### PR TITLE
th1520-i2s: Fix kernel panic when reading sysfs registers

### LINKED ISSUE #175: th1520-i2s: 读取sysfs registers属性时内核崩溃
当访问TH1520 I2S音频驱动的sysfs调试接口时会触发内核崩溃，复现方法：

1. 确认已加载 th1520-i2s 驱动
2. `# cat /sys/devices/platform/soc/ffe7034000.ap-i2s/th1520_i2s_debug/registers`
3. 系统触发内核Oops

```
[ 7149.857140][T102963] Unable to handle kernel access to user memory without uaccess routines at virtual address 0000000000000204
[ 7149.857148][T102963] Oops [#1]
[ 7149.857152][T102963] Modules linked in: vfio vhost_net tap vhost_vsock vmw_vsock_virtio_transport_common vhost vhost_iotlb vsock binfmt_misc nfsv3 tls tun brd ntfs exfat btrfs blake2b_generic xor raid6_pq xfs sctp ip6_udp_tunnel udp_tunnel nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip_set nf_tables libcrc32c onboard_usb_hub aic8800_bsp dwc3 udc_core roles rtw88_8723ds rtw88_8723d rtw88_sdio rtw88_core th1520_adc etnaviv mr75203 rtc_xgene dwc3_xuantie gpu_sched pwm_fan uio_pdrv_genirq uio sch_fq_codel nfnetlink
[ 7149.857303][T102963] CPU: 2 PID: 102963 Comm: read_all Not tainted 6.6.0-102.0.0.5.oe2509.riscv64 #1
[ 7149.857310][T102963] Hardware name: Sipeed Lichee Pi 4A 16G (DT)
[ 7149.857314][T102963] epc : regmap_read+0x16/0x5a
[ 7149.857328][T102963]  ra : th1520_i2s_show+0x70/0xb2
[ 7149.857340][T102963] epc : ffffffff809aa8b6 ra : ffffffff80ccfdea sp : ffffffc800d9bc60
[ 7149.857345][T102963]  gp : ffffffff82687ab8 tp : ffffffda308a2ac0 t0 : ffffffff8217cbe0
[ 7149.857349][T102963]  t1 : ffffffff8130e4d0 t2 : ffffffff8123cad0 s0 : ffffffc800d9bc90
[ 7149.857354][T102963]  s1 : 0000000000000000 a0 : 0000000000000000 a1 : 0000000000000000
[ 7149.857359][T102963]  a2 : ffffffc800d9bc94 a3 : 0000000000000010 a4 : 0000000000000000
[ 7149.857364][T102963]  a5 : 0000000000000000 a6 : 0000000000000000 a7 : ffffffffffffffff
[ 7149.857369][T102963]  s2 : ffffffd9019ca040 s3 : 0000000000000100 s4 : ffffffd90715a540
[ 7149.857374][T102963]  s5 : 0000000000001000 s6 : 0000000000000000 s7 : ffffffd9077476b8
[ 7149.857378][T102963]  s8 : 0000000000400cc0 s9 : fffffffffffff000 s10: ffffffd9077476c8
[ 7149.857383][T102963]  s11: 000000007ffff000 t3 : 0000003f8ff7df62 t4 : ffffffffffffffff
[ 7149.857387][T102963]  t5 : 00000004ff84538e t6 : ffffffff8273da1a
[ 7149.857392][T102963] status: 0000000200000120 badaddr: 0000000000000204 cause: 000000000000000d
[ 7149.857397][T102963] [<ffffffff809aa8b6>] regmap_read+0x16/0x5a
[ 7149.857405][T102963] [<ffffffff80ccfdea>] th1520_i2s_show+0x70/0xb2
[ 7149.857412][T102963] [<ffffffff8097c348>] dev_attr_show+0x1c/0x4c
[ 7149.857420][T102963] [<ffffffff803c5b38>] sysfs_kf_seq_show+0x74/0xc8
[ 7149.857430][T102963] [<ffffffff803c4330>] kernfs_seq_show+0x20/0x28
[ 7149.857439][T102963] [<ffffffff8034e3b4>] seq_read_iter+0x156/0x32a
[ 7149.857451][T102963] [<ffffffff803c51cc>] kernfs_fop_read_iter+0x3a/0x42
[ 7149.857459][T102963] [<ffffffff8031c306>] vfs_read+0x1a2/0x220
[ 7149.857468][T102963] [<ffffffff8031ce0a>] ksys_read+0x62/0xde
[ 7149.857475][T102963] [<ffffffff8031cea6>] __riscv_sys_read+0x20/0x28
[ 7149.857483][T102963] [<ffffffff810dc33e>] do_trap_ecall_u+0x72/0x162
[ 7149.857492][T102963] [<ffffffff810e9128>] ret_from_exception+0x0/0x64
[ 7149.857506][T102963] Code: 0000 0013 0000 7179 f022 f406 ec26 e84a e44e 1800 (2783) 2045 
[ 7149.857512][T102963] ---[ end trace 0000000000000000 ]---
[ 7149.857525][T102963] th1520-event soc:th1520-event: set rebootmode:0x22
[ 7149.857532][T102963] Kernel panic - not syncing: Fatal exception
[ 7149.857535][T102963] SMP: stopping secondary CPUs
[ 7150.524242][T102963] SMP: failed to stop secondary CPUs 1-2
[ 7150.524252][T102963] [panic_cpufreq_notifier_call]Match the clock sw status to the hw after rst
[ 7150.953006][T102963] ---[ end Kernel panic - not syncing: Fatal exception ]---
```

该问题导致 LTP 在 LPI4A 上测试失败，相关报告链接：
https://gitee.com/openeuler/RISC-V/issues/ICXA4L

### PR DESCRIPTION
**Pull request by xmzzz**
Fix: https://github.com/RVCK-Project/rvck/issues/175

基于 rvck-olk/OLK-next 分支测试。
验证方法：

- 启动 LPI4A 平台；
- `$ sudo cat /sys/devices/platform/soc/ffe7034000.ap-i2s/th1520_i2s_debug/registers`

打补丁前：
```
[  118.379972][ T1241] i2s reg[0x68]=0x0
[  118.383657][ T1241] i2s reg[0x6c]=0x0
[  118.387347][ T1241] Unable to handle kernel access to user memory without uaccess routines at virtual address 0000000000000204
[  118.398782][ T1241] Oops [#1]
[  118.401759][ T1241] Modules linked in: nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nk
[  118.439260][ T1241] CPU: 2 PID: 1241 Comm: cat Not tainted 6.6.0-next-1204 #1
[  118.446402][ T1241] Hardware name: Sipeed Lichee Pi 4A (DT)
[  118.451979][ T1241] epc : regmap_read+0x12/0x58
[  118.456527][ T1241]  ra : th1520_i2s_show+0x70/0xb2
[  118.461417][ T1241] epc : ffffffff80a02746 ra : ffffffff80d45f90 sp : ffffffc802653c50
[  118.469335][ T1241]  gp : ffffffff8207fc90 tp : ffffffd905abd700 t0 : 3000000000000000
[  118.477251][ T1241]  t1 : 00000000ffff7fff t2 : 305b676572207332 s0 : ffffffc802653c80
[  118.485171][ T1241]  s1 : 0000000000000000 a0 : 0000000000000000 a1 : 0000000000000000
[  118.493088][ T1241]  a2 : ffffffc802653c84 a3 : 0000000000000010 a4 : 0000000000000000
[  118.501005][ T1241]  a5 : 0000000000000000 a6 : 0000000000000003 a7 : c0000000ffff7fff
[  118.508922][ T1241]  s2 : ffffffd90167a440 s3 : 0000000000000100 s4 : ffffffc802653e18
[  118.516837][ T1241]  s5 : ffffffd9037c2898 s6 : fffffffffffff000 s7 : 000000007ffff000
[  118.524753][ T1241]  s8 : 0000003fbdd1a030 s9 : ffffffc802653df0 s10: 0000000000020000
[  118.532670][ T1241]  s11: 0000003fb5696d60 t3 : ffffffc802653ac0 t4 : ffffffff81e2df00
[  118.540586][ T1241]  t5 : ffffffff8209f2c0 t6 : ffffffc802653ad8
[  118.546593][ T1241] status: 0000000200000120 badaddr: 0000000000000204 cause: 000000000000000d
[  118.555205][ T1241] [<ffffffff80a02746>] regmap_read+0x12/0x58
[  118.561044][ T1241] [<ffffffff80d45f90>] th1520_i2s_show+0x70/0xb2
[  118.567229][ T1241] [<ffffffff809d24e6>] dev_attr_show+0x1a/0x50
[  118.573241][ T1241] [<ffffffff803db26c>] sysfs_kf_seq_show+0x74/0xe2
[  118.579602][ T1241] [<ffffffff803d9a68>] kernfs_seq_show+0x20/0x28
[  118.585784][ T1241] [<ffffffff8035d7f8>] seq_read_iter+0xda/0x36c
[  118.591886][ T1241] [<ffffffff803da884>] kernfs_fop_read_iter+0x3a/0x42
[  118.598503][ T1241] [<ffffffff803284b6>] vfs_read+0x204/0x2aa
[  118.604255][ T1241] [<ffffffff80329156>] ksys_read+0x6a/0xf0
[  118.609919][ T1241] [<ffffffff803291fc>] __riscv_sys_read+0x20/0x28
[  118.616188][ T1241] [<ffffffff81178b2e>] do_trap_ecall_u+0xa8/0x19a
[  118.622467][ T1241] [<ffffffff81186c3c>] ret_from_exception+0x0/0x64
[  118.628845][ T1241] Code: b799 0013 0000 0013 0000 7179 f022 f406 ec26 1800 (2783) 2045 
[  118.637001][ T1241] ---[ end trace 0000000000000000 ]---
[  118.642353][ T1241] th1520-event soc:th1520-event: set rebootmode:0x22
[  118.648905][ T1241] Kernel panic - not syncing: Fatal exception
[  118.654828][ T1241] SMP: stopping secondary CPUs
[  118.659475][ T1241] [panic_cpufreq_notifier_call]Match the clock sw status to the hw after rst
[  118.668248][ T1241] ---[ end Kernel panic - not syncing: Fatal exception ]---
```

打补丁后：
```
[   44.156340][ T1210] i2s reg[0x64]=0x0
[   44.160029][ T1210] i2s reg[0x68]=0x0
[   44.163711][ T1210] i2s reg[0x6c]=0x0
[   44.167397][ T1210] No CPR regmap for ap-i2s                 <========= 正常打印
[   44.177689][ T1211] i2s reg[0x0]=0x0
[   44.181324][ T1211] i2s reg[0x4]=0x0
[   44.184948][ T1211] i2s reg[0x8]=0x0
[   44.188562][ T1211] i2s reg[0xc]=0x0
[   44.192170][ T1211] i2s reg[0x10]=0x0
[   44.195863][ T1211] i2s reg[0x14]=0x0
[   44.199553][ T1211] i2s reg[0x18]=0x0
[   44.203243][ T1211] i2s reg[0x1c]=0x0
[   44.206907][ T1211] i2s reg[0x20]=0x0
[   44.210596][ T1211] i2s reg[0x24]=0x0
[   44.214284][ T1211] i2s reg[0x28]=0x0
[   44.217972][ T1211] i2s reg[0x2c]=0x0
[   44.221668][ T1211] i2s reg[0x30]=0x0
[   44.225375][ T1211] i2s reg[0x34]=0x0
[   44.229087][ T1211] i2s reg[0x38]=0x0
[   44.232783][ T1211] i2s reg[0x3c]=0x0
[   44.236474][ T1211] i2s reg[0x40]=0x0
[   44.240170][ T1211] i2s reg[0x44]=0x0
[   44.243865][ T1211] i2s reg[0x48]=0x0
[   44.247554][ T1211] i2s reg[0x4c]=0x0
[   44.251239][ T1211] i2s reg[0x50]=0x0
[   44.254905][ T1211] i2s reg[0x54]=0x0
[   44.258590][ T1211] i2s reg[0x58]=0x0
[   44.262274][ T1211] i2s reg[0x5c]=0x0
[   44.265956][ T1211] i2s reg[0x60]=0x0
[   44.269642][ T1211] i2s reg[0x64]=0x0
[   44.273325][ T1211] i2s reg[0x68]=0x0
[   44.277010][ T1211] i2s reg[0x6c]=0x0
[   44.280702][ T1211] cpr reg[0x0]=0x1ac00f
[   44.284735][ T1211] cpr reg[0x4]=0x3f2535f
[   44.288858][ T1211] cpr reg[0x8]=0x2000000
[   44.292978][ T1211] cpr reg[0xc]=0x7000
[   44.296844][ T1211] cpr reg[0x10]=0x7fbff1f
[   44.301053][ T1211] cpr reg[0x14]=0x7ffff18
...
```

### CODE REVIEW

**Comment by xmzzz** [comment]
/check


---

**开始测试 log: [https://github.com/RVCK-Project/rvck/actions/runs/20152176350](https://github.com/RVCK-Project/rvck/actions/runs/20152176350)**

<details>

<summary>参数解析结果</summary>

|args|value|
|:-:|:-:|
| repository | RVCK-Project/rvck |
| head ref | pull/176/head |
| base ref | rvck-6.6 |
|LAVA repo | RVCK-Project/lavaci |
|LAVA Template | lava-job-template/qemu/qemu-ltp.yaml |
|Testcase path | lava-testcases/common-test/ltp/ltp.yaml |
|need run job | kunit-test,kernel-build,check-patch,lava-trigger |

</details>

---

**测试完成**
<details>

<summary> 详细结果:</summary>

# RVCK result

| check | result |
| :-: | :-: |
|kunit-test| success |
|kernel-build| success |
|lava-trigger| success |
|check-patch| success |

## Kunit Test Result

[00:43:29] Testing complete. Ran 455 tests: passed: 443, skipped: 12

## Kernel Build Result

Kernel build succeeded: [RVCK-Project/rvck/176_3644403574](https://repo.tarsier-infra.isrc.ac.cn/openEuler-RISC-V/RVCK/OERV-RVCI/RVCK-Project/rvck/176_3644403574)/

ebf90091bced3e68eedd262da54fc1aa  /srv/guix_result/6623157044904f30536f78afb3bcd9a2541450cc/Image
aad0ba574350f637c11e0f3a3a1304bf  /root/initramfs.img


## LAVA Check

### args:

- testcase_repo: RVCK-Project/lavaci
- testcase_ref: main
- lava_template: lava-job-template/qemu/qemu-ltp.yaml
- testcase_path: lava-testcases/common-test/ltp/ltp.yaml
- testitem_name: RVCK-Project_rvck_issue_comment_176__3644403574_common-test_qemu
- kernel_download_url: https://repo.tarsier-infra.isrc.ac.cn/openEuler-RISC-V/RVCK/OERV-RVCI/RVCK-Project/rvck/176_3644403574/Image
- initramfs_download_url: https://repo.tarsier-infra.isrc.ac.cn/openEuler-RISC-V/RVCK/OERV-RVCI/RVCK-Project/rvck/176_3644403574/initramfs.img
- rootfs_download_url: https://fast-mirror.isrc.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/RVCK/openEuler24.03-LTS-SP1/openeuler-rootfs.img.zst

### result:

Lava check done! lava log: https://lava.oerv.ac.cn/scheduler/job/1011

lava result count: [fail]: 173, [pass]: 1435, [skip]: 291


## Check Patch Result

| | |
|---|---|
| Total Errors | 0 |
| Total Warnings | 3 |

</details>

File: sound/soc/xuantie/th1520-i2s.c [hunk 1]
```diff
@@ -649,15 +649,20 @@ static ssize_t th1520_i2s_show(struct device *dev, struct device_attribute *attr
         u32 value, i;
         struct th1520_i2s_priv *priv = dev_get_drvdata(dev);
 
-        for (i = I2S_IISEN; i <= I2S_DR4; i+=0x4) {
+	for (i = I2S_IISEN; i <= I2S_DR4; i += 0x4) {
```
Comment (sterling-teng) [inline sound/soc/xuantie/th1520-i2s.c:652]: 需要调整下缩进，tab为8个空格。

**Comment by xmzzz** [comment]
感谢合并。看了下 checkpatch 结果，缩进问题好像是由于原来的补丁存在很多未解决格式问题，可能当时未启用 checkpatch 检查。这个建议后面提交单独的补丁解决源文件的格式问题
@sterling-teng
