### PR TITLE
【backport】RISC-V SBI FWFT 扩展支持

### LINKED ISSUE #239: 【backport】RISC-V SBI FWFT 扩展支持
本PR实现以下主要功能：

1. SBI FWFT (Firmware Feature) 扩展支持

- [x] 允许S-mode请求特定的硬件或软件特性启用

- [x] 实现非对齐访问异常委托给S-mode，由内核直接处理

2. KVM FWFT SBI 扩展支持

- [x] 基于非对齐访问处理基础设施

- [x] 支持在KVM虚拟化环境中测试异常委托

该功能合入以下补丁，均来自L0社区

1、PR 199 和 PR 207的bugfix，
475afa39b123 riscv: Fix the __riscv_copy_vec_words_unaligned implementation
33981b1c4e49 riscv: Fix missing __free_pages() in check_vector_unaligned_access()
61a74ad25462 riscv: misaligned: fix sleeping function called during misaligned access handling
7b30b1b04e0d riscv: misaligned: Add handling for ZCB instructions
fd94de9f9e7a riscv: misaligned: factorize trap handling
453805f0a28f riscv: misaligned: enable IRQs while handling misaligned accesses
897e8aece3c8 riscv: misaligned: use get_user() instead of __get_user()
2f73c62d4e13 Revert "riscv: misaligned: fix sleeping function called during misaligned access handling"

2、fwft功能的前置补丁
SBI调用追踪、代码优化
56c1c1a09ab9 riscv: Add tracepoints for SBI calls and returns
16badacd8af4 riscv: Improve sbi_ecall() code generation by reordering arguments

替代指令修复
441016056010 riscv: Fix unaligned access info messages
1ff95eb2bebd riscv: Fix RISCV_ALTERNATIVE_EARLY

KVM虚拟化调试支持和测试
edcbe90f1289 RISC-V: KVM: Implement kvm_arch_vcpu_ioctl_set_guest_debug()
1df1fb521b9d RISC-V: KVM: Handle breakpoint exits for VCPU
f1c48c1ec735 RISC-V: KVM: selftests: Add ebreak test support

3、fwft功能
非kvm处理
cf8651f7319d riscv: sbi: add Firmware Feature (FWFT) SBI extensions definitions
a7cd450f0e06 riscv: sbi: remove useless parenthesis
99cf5b7c7387 riscv: sbi: add new SBI error mappings
6d6d0641dcfa riscv: sbi: add FWFT extension interface
cf5a8abc6560 riscv: misaligned: request misaligned exception from SBI
9f9f6fdd1dc6 riscv: misaligned: use on_each_cpu() for scalar misaligned access probing
1317045a7d6f riscv: misaligned: declare misaligned_access_speed under CONFIG_RISCV_MISALIGNED
4eaaa65e3012 riscv: misaligned: move emulated access uniformity check in a function
7977448bf374 riscv: misaligned: add a function to check misalign trap delegability

kvm处理
cf648c400fd2 RISC-V: KVM: add SBI extension init()/deinit() functions
c046de827c85 RISC-V: KVM: add SBI extension reset callback
6b72fd170592 RISC-V: KVM: add support for FWFT SBI extension
bb053f816a8b RISC-V: KVM: add support for SBI_FWFT_MISALIGNED_DELEG

3、fwft的一些代码优化
932131fd3ed2 riscv: Fix typo EXRACT -> EXTRACT
833bbb0d91d2 riscv: Strengthen duplicate and inconsistent definition of RV_X()
a60173223683 riscv: Move all duplicate insn parsing macros into asm/insn.h

### PR DESCRIPTION
**Pull request by uestc-gr**
fixed: #239

已backport L0社区关于sbi3.0的fwft的补丁，具体合入的补丁列表见issues，目前社区只完成了fwft关于内核非对齐的处理。

已经测试通过，具体测试方法
1、使用开源最新的opensbi

2、使用新的qemu，并合入以下补丁
https://lists.libreplanet.org/archive/html/qemu-riscv/2024-12/msg00224.html

3、使用新编译的的sbi和qemu启动tcg虚拟机
$ qemu-system-riscv64
-cpu rv64,trap-misaligned-access=true,v=true
-M virt
-m 1024M
-bios fw_dynamic.bin
-kernel Image

4、运行测试用例
https://github.com/clementleger/unaligned_test

/home # ./unaligned 
Buf base address: 0xded40
Testing emulated misaligned accesses, size 2, offset 1
Testing non-emulated misaligned accesses, size 2, offset 1
Testing emulated misaligned accesses, size 4, offset 1
Testing non-emulated misaligned accesses, size 4, offset 1
Testing emulated misaligned accesses, size 4, offset 2
Testing non-emulated misaligned accesses, size 4, offset 2
Testing emulated misaligned accesses, size 4, offset 3
Testing non-emulated misaligned accesses, size 4, offset 3
Testing emulated misaligned accesses, size 8, offset 1
Testing non-emulated misaligned accesses, size 8, offset 1
Testing emulated misaligned accesses, size 8, offset 2
Testing non-emulated misaligned accesses, size 8, offset 2
Testing emulated misaligned accesses, size 8, offset 3
Testing non-emulated misaligned accesses, size 8, offset 3
Testing emulated misaligned accesses, size 8, offset 4
Testing non-emulated misaligned accesses, size 8, offset 4
Testing emulated misaligned accesses, size 8, offset 5
Testing non-emulated misaligned accesses, size 8, offset 5
Testing emulated misaligned accesses, size 8, offset 6
Testing non-emulated misaligned accesses, size 8, offset 6
Testing emulated misaligned accesses, size 8, offset 7
Testing non-emulated misaligned accesses, size 8, offset 7

执行kvm unit测试
./lkvm-static run -k ./sbi.flat -m 256 -c 4 --console serial --name riscv-sbi
.......
PASS: sbi: fwft: base: get reserved feature 0x6: SBI_ERR_DENIED
PASS: sbi: fwft: base: set reserved feature 0x6: SBI_ERR_DENIED
PASS: sbi: fwft: base: get reserved feature 0x3fffffff: SBI_ERR_DENIED
PASS: sbi: fwft: base: set reserved feature 0x3fffffff: SBI_ERR_DENIED
PASS: sbi: fwft: base: get reserved feature 0x80000000: SBI_ERR_DENIED
PASS: sbi: fwft: base: set reserved feature 0x80000000: SBI_ERR_DENIED
PASS: sbi: fwft: base: get reserved feature 0xbfffffff: SBI_ERR_DENIED
PASS: sbi: fwft: base: set reserved feature 0xbfffffff: SBI_ERR_DENIED
PASS: sbi: fwft: misaligned_exc_deleg: Get misaligned deleg feature: SBI_SUCCESS
SKIP: sbi: fwft: misaligned_exc_deleg: missing MISALIGNED_EXC_DELEG_RESET environment variable
PASS: sbi: fwft: misaligned_exc_deleg: Set misaligned deleg feature invalid value 2: SBI_ERR_INVALID_PARAM
PASS: sbi: fwft: misaligned_exc_deleg: Set misaligned deleg feature invalid value 0xFFFFFFFF: SBI_ERR_INVALID_PARAM
PASS: sbi: fwft: misaligned_exc_deleg: Set misaligned deleg with invalid value > 32bits: SBI_ERR_INVALID_PARAM
PASS: sbi: fwft: misaligned_exc_deleg: Set misaligned deleg with invalid flag > 32bits: SBI_ERR_INVALID_PARAM
PASS: sbi: fwft: misaligned_exc_deleg: set to 0: SBI_SUCCESS
PASS: sbi: fwft: misaligned_exc_deleg: get 0 after set
PASS: sbi: fwft: misaligned_exc_deleg: set to 1: SBI_SUCCESS
PASS: sbi: fwft: misaligned_exc_deleg: get 1 after set
PASS: sbi: fwft: misaligned_exc_deleg: Misaligned load exception trap in S-mode
PASS: sbi: fwft: misaligned_exc_deleg: Set misaligned deleg feature value 0 and lock: SBI_SUCCESS
PASS: sbi: fwft: misaligned_exc_deleg: locked: Set to 0 without lock flag: SBI_ERR_DENIED_LOCKED
PASS: sbi: fwft: misaligned_exc_deleg: locked: Set to 0 with lock flag: SBI_ERR_DENIED_LOCKED
PASS: sbi: fwft: misaligned_exc_deleg: locked: Set to 1 without lock flag: SBI_ERR_DENIED_LOCKED
PASS: sbi: fwft: misaligned_exc_deleg: locked: Set to 1 with lock flag: SBI_ERR_DENIED_LOCKED
PASS: sbi: fwft: misaligned_exc_deleg: locked: Get value 0

### CODE REVIEW

**Comment by uestc-gr** [comment]
该PR已经完成，所有补丁均来自L0社区，自测通过，请老师评审

File: arch/arm64/include/uapi/asm/kvm.h [hunk 1]
```diff
@@ -37,7 +37,6 @@
 #include <asm/ptrace.h>
```
Comment (sterling-teng) [inline arch/arm64/include/uapi/asm/kvm.h:37]: 这个补丁的commit message格式不符合规范，需要有必要的tag。

Comment (uestc-gr) [reply arch/arm64/include/uapi/asm/kvm.h:37]: 已修订，请老师检查

**Comment by uestc-gr** [comment]
lava报错应该是initramfs 中的内核模块（dm_mod、sunrpc、dax 等）是用不同版本的内核源码编译的，与当前运行的内核不一致
image

**Comment by sterling-teng** [comment]
我再重跑一遍确认下。

**Comment by sterling-teng** [comment]
我在milkv pioneer上测试，这个pr在空负载时降低了风扇转速，很安静。但是执行poweroff后，风扇转速升高，主板不下电，关机失败。这个pr需要更多的物理机测试。

**Comment by wangliu-iscas** [comment]
/check


---

**开始测试 log: [https://github.com/RVCK-Project/rvck/actions/runs/23626430310](https://github.com/RVCK-Project/rvck/actions/runs/23626430310)**

<details>

<summary>参数解析结果</summary>

|args|value|
|:-:|:-:|
| repository | RVCK-Project/rvck |
| head ref | pull/242/head |
| base ref | rvck-6.6 |
|LAVA repo | RVCK-Project/lavaci |
|LAVA Template | lava-job-template/qemu/qemu-ltp.yaml |
|Testcase path | lava-testcases/common-test/ltp/ltp.yaml |
|need run job | kunit-test,kernel-build,check-patch,lava-trigger |

</details>

---

**测试完成**
<details>

<summary> 详细结果:</summary>

# RVCK result

| check | result |
| :-: | :-: |
|kunit-test| success |
|kernel-build| success |
|lava-trigger| success |
|check-patch| success |

## Kunit Test Result

[01:26:54] Testing complete. Ran 457 tests: passed: 445, skipped: 12

## Kernel Build Result

Kernel build succeeded: [RVCK-Project/rvck/242_4139390880](https://repo.tarsier-infra.isrc.ac.cn/openEuler-RISC-V/RVCK/OERV-RVCI/RVCK-Project/rvck/242_4139390880)/

b1ff7fac35a084b092bcf195bc4de765  /srv/guix_result/663cf967ee1bd7aca77f0b01a11420473e8b48c4/Image
cf6f4e333ead60ee0a333e92fd72dca5  /root/initramfs.img


## LAVA Check

### args:

- testcase_repo: RVCK-Project/lavaci
- testcase_ref: main
- lava_template: lava-job-template/qemu/qemu-ltp.yaml
- testcase_path: lava-testcases/common-test/ltp/ltp.yaml
- testitem_name: RVCK-Project_rvck_issue_comment_242__4139390880_common-test_qemu
- kernel_download_url: https://repo.tarsier-infra.isrc.ac.cn/openEuler-RISC-V/RVCK/OERV-RVCI/RVCK-Project/rvck/242_4139390880/Image
- initramfs_download_url: https://repo.tarsier-infra.isrc.ac.cn/openEuler-RISC-V/RVCK/OERV-RVCI/RVCK-Project/rvck/242_4139390880/initramfs.img
- rootfs_download_url: https://fast-mirror.isrc.ac.cn/openeuler-sig-riscv/openEuler-RISC-V/RVCK/openEuler24.03-LTS-SP1/openeuler-rootfs.img.zst

### result:

Lava check done! lava log: https://lava.oerv.ac.cn/scheduler/job/1640

lava result count: [fail]: 175, [pass]: 1434, [skip]: 290


## Check Patch Result

| | |
|---|---|
| Total Errors | 0 |
| Total Warnings | 39 |

</details>

**Comment by uestc-gr** [comment]
> 我在milkv pioneer上测试，这个pr在空负载时降低了风扇转速，很安静。但是执行poweroff后，风扇转速升高，主板不下电，关机失败。这个pr需要更多的物理机测试。

理论上这个功能 在不支持sbi3.0的设备不会开启，即使开启了也只会处理非对齐处理，不会影响其它流程，是否是与lava故障一样initramfs没有重新编译导致，能否取一下上下电串口日志看看

**Comment by sterling-teng** [comment]
> > 我在milkv pioneer上测试，这个pr在空负载时降低了风扇转速，很安静。但是执行poweroff后，风扇转速升高，主板不下电，关机失败。这个pr需要更多的物理机测试。
> 
> 理论上这个功能 在不支持sbi3.0的设备不会开启，即使开启了也只会处理非对齐处理，不会影响其它流程，是否是与lava故障一样initramfs没有重新编译导致，能否取一下上下电串口日志看看

boot
```
[    0.000000] software IO TLB: mapped [mem 0x00000000bbe3d000-0x00000000bfe3d000] (64MB)
[    0.000000] Memory: 126955100K/130023424K available (11202K kernel code, 5727K rwdata, 10240K rodata, 2714K init, 520K bss, 2806180K reserved, 262144K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=64, Nodes=4
[    0.000000] ftrace: allocating 41282 entries in 162 pages
[    0.000000] ftrace: allocated 162 pages with 3 groups
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000]  Rude variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] riscv-intc: 64 local interrupts mapped
[    0.000000] riscv-plic: interrupt-controller@7090000000: mapped 224 interrupts with 64 handlers for 128 contexts.
[    0.000000] riscv: providing IPIs using SBI IPI extension
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0xb8812736b, max_idle_ns: 440795202655 ns
[    0.000000] sched_clock: 64 bits at 50MHz, resolution 20ns, wraps every 4398046511100ns
[    0.008513] clocksource: dw-apb-timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 38225208935 ns
[    0.018423] sched_clock: 32 bits at 50MHz, resolution 20ns, wraps every 42949672950ns
[    0.026951] Console: colour dummy device 80x25
[    0.031422] printk: console [tty0] enabled
[    0.035532] printk: bootconsole [uart0] disabled
[    0.000000] Linux version 6.6.127+ (root@openeuler-riscv64) (gcc (GCC) 12.3.1 (openEuler 12.3.1-62.oe2403sp1), GNU ld (GNU Binutils) 2.41) #4 SMP Fri Mar 27 01:16:22 CST 2026
[    0.000000] Machine model: Sophgo Mango
[    0.000000] SBI specification v1.0 detected
[    0.000000] SBI implementation ID=0x1 Version=0x10002
[    0.000000] SBI TIME extension detected
[    0.000000] SBI IPI extension detected
[    0.000000] SBI RFENCE extension detected
[    0.000000] SBI SRST extension detected
[    0.000000] efi: EFI v2.7 by EDK II
[    0.000000] efi: SMBIOS=0xbffdc000 INITRD=0xb7a0ea98 MEMRESERVE=0xb7a0e118 
[    0.000000] OF: reserved mem: 0x0000000000000000..0x00000000001fffff (2048 KiB) map non-reusable mmode_resv0@0
[    0.000000] cma: Reserved 256 MiB at 0x0000000098200000 on node -1
[    0.000000] earlycon: uart0 at MMIO32 0x0000007040000000 (options '')
[    0.000000] printk: bootconsole [uart0] enabled
[    0.000000] OF: NUMA: parsing numa-distance-map-v1
[    0.000000] NUMA: NODE_DATA [mem 0x7ffffdfc0-0x7ffffffff]
[    0.000000] NUMA: NODE_DATA [mem 0xfffffdfc0-0xfffffffff]
[    0.000000] NUMA: NODE_DATA [mem 0x17ffffdfc0-0x17ffffffff]
[    0.000000] NUMA: NODE_DATA [mem 0x1f42531fc0-0x1f42533fff]
[    0.000000] Zone ranges:
[    0.000000]   DMA32    [mem 0x0000000002800000-0x00000000ffffffff]
[    0.000000]   Normal   [mem 0x0000000100000000-0x0000001f427fffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000002800000-0x00000000bfe3cfff]
[    0.000000]   node   0: [mem 0x00000000bfe3d000-0x00000000bfffefff]
[    0.000000]   node   0: [mem 0x00000000bffff000-0x00000000bfffffff]
[    0.000000]   node   0: [mem 0x0000000100000000-0x00000007ffffffff]
[    0.000000]   node   1: [mem 0x0000000800000000-0x0000000fffffffff]
[    0.000000]   node   2: [mem 0x0000001000000000-0x00000017ffffffff]
[    0.000000]   node   3: [mem 0x0000001800000000-0x0000001f427fffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000002800000-0x00000007ffffffff]
[    0.000000] Initmem setup node 1 [mem 0x0000000800000000-0x0000000fffffffff]
[    0.000000] Initmem setup node 2 [mem 0x0000001000000000-0x00000017ffffffff]
[    0.000000] Initmem setup node 3 [mem 0x0000001800000000-0x0000001f427fffff]
[    0.000000] On node 0, zone DMA32: 10240 pages in unavailable ranges
[    0.000000] On node 3, zone Normal: 22528 pages in unavailable ranges
[    0.000000] SBI HSM extension detected
[    0.000000] Falling back to deprecated "riscv,isa"
[    0.000000] Vendor extensions are ignored in riscv,isa. Use riscv,isa-extensions instead.
[    0.000000] riscv: base ISA extensions acdfim
[    0.000000] riscv: ELF capabilities acdfim
[    0.000000] Ticket spinlock: enabled
[    0.000000] percpu: cpu 0 has no node -1 or node-local memory
[    0.000000] percpu: Embedded 29 pages/cpu s80872 r8192 d29720 u118784
[    0.000000] Kernel command line: BOOT_IMAGE=/Image root=/dev/nvme0n1p3 ro selinux=0 console=ttyS0,115200 console=tty earlycon rootwait
[    0.000000] Unknown kernel command line parameters "selinux=0", will be passed to user space.
[    0.000000] printk: log_buf_len individual max cpu contribution: 4096 bytes
[    0.000000] printk: log_buf_len total cpu_extra contributions: 258048 bytes
[    0.000000] printk: log_buf_len min size: 131072 bytes
[    0.000000] printk: log_buf_len: 524288 bytes
[    0.000000] printk: early log buf free: 127264(97%)
[    0.000000] Fallback order for Node 0: 0 1 2 3 
[    0.000000] Fallback order for Node 1: 1 0 3 2 
[    0.000000] Fallback order for Node 2: 2 3 0 1 
[    0.000000] Fallback order for Node 3: 3 2 1 0 
[    0.000000] Built 4 zonelists, mobility grouping on.  Total pages: 31870976
[    0.000000] Policy zone: Normal
[    0.000000] mem auto-init: stack:all(pattern), heap alloc:on, heap free:off
[    0.000000] software IO TLB: area num 64.
[    0.000000] software IO TLB: mapped [mem 0x00000000bbe3d000-0x00000000bfe3d000] (64MB)
[    0.000000] Memory: 126955100K/130023424K available (11202K kernel code, 5727K rwdata, 10240K rodata, 2714K init, 520K bss, 2806180K reserved, 262144K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=64, Nodes=4
[    0.000000] ftrace: allocating 41282 entries in 162 pages
[    0.000000] ftrace: allocated 162 pages with 3 groups
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000]  Rude variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] riscv-intc: 64 local interrupts mapped
[    0.000000] riscv-plic: interrupt-controller@7090000000: mapped 224 interrupts with 64 handlers for 128 contexts.
[    0.000000] riscv: providing IPIs using SBI IPI extension
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0xb8812736b, max_idle_ns: 440795202655 ns
[    0.000000] sched_clock: 64 bits at 50MHz, resolution 20ns, wraps every 4398046511100ns
[    0.008513] clocksource: dw-apb-timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 38225208935 ns
[    0.018423] sched_clock: 32 bits at 50MHz, resolution 20ns, wraps every 42949672950ns
[    0.026951] Console: colour dummy device 80x25
[    0.031422] printk: console [tty0] enabled
[    0.035532] printk: bootconsole [uart0] disabled
[    0.041611] mempolicy: Enabling automatic NUMA balancing. Configure with numa_balancing= or the kernel.numa_balancing sysctl
[    0.041730] Calibrating delay loop (skipped), value calculated using timer frequency.. 100.00 BogoMIPS (lpj=200000)
[    0.041756] pid_max: default: 65536 minimum: 512
[    0.044623] LSM: initializing lsm=lockdown,capability,landlock,yama,apparmor,tomoyo,bpf,integrity
[    0.044689] landlock: Up and running.
[    0.044698] Yama: becoming mindful.
[    0.044817] AppArmor: AppArmor initialized
[    0.044837] TOMOYO Linux initialized
[    0.044868] LSM support for eBPF active
[    0.068355] Dentry cache hash table entries: 8388608 (order: 14, 67108864 bytes, vmalloc hugepage)
[    0.080238] Inode-cache hash table entries: 4194304 (order: 13, 33554432 bytes, vmalloc hugepage)
[    0.081298] Mount-cache hash table entries: 131072 (order: 8, 1048576 bytes, vmalloc)
[    0.081808] Mountpoint-cache hash table entries: 131072 (order: 8, 1048576 bytes, vmalloc)
[    0.130600] RCU Tasks Rude: Setting shift to 6 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=64.
[    0.130766] RCU Tasks Trace: Setting shift to 6 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=64.
[    0.130865] riscv: ELF compat mode unsupported
[    0.131020] ASID allocator using 16 bits (65536 entries)
[    0.131182] rcu: Hierarchical SRCU implementation.
[    0.131197] rcu:     Max phase no-delay instances is 1000.
[    0.131863] Remapping and enabling EFI services.
[    0.135082] smp: Bringing up secondary CPUs ...
[    0.180707] smp: Brought up 4 nodes, 64 CPUs
[    0.212594] devtmpfs: initialized
[    0.221711] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.222216] futex hash table entries: 16384 (order: 8, 1048576 bytes, vmalloc)
[    0.229045] pinctrl core: initialized pinctrl subsystem
[    0.229882] SMBIOS 2.8 present.
[    0.229913] DMI: SOPHGO Sophgo SG2042 EVB Board/Sophgo SG2042 EVB Board, BIOS V1.0 Mar 27 2024
[    0.231476] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.234102] DMA: preallocated 4096 KiB GFP_KERNEL pool for atomic allocations
[    0.235062] DMA: preallocated 4096 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.236066] audit: initializing netlink subsys (disabled)
[    0.236423] audit: type=2000 audit(0.208:1): state=initialized audit_enabled=0 res=1
[    0.237182] thermal_sys: Registered thermal governor 'fair_share'
[    0.237194] thermal_sys: Registered thermal governor 'bang_bang'
[    0.237216] thermal_sys: Registered thermal governor 'step_wise'
[    0.237227] thermal_sys: Registered thermal governor 'user_space'
[    0.237238] thermal_sys: Registered thermal governor 'power_allocator'
[    0.237359] cpuidle: using governor ladder
[    0.237423] cpuidle: using governor menu
[    0.265051] cpu63: Ratio of byte access time to unaligned word access is 2.86, unaligned accesses are fast
[    0.265051] cpu62: Ratio of byte access time to unaligned word access is 2.81, unaligned accesses are fast
[    0.265051] cpu61: Ratio of byte access time to unaligned word access is 2.86, unaligned accesses are fast
[    0.265051] cpu60: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
[    0.265055] cpu5: Ratio of byte access time to unaligned word access is 3.98, unaligned accesses are fast
[    0.265054] cpu47: Ratio of byte access time to unaligned word access is 3.01, unaligned accesses are fast
[    0.265054] cpu45: Ratio of byte access time to unaligned word access is 3.00, unaligned accesses are fast
[    0.265055] cpu36: Ratio of byte access time to unaligned word access is 3.14, unaligned accesses are fast
[    0.265051] cpu11: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
[    0.265051] cpu24: Ratio of byte access time to unaligned word access is 3.30, unaligned accesses are fast
[    0.265054] cpu44: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
[    0.265054] cpu46: Ratio of byte access time to unaligned word access is 2.95, unaligned accesses are fast
[    0.265052] cpu25: Ratio of byte access time to unaligned word access is 3.38, unaligned accesses are fast
[    0.265055] cpu2: Ratio of byte access time to unaligned word access is 2.88, unaligned accesses are fast
[    0.265055] cpu3: Ratio of byte access time to unaligned word access is 2.82, unaligned accesses are fast
[    0.265054] cpu35: Ratio of byte access time to unaligned word access is 3.19, unaligned accesses are fast
[    0.265051] cpu10: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
[    0.265054] cpu32: Ratio of byte access time to unaligned word access is 3.26, unaligned accesses are fast
[    0.265056] cpu29: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
[    0.265053] cpu56: Ratio of byte access time to unaligned word access is 3.07, unaligned accesses are fast
[    0.265053] cpu58: Ratio of byte access time to unaligned word access is 2.98, unaligned accesses are fast
[    0.265055] cpu37: Ratio of byte access time to unaligned word access is 4.56, unaligned accesses are fast
[    0.265055] cpu4: Ratio of byte access time to unaligned word access is 2.82, unaligned accesses are fast
[    0.265052] cpu48: Ratio of byte access time to unaligned word access is 3.11, unaligned accesses are fast
[    0.265055] cpu1: Ratio of byte access time to unaligned word access is 2.80, unaligned accesses are fast
[    0.265056] cpu7: Ratio of byte access time to unaligned word access is 3.91, unaligned accesses are fast
[    0.265056] cpu6: Ratio of byte access time to unaligned word access is 4.02, unaligned accesses are fast
[    0.265055] cpu21: Ratio of byte access time to unaligned word access is 3.07, unaligned accesses are fast
[    0.265054] cpu13: Ratio of byte access time to unaligned word access is 3.75, unaligned accesses are fast
[    0.265053] cpu53: Ratio of byte access time to unaligned word access is 2.91, unaligned accesses are fast
[    0.265056] cpu30: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
[    0.265052] cpu17: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
[    0.265053] cpu40: Ratio of byte access time to unaligned word access is 3.14, unaligned accesses are fast
[    0.265054] cpu43: Ratio of byte access time to unaligned word access is 3.26, unaligned accesses are fast
[    0.265053] cpu42: Ratio of byte access time to unaligned word access is 3.23, unaligned accesses are fast
[    0.265053] cpu41: Ratio of byte access time to unaligned word access is 3.22, unaligned accesses are fast
[    0.265054] cpu14: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
[    0.265051] cpu9: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
[    0.265052] cpu27: Ratio of byte access time to unaligned word access is 3.42, unaligned accesses are fast
[    0.265054] cpu34: Ratio of byte access time to unaligned word access is 3.38, unaligned accesses are fast
[    0.265054] cpu33: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
[    0.265053] cpu54: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
[    0.265051] cpu8: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
[    0.265056] cpu31: Ratio of byte access time to unaligned word access is 3.04, unaligned accesses are fast
[    0.265055] cpu39: Ratio of byte access time to unaligned word access is 3.22, unaligned accesses are fast
[    0.265055] cpu38: Ratio of byte access time to unaligned word access is 3.60, unaligned accesses are fast
[    0.265055] cpu22: Ratio of byte access time to unaligned word access is 3.13, unaligned accesses are fast
[    0.265054] cpu15: Ratio of byte access time to unaligned word access is 2.88, unaligned accesses are fast
[    0.265052] cpu49: Ratio of byte access time to unaligned word access is 2.83, unaligned accesses are fast
[    0.265055] cpu20: Ratio of byte access time to unaligned word access is 3.18, unaligned accesses are fast
[    0.265053] cpu52: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
[    0.265053] cpu55: Ratio of byte access time to unaligned word access is 2.92, unaligned accesses are fast
[    0.265052] cpu16: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
[    0.265052] cpu26: Ratio of byte access time to unaligned word access is 3.18, unaligned accesses are fast
[    0.265052] cpu51: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
[    0.265055] cpu23: Ratio of byte access time to unaligned word access is 3.07, unaligned accesses are fast
[    0.265054] cpu12: Ratio of byte access time to unaligned word access is 3.32, unaligned accesses are fast
[    0.265054] cpu19: Ratio of byte access time to unaligned word access is 2.98, unaligned accesses are fast
[    0.265052] cpu50: Ratio of byte access time to unaligned word access is 2.80, unaligned accesses are fast
[    0.265053] cpu59: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
[    0.265053] cpu57: Ratio of byte access time to unaligned word access is 3.06, unaligned accesses are fast
[    0.265056] cpu28: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
[    0.265054] cpu18: Ratio of byte access time to unaligned word access is 3.00, unaligned accesses are fast
[    0.289100] cpu0: Ratio of byte access time to unaligned word access is 5.97, unaligned accesses are fast
[    0.290415] Serial: LRW UART driver
[    0.290665] sse: Missing SBI SSE extension
[    0.311076] sophgo,top-intc 70300102e0.top_intc: is a msi parent
[    0.327406] HugeTLB: registered 1.00 GiB page size, pre-allocated 0 pages
[    0.327430] HugeTLB: 0 KiB vmemmap can be freed for a 1.00 GiB page
[    0.327444] HugeTLB: registered 2.00 MiB page size, pre-allocated 0 pages
[    0.327455] HugeTLB: 0 KiB vmemmap can be freed for a 2.00 MiB page
[    0.332494] ACPI: Interpreter disabled.
[    0.333142] iommu: Default domain type: Translated
[    0.333161] iommu: DMA domain TLB invalidation policy: strict mode
[    0.333759] pps_core: LinuxPPS API ver. 1 registered
[    0.333779] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.333804] PTP clock support registered
[    0.334314] efivars: Registered efivars operations
[    0.335699] NetLabel: Initializing
[    0.335723] NetLabel:  domain hash size = 128
[    0.335734] NetLabel:  protocols = UNLABELED CIPSOv4 CALIPSO
[    0.335804] NetLabel:  unlabeled traffic allowed by default
[    0.336150] vgaarb: loaded
[    0.337190] clocksource: Switched to clocksource riscv_clocksource
[    0.343385] VFS: Disk quotas dquot_6.6.0
[    0.343633] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.346650] AppArmor: AppArmor Filesystem Enabled
[    0.346810] pnp: PnP ACPI: disabled
[    0.358401] NET: Registered PF_INET protocol family
[    0.359469] IP idents hash table entries: 262144 (order: 9, 2097152 bytes, vmalloc)
[    0.373312] tcp_listen_portaddr_hash hash table entries: 65536 (order: 8, 1048576 bytes, vmalloc)
[    0.373987] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, vmalloc)
[    0.375584] TCP established hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)
[    0.377485] TCP bind hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
[    0.378590] TCP: Hash tables configured (established 524288 bind 65536)
[    0.380288] MPTCP token hash table entries: 65536 (order: 9, 1572864 bytes, vmalloc)
[    0.382060] UDP hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
[    0.383229] UDP-Lite hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
[    0.384259] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.384308] NET: Registered PF_XDP protocol family
[    0.384333] PCI: CLS 0 bytes, default 64
[    0.385763] Trying to unpack rootfs image as initramfs...
[    0.389153] Initialise system trusted keyrings
[    0.389318] Key type blacklist registered
[    0.390041] workingset: timestamp_bits=43 max_order=25 bucket_order=0
[    0.390114] zbud: loaded
[    0.396835] fuse: init (API version 7.39)
[    0.399678] integrity: Platform Keyring initialized
[    0.399734] integrity: Machine keyring initialized
[    0.399766] Key type asymmetric registered
[    0.399779] Asymmetric key parser 'x509' registered
[    3.296324] Freeing initrd memory: 117684K
[    3.378869] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 246)
[    3.379281] io scheduler mq-deadline registered
[    3.391286] pwm_sophgo_probe
[    3.391850] cdns-pcie-host 7060000000.pcie: host bridge /pcie@7060000000 ranges:
[    3.391899] cdns-pcie-host 7060000000.pcie:       IO 0x40c0000000..0x40c03fffff -> 0x00c0000000
[    3.391933] cdns-pcie-host 7060000000.pcie:      MEM 0x40d0000000..0x40dfffffff -> 0x00d0000000
[    3.391960] cdns-pcie-host 7060000000.pcie:      MEM 0x40e0000000..0x40ffffffff -> 0x00e0000000
[    3.391982] cdns-pcie-host 7060000000.pcie:      MEM 0x4200000000..0x43ffffffff -> 0x4200000000
[    3.392002] cdns-pcie-host 7060000000.pcie:      MEM 0x4100000000..0x41ffffffff -> 0x4100000000
[    3.392031] cdns-pcie-host 7060000000.pcie: Memory resource size exceeds max for 32 bits
[    3.392084] cdns-pcie-host 7060000000.pcie: no phy-names.  PHY will not be initialized
[    3.392458] cdns-pcie-host 7060000000.pcie: PCI host bridge to bus 0000:00
[    3.392480] pci_bus 0000:00: Unknown NUMA node; performance will be reduced
[    3.392495] pci_bus 0000:00: root bus resource [bus 00-3f]
[    3.392513] pci_bus 0000:00: root bus resource [io  0x0000-0x3fffff] (bus address [0xc0000000-0xc03fffff])
[    3.392531] pci_bus 0000:00: root bus resource [mem 0x40d0000000-0x40dfffffff pref] (bus address [0xd0000000-0xdfffffff])
[    3.392548] pci_bus 0000:00: root bus resource [mem 0x40e0000000-0x40ffffffff] (bus address [0xe0000000-0xffffffff])
[    3.392562] pci_bus 0000:00: root bus resource [mem 0x4200000000-0x43ffffffff pref]
[    3.392576] pci_bus 0000:00: root bus resource [mem 0x4100000000-0x41ffffffff]
[    3.392619] pci 0000:00:00.0: [1e30:2042] type 01 class 0x060400
[    3.392728] pci 0000:00:00.0: supports D1
[    3.392744] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    3.395695] pci 0000:01:00.0: [1002:6611] type 00 class 0x030000
[    3.395758] pci 0000:01:00.0: reg 0x10: [mem 0xc0000000-0xcfffffff 64bit pref]
[    3.395797] pci 0000:01:00.0: reg 0x18: [mem 0x40d0000000-0x40d003ffff 64bit]
[    3.395824] pci 0000:01:00.0: reg 0x20: initial BAR value 0x00000000 invalid
[    3.395837] pci 0000:01:00.0: reg 0x20: [io  size 0x0100]
[    3.395876] pci 0000:01:00.0: reg 0x30: [mem 0x40fffe0000-0x40ffffffff pref]
[    3.395899] pci 0000:01:00.0: enabling Extended Tags
[    3.396031] pci 0000:01:00.0: supports D1 D2
[    3.396044] pci 0000:01:00.0: PME# supported from D1 D2 D3hot
[    3.396430] pci 0000:01:00.0: vgaarb: setting as boot VGA device
[    3.396446] pci 0000:01:00.0: vgaarb: bridge control possible
[    3.396458] pci 0000:01:00.0: vgaarb: VGA device added: decodes=io+mem,owns=none,locks=none
[    3.396525] pci 0000:01:00.1: [1002:aab0] type 00 class 0x040300
[    3.396568] pci 0000:01:00.1: reg 0x10: [mem 0x40d0040000-0x40d0043fff 64bit]
[    3.396637] pci 0000:01:00.1: enabling Extended Tags
[    3.396744] pci 0000:01:00.1: supports D1 D2
[    3.405287] pci_bus 0000:01: busn_res: [bus 01-3f] end is updated to 01
[    3.405334] pci 0000:00:00.0: BAR 15: assigned [mem 0x4200000000-0x420fffffff 64bit pref]
[    3.405354] pci 0000:00:00.0: BAR 14: assigned [mem 0x40e0000000-0x40e00fffff]
[    3.405369] pci 0000:00:00.0: BAR 13: assigned [io  0x1000-0x1fff]
[    3.405389] pci 0000:01:00.0: BAR 0: assigned [mem 0x4200000000-0x420fffffff 64bit pref]
[    3.405420] pci 0000:01:00.0: BAR 2: assigned [mem 0x40e0000000-0x40e003ffff 64bit]
[    3.405449] pci 0000:01:00.0: BAR 6: assigned [mem 0x40e0040000-0x40e005ffff pref]
[    3.405463] pci 0000:01:00.1: BAR 0: assigned [mem 0x40e0060000-0x40e0063fff 64bit]
[    3.405490] pci 0000:01:00.0: BAR 4: assigned [io  0x1000-0x10ff]
[    3.405509] pci 0000:00:00.0: PCI bridge to [bus 01]
[    3.405521] pci 0000:00:00.0:   bridge window [io  0x1000-0x1fff]
[    3.405535] pci 0000:00:00.0:   bridge window [mem 0x40e0000000-0x40e00fffff]
[    3.405549] pci 0000:00:00.0:   bridge window [mem 0x4200000000-0x420fffffff 64bit pref]
[    3.405980] pcieport 0000:00:00.0: PME: Signaling with IRQ 45
[    3.406441] pcieport 0000:00:00.0: AER: enabled with IRQ 45
[    3.406727] pci 0000:01:00.1: D0 power state depends on 0000:01:00.0
[    3.406972] cdns-pcie-host 7062000000.pcie: host bridge /pcie@7062000000 ranges:
[    3.407016] cdns-pcie-host 7062000000.pcie:       IO 0x48c0800000..0x48c0bfffff -> 0x00c0800000
[    3.407047] cdns-pcie-host 7062000000.pcie:      MEM 0x48d0000000..0x48dfffffff -> 0x00d0000000
[    3.407071] cdns-pcie-host 7062000000.pcie:      MEM 0x48e0000000..0x48ffffffff -> 0x00e0000000
[    3.407094] cdns-pcie-host 7062000000.pcie:      MEM 0x4900000000..0x49ffffffff -> 0x4900000000
[    3.407112] cdns-pcie-host 7062000000.pcie:      MEM 0x4a00000000..0x4bffffffff -> 0x4a00000000
[    3.407163] cdns-pcie-host 7062000000.pcie: Memory resource size exceeds max for 32 bits
[    3.407217] cdns-pcie-host 7062000000.pcie: no phy-names.  PHY will not be initialized
[    3.407292] cdns-pcie-host 7062000000.pcie: msi_data is 0xaf000000
[    3.407605] cdns-pcie-host 7062000000.pcie: PCI host bridge to bus 0001:80
[    3.407624] pci_bus 0001:80: Unknown NUMA node; performance will be reduced
[    3.407638] pci_bus 0001:80: root bus resource [bus 80-bf]
[    3.407653] pci_bus 0001:80: root bus resource [io  0x400000-0x7fffff] (bus address [0xc0800000-0xc0bfffff])
[    3.407670] pci_bus 0001:80: root bus resource [mem 0x48d0000000-0x48dfffffff pref] (bus address [0xd0000000-0xdfffffff])
[    3.407687] pci_bus 0001:80: root bus resource [mem 0x48e0000000-0x48ffffffff] (bus address [0xe0000000-0xffffffff])
[    3.407702] pci_bus 0001:80: root bus resource [mem 0x4900000000-0x49ffffffff]
[    3.407715] pci_bus 0001:80: root bus resource [mem 0x4a00000000-0x4bffffffff pref]
[    3.407751] pci 0001:80:00.0: [1e30:2042] type 01 class 0x060400
[    3.407849] pci 0001:80:00.0: supports D1
[    3.407863] pci 0001:80:00.0: PME# supported from D0 D1 D3hot
[    3.410185] pci_bus 0001:81: busn_res: [bus 81-bf] end is updated to 81
[    3.410219] pci 0001:80:00.0: PCI bridge to [bus 81]
[    3.410439] cdns-pcie-host 7062000000.pcie: msi#0 address_hi 0x0 address_lo 0xaf000000
[    3.410588] pcieport 0001:80:00.0: PME: Signaling with IRQ 47
[    3.411013] pcieport 0001:80:00.0: AER: enabled with IRQ 47
[    3.411311] cdns-pcie-host 4c00000000.pcie: host bridge /pcie@7062800000 ranges:
[    3.411355] cdns-pcie-host 4c00000000.pcie:       IO 0x4cc0c00000..0x4cc0ffffff -> 0x00c0c00000
[    3.411386] cdns-pcie-host 4c00000000.pcie:      MEM 0x4cf8000000..0x4cfbffffff -> 0x00f8000000
[    3.411411] cdns-pcie-host 4c00000000.pcie:      MEM 0x4cfc000000..0x4cffffffff -> 0x00fc000000
[    3.411451] cdns-pcie-host 4c00000000.pcie:      MEM 0x4e00000000..0x4fffffffff -> 0x4e00000000
[    3.411472] cdns-pcie-host 4c00000000.pcie:      MEM 0x4d00000000..0x4dffffffff -> 0x4d00000000
[    3.411502] cdns-pcie-host 4c00000000.pcie: Memory resource size exceeds max for 32 bits
[    3.411540] cdns-pcie-host 4c00000000.pcie: no phy-names.  PHY will not be initialized
[    3.411711] cdns-pcie-host 4c00000000.pcie: PCI host bridge to bus 0002:c0
[    3.411727] pci_bus 0002:c0: Unknown NUMA node; performance will be reduced
[    3.411742] pci_bus 0002:c0: root bus resource [bus c0-ff]
[    3.411756] pci_bus 0002:c0: root bus resource [io  0x800000-0xbfffff] (bus address [0xc0c00000-0xc0ffffff])
[    3.411772] pci_bus 0002:c0: root bus resource [mem 0x4cf8000000-0x4cfbffffff pref] (bus address [0xf8000000-0xfbffffff])
[    3.411788] pci_bus 0002:c0: root bus resource [mem 0x4cfc000000-0x4cffffffff] (bus address [0xfc000000-0xffffffff])
[    3.411803] pci_bus 0002:c0: root bus resource [mem 0x4e00000000-0x4fffffffff pref]
[    3.411816] pci_bus 0002:c0: root bus resource [mem 0x4d00000000-0x4dffffffff]
[    3.411850] pci 0002:c0:00.0: [1e30:2042] type 01 class 0x060400
[    3.411945] pci 0002:c0:00.0: supports D1
[    3.411958] pci 0002:c0:00.0: PME# supported from D0 D1 D3hot
[    3.414269] pci 0002:c1:00.0: [1b21:2824] type 01 class 0x060400
[    3.414382] pci 0002:c1:00.0: enabling Extended Tags
[    3.414540] pci 0002:c1:00.0: PME# supported from D0 D3hot D3cold
[    3.425436] pci 0002:c2:00.0: [1b21:2824] type 01 class 0x060400
[    3.425551] pci 0002:c2:00.0: enabling Extended Tags
[    3.425713] pci 0002:c2:00.0: PME# supported from D0 D3hot D3cold
[    3.426443] pci 0002:c2:04.0: [1b21:2824] type 01 class 0x060400
[    3.426557] pci 0002:c2:04.0: enabling Extended Tags
[    3.426717] pci 0002:c2:04.0: PME# supported from D0 D3hot D3cold
[    3.427216] pci 0002:c2:06.0: [1b21:2824] type 01 class 0x060400
[    3.427325] pci 0002:c2:06.0: enabling Extended Tags
[    3.427483] pci 0002:c2:06.0: PME# supported from D0 D3hot D3cold
[    3.427911] pci 0002:c2:07.0: [1b21:2824] type 01 class 0x060400
[    3.428019] pci 0002:c2:07.0: enabling Extended Tags
[    3.428176] pci 0002:c2:07.0: PME# supported from D0 D3hot D3cold
[    3.428579] pci 0002:c2:08.0: [1b21:2824] type 01 class 0x060400
[    3.428685] pci 0002:c2:08.0: enabling Extended Tags
[    3.428841] pci 0002:c2:08.0: PME# supported from D0 D3hot D3cold
[    3.429563] pci 0002:c2:0c.0: [1b21:2824] type 01 class 0x060400
[    3.429676] pci 0002:c2:0c.0: enabling Extended Tags
[    3.429837] pci 0002:c2:0c.0: PME# supported from D0 D3hot D3cold
[    3.430365] pci 0002:c2:0e.0: [1b21:2824] type 01 class 0x060400
[    3.430475] pci 0002:c2:0e.0: enabling Extended Tags
[    3.430634] pci 0002:c2:0e.0: PME# supported from D0 D3hot D3cold
[    3.431059] pci 0002:c2:0f.0: [1b21:2824] type 01 class 0x060400
[    3.431165] pci 0002:c2:0f.0: enabling Extended Tags
[    3.431322] pci 0002:c2:0f.0: PME# supported from D0 D3hot D3cold
[    3.432977] pci_bus 0002:c3: busn_res: [bus c3-ff] end is updated to c3
[    3.433313] pci 0002:c4:00.0: [1b21:2142] type 00 class 0x0c0330
[    3.433374] pci 0002:c4:00.0: reg 0x10: [mem 0xc0500000-0xc0507fff 64bit]
[    3.433470] pci 0002:c4:00.0: enabling Extended Tags
[    3.433648] pci 0002:c4:00.0: PME# supported from D0 D3hot D3cold
[    3.445242] pci_bus 0002:c4: busn_res: [bus c4-ff] end is updated to c4
[    3.445447] pci 0002:c5:00.0: [10ec:8125] type 00 class 0x020000
[    3.445493] pci 0002:c5:00.0: reg 0x10: [io  0xc02000-0xc020ff]
[    3.445544] pci 0002:c5:00.0: reg 0x18: [mem 0xc0400000-0xc040ffff 64bit]
[    3.445581] pci 0002:c5:00.0: reg 0x20: [mem 0xc0410000-0xc0413fff 64bit]
[    3.445820] pci 0002:c5:00.0: supports D1 D2
[    3.445833] pci 0002:c5:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[    3.457248] pci_bus 0002:c5: busn_res: [bus c5-ff] end is updated to c5
[    3.457460] pci 0002:c6:00.0: [1106:3483] type 00 class 0x0c0330
[    3.457514] pci 0002:c6:00.0: reg 0x10: [mem 0xc0300000-0xc0300fff 64bit]
[    3.457697] pci 0002:c6:00.0: PME# supported from D0 D3hot D3cold
[    3.458042] pci_bus 0002:c6: busn_res: [bus c6-ff] end is updated to c6
[    3.458236] pci 0002:c7:00.0: [1bb1:5027] type 00 class 0x010802
[    3.458314] pci 0002:c7:00.0: reg 0x10: [mem 0xc0200000-0xc0203fff 64bit]
[    3.459034] pci 0002:c7:00.0: 31.504 Gb/s available PCIe bandwidth, limited by 8.0 GT/s PCIe x4 link at 0002:c2:08.0 (capable of 63.012 Gb/s with 16.0 GT/s PCIe x4 link)
[    3.469236] pci_bus 0002:c7: busn_res: [bus c7-ff] end is updated to c7
[    3.469427] pci 0002:c8:00.0: [197b:0585] type 00 class 0x010601
[    3.469477] pci 0002:c8:00.0: reg 0x10: [io  0xc01200-0xc0127f]
[    3.469508] pci 0002:c8:00.0: reg 0x14: [io  0xc01180-0xc011ff]
[    3.469538] pci 0002:c8:00.0: reg 0x18: [io  0xc01100-0xc0117f]
[    3.469568] pci 0002:c8:00.0: reg 0x1c: [io  0xc01080-0xc010ff]
[    3.469597] pci 0002:c8:00.0: reg 0x20: [io  0xc01000-0xc0107f]
[    3.469626] pci 0002:c8:00.0: reg 0x24: [mem 0xc0100000-0xc0101fff]
[    3.469656] pci 0002:c8:00.0: reg 0x30: [mem 0x4cffff0000-0x4cffffffff pref]
[    3.469837] pci 0002:c8:00.0: PME# supported from D3hot
[    3.470310] pci_bus 0002:c8: busn_res: [bus c8-ff] end is updated to c8
[    3.470513] pci 0002:c9:00.0: [10ec:8125] type 00 class 0x020000
[    3.470558] pci 0002:c9:00.0: reg 0x10: [io  0xc00000-0xc000ff]
[    3.470609] pci 0002:c9:00.0: reg 0x18: [mem 0xc0000000-0xc000ffff 64bit]
[    3.470646] pci 0002:c9:00.0: reg 0x20: [mem 0xc0010000-0xc0013fff 64bit]
[    3.470881] pci 0002:c9:00.0: supports D1 D2
[    3.470893] pci 0002:c9:00.0: PME# supported from D0 D1 D2 D3hot D3cold
[    3.481236] pci_bus 0002:c9: busn_res: [bus c9-ff] end is updated to c9
[    3.481585] pci_bus 0002:ca: busn_res: [bus ca-ff] end is updated to ca
[    3.481612] pci_bus 0002:c2: busn_res: [bus c2-ff] end is updated to ca
[    3.481631] pci_bus 0002:c1: busn_res: [bus c1-ff] end is updated to ca
[    3.481676] pci 0002:c0:00.0: BAR 14: assigned [mem 0x4cfc000000-0x4cfc5fffff]
[    3.481694] pci 0002:c0:00.0: BAR 13: assigned [io  0x800000-0x802fff]
[    3.481712] pci 0002:c1:00.0: BAR 14: assigned [mem 0x4cfc000000-0x4cfc5fffff]
[    3.481726] pci 0002:c1:00.0: BAR 13: assigned [io  0x800000-0x802fff]
[    3.481746] pci 0002:c2:04.0: BAR 14: assigned [mem 0x4cfc000000-0x4cfc0fffff]
[    3.481761] pci 0002:c2:06.0: BAR 14: assigned [mem 0x4cfc100000-0x4cfc1fffff]
[    3.481775] pci 0002:c2:07.0: BAR 14: assigned [mem 0x4cfc200000-0x4cfc2fffff]
[    3.481789] pci 0002:c2:08.0: BAR 14: assigned [mem 0x4cfc300000-0x4cfc3fffff]
[    3.481802] pci 0002:c2:0c.0: BAR 14: assigned [mem 0x4cfc400000-0x4cfc4fffff]
[    3.481816] pci 0002:c2:0e.0: BAR 14: assigned [mem 0x4cfc500000-0x4cfc5fffff]
[    3.481829] pci 0002:c2:06.0: BAR 13: assigned [io  0x800000-0x800fff]
[    3.481842] pci 0002:c2:0c.0: BAR 13: assigned [io  0x801000-0x801fff]
[    3.481854] pci 0002:c2:0e.0: BAR 13: assigned [io  0x802000-0x802fff]
[    3.481868] pci 0002:c2:00.0: PCI bridge to [bus c3]
[    3.481902] pci 0002:c4:00.0: BAR 0: assigned [mem 0x4cfc000000-0x4cfc007fff 64bit]
[    3.481937] pci 0002:c2:04.0: PCI bridge to [bus c4]
[    3.481954] pci 0002:c2:04.0:   bridge window [mem 0x4cfc000000-0x4cfc0fffff]
[    3.481982] pci 0002:c5:00.0: BAR 2: assigned [mem 0x4cfc100000-0x4cfc10ffff 64bit]
[    3.482017] pci 0002:c5:00.0: BAR 4: assigned [mem 0x4cfc110000-0x4cfc113fff 64bit]
[    3.482050] pci 0002:c5:00.0: BAR 0: assigned [io  0x800000-0x8000ff]
[    3.482069] pci 0002:c2:06.0: PCI bridge to [bus c5]
[    3.482082] pci 0002:c2:06.0:   bridge window [io  0x800000-0x800fff]
[    3.482099] pci 0002:c2:06.0:   bridge window [mem 0x4cfc100000-0x4cfc1fffff]
[    3.482125] pci 0002:c6:00.0: BAR 0: assigned [mem 0x4cfc200000-0x4cfc200fff 64bit]
[    3.482158] pci 0002:c2:07.0: PCI bridge to [bus c6]
[    3.482174] pci 0002:c2:07.0:   bridge window [mem 0x4cfc200000-0x4cfc2fffff]
[    3.482200] pci 0002:c7:00.0: BAR 0: assigned [mem 0x4cfc300000-0x4cfc303fff 64bit]
[    3.482240] pci 0002:c2:08.0: PCI bridge to [bus c7]
[    3.482257] pci 0002:c2:08.0:   bridge window [mem 0x4cfc300000-0x4cfc3fffff]
[    3.482284] pci 0002:c8:00.0: BAR 6: assigned [mem 0x4cfc400000-0x4cfc40ffff pref]
[    3.482299] pci 0002:c8:00.0: BAR 5: assigned [mem 0x4cfc410000-0x4cfc411fff]
[    3.482317] pci 0002:c8:00.0: BAR 0: assigned [io  0x801000-0x80107f]
[    3.482334] pci 0002:c8:00.0: BAR 1: assigned [io  0x801080-0x8010ff]
[    3.482351] pci 0002:c8:00.0: BAR 2: assigned [io  0x801100-0x80117f]
[    3.482368] pci 0002:c8:00.0: BAR 3: assigned [io  0x801180-0x8011ff]
[    3.482385] pci 0002:c8:00.0: BAR 4: assigned [io  0x801200-0x80127f]
[    3.482403] pci 0002:c2:0c.0: PCI bridge to [bus c8]
[    3.482416] pci 0002:c2:0c.0:   bridge window [io  0x801000-0x801fff]
[    3.482433] pci 0002:c2:0c.0:   bridge window [mem 0x4cfc400000-0x4cfc4fffff]
[    3.482459] pci 0002:c9:00.0: BAR 2: assigned [mem 0x4cfc500000-0x4cfc50ffff 64bit]
[    3.482492] pci 0002:c9:00.0: BAR 4: assigned [mem 0x4cfc510000-0x4cfc513fff 64bit]
[    3.482525] pci 0002:c9:00.0: BAR 0: assigned [io  0x802000-0x8020ff]
[    3.482543] pci 0002:c2:0e.0: PCI bridge to [bus c9]
[    3.482556] pci 0002:c2:0e.0:   bridge window [io  0x802000-0x802fff]
[    3.482573] pci 0002:c2:0e.0:   bridge window [mem 0x4cfc500000-0x4cfc5fffff]
[    3.482597] pci 0002:c2:0f.0: PCI bridge to [bus ca]
[    3.482626] pci 0002:c1:00.0: PCI bridge to [bus c2-ca]
[    3.482638] pci 0002:c1:00.0:   bridge window [io  0x800000-0x802fff]
[    3.482656] pci 0002:c1:00.0:   bridge window [mem 0x4cfc000000-0x4cfc5fffff]
[    3.482680] pci 0002:c0:00.0: PCI bridge to [bus c1-ca]
[    3.482691] pci 0002:c0:00.0:   bridge window [io  0x800000-0x802fff]
[    3.482704] pci 0002:c0:00.0:   bridge window [mem 0x4cfc000000-0x4cfc5fffff]
[    3.483107] pcieport 0002:c0:00.0: PME: Signaling with IRQ 48
[    3.483596] pcieport 0002:c0:00.0: AER: enabled with IRQ 48
[    3.487131] pci 0002:c4:00.0: PME# does not work under D0, disabling it
[    3.487164] pci 0002:c4:00.0: enabling device (0000 -> 0002)
[    3.487259] pci 0002:c6:00.0: enabling device (0000 -> 0002)
[    3.488568] EINJ: ACPI disabled.
[    3.488589] ERST DBG: ERST support is disabled.
[    3.492343] no vdmabuf_reserved_memory node
[    3.492365] virtio-vdmabuf: carveout buf not setup -22
[    3.493828] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    3.496550] printk: console [ttyS0] disabled
[    3.496941] 7040000000.serial: ttyS0 at MMIO 0x7040000000 (irq = 57, base_baud = 31250000) is a 16550A
[    3.497008] printk: console [ttyS0] enabled
[    6.653616] 7040001000.serial: ttyS1 at MMIO 0x7040001000 (irq = 58, base_baud = 31250000) is a 16550A
[    6.664291] 7040002000.serial: ttyS2 at MMIO 0x7040002000 (irq = 59, base_baud = 31250000) is a 16550A
[    6.674993] 7040003000.serial: ttyS3 at MMIO 0x7040003000 (irq = 60, base_baud = 31250000) is a 16550A
[    6.691432] nvme nvme0: pci function 0002:c7:00.0
[    6.693487] mousedev: PS/2 mouse device common for all mice
[    6.703782] sdhci: Secure Digital Host Controller Interface driver
[    6.710021] sdhci: Copyright(c) Pierre Ossman
[    6.711847] hwmon hwmon0: temp1_input not attached to any thermal zone
[    6.714740] sdhci-pltfm: SDHCI platform and OF driver helper
[    6.721065] hwmon hwmon0: temp2_input not attached to any thermal zone
[    6.737204] ledtrig-cpu: registered to indicate activity on CPUs
[    6.743578] pstore: Using crash dump compression: deflate
[    6.749064] pstore: Registered efi_pstore as persistent store backend
[    6.756324] riscv-pmu-sbi: SBI PMU extension is available
[    6.761974] riscv-pmu-sbi: 16 firmware and 31 hardware counters
[    6.774971] NET: Registered PF_INET6 protocol family
[    6.775258] nvme nvme0: allocated 64 MiB host memory buffer.
[    6.792744] nvme nvme0: 1/0/0 default/read/poll queues
[    6.798818] Segment Routing with IPv6
[    6.802615] In-situ OAM (IOAM) with IPv6
[    6.806651] mip6: Mobile IPv6
[    6.809657] NET: Registered PF_PACKET protocol family
[    6.814951] mpls_gso: MPLS GSO support
[    6.826385] registered taskstats version 1
[    6.828554]  nvme0n1: p1 p2 p3
[    6.832483] Loading compiled-in X.509 certificates
[    6.881423] Loaded X.509 cert 'Build time autogenerated kernel key: a949a38ba7402beaa827889ff304b05fc9df7c05'
[    6.910444] Key type .fscrypt registered
[    6.914452] Key type fscrypt-provisioning registered
[    6.931636] Key type encrypted registered
[    6.935707] AppArmor: AppArmor sha1 policy hashing enabled
[    6.941498] ima: No TPM chip found, activating TPM-bypass!
[    6.947038] ima: Allocated hash algorithm: sha256
[    6.951806] ima: No architecture policies found
[    6.956459] evm: Initialising EVM extended attributes:
[    6.961618] evm: security.selinux
[    6.964937] evm: security.SMACK64 (disabled)
[    6.969217] evm: security.SMACK64EXEC (disabled)
[    6.973848] evm: security.SMACK64TRANSMUTE (disabled)
[    6.978909] evm: security.SMACK64MMAP (disabled)
[    6.983536] evm: security.apparmor
[    6.986948] evm: security.ima
[    6.989927] evm: security.capability
[    6.993513] evm: HMAC attrs: 0x1
[    7.247426] clk: Disabling unused clocks
[    7.256860] Freeing unused kernel image (initmem) memory: 2712K
[   10.882016] r8169 0002:c9:00.0 eth1: RTL8125B, 00:e0:4c:68:02:e6, XID 641, IRQ 68
1;-1f[   10.882032] r8169 0002:c9:00.0 eth1: jumbo features [frames: 9194 bytes, tx checksumming: ko]
[   10.889827] xhci_hcd 0002:c4:00.0: xHCI Host Controller
[   10.891369] r8169 0002:c5:00.0 enP2p197s0: renamed from eth0
[   10.896488] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   10.904233] xhci_hcd 0002:c4:00.0: new USB bus registered, assigned bus number 2
[   10.904253] xhci_hcd 0002:c4:00.0: Host supports USB 3.1 Enhanced SuperSpeed
[   10.905580] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   10.913690] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.06
[   10.962246] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[   10.962253] usb usb1: Product: xHCI Host Controller
[   10.962257] usb usb1: Manufacturer: Linux 6.6.127+ xhci-hcd
[   10.962261] usb usb1: SerialNumber: 0002:c4:00.0
[   10.962987] hub 1-0:1.0: USB hub found
[   10.988466] hub 1-0:1.0: 2 ports detected
[   10.989373] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   10.991053] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[   10.991187] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.06
[   10.991197] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[   10.991204] usb usb2: Product: xHCI Host Controller
[   10.991208] usb usb2: Manufacturer: Linux 6.6.127+ xhci-hcd
[   10.991212] usb usb2: SerialNumber: 0002:c4:00.0
[   10.991915] hub 2-0:1.0: USB hub found
[   10.991958] hub 2-0:1.0: 2 ports detected
[   10.992696] xhci_hcd 0002:c6:00.0: xHCI Host Controller
[   11.001456] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   11.008198] xhci_hcd 0002:c6:00.0: new USB bus registered, assigned bus number 3
[   11.016938] gpio-keys soc:gpio-restart: there is not valid maps for state default
[  OK  ] Finished dracut initqueue hook.
[  OK  ] Found device Seagate ZP2048CM30003 oERV.
[  OK  ] Reached target Initrd Root Device.
[  OK  ] Reached target Preparation for Remote File Systems.
[  OK  ] Reached target Remote File Systems.
         Starting dracut pre-mount hook...
[  OK  ] Started Show Plymouth Boot Screen.
[  OK  ] Started Forward Password Requests to Plymouth Directory Watch.
[  OK  ] Reached target Path Units.
[  OK  ] Reached target Basic System.
[  OK  ] Stopped Virtual Console Setup.
         Stopping Virtual Console Setup...
         Starting Virtual Console Setup...
[  OK  ] Finished dracut pre-mount hook.
         Starting File System Check on /dev/nvme0n1p3...
[   11.245223] usb 1-1: new high-speed USB device number 2 using xhci_hcd
[  OK  ] Finished File System Check on /dev/nvme0n1p3.
         Mounting /sysroot...
[   11.385246] EXT4-fs (nvme0n1p3): mounted filesystem 07617bd8-13da-4749-97a3-2b548687b739 ro with ordered data mode. Quota mode: none.
[   11.400683] usb 1-1: New USB device found, idVendor=2109, idProduct=2822, bcdDevice= 7.94
[   11.408909] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   11.408916] usb 1-1: Product: USB2.0 Hub             
[  OK  ] Mounted    11.408921] usb 1-1: Manufacturer: VIA Labs, Inc.         
1;39m/sysroot.
[   11.408925] usb 1-1: SerialNumber: 000000001
[   11.414710] hub 1-1:1.0: USB hub found
[   11.439385] hub 1-1:1.0: 4 ports detected
[  OK  ] Reached target Initrd Root File System.
         Starting Mountpoints Configured in the Real Root...
[  OK  ] Finished Mountpoints Configured in the Real Root.
[  OK  ] Reached target    11.542161] usb 2-1: new SuperSpeed USB device number 2 using xhci_hcd
mInitrd File Systems.
[  OK  ] Reached target Initrd Default Target.
         Starting dracut pre-pivot and cleanup hook...
[   11.573510] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   11.581589] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   11.674720] scsi host0: ahci
[   11.678766] xhci_hcd 0002:c6:00.0: hcc params 0x002841eb hci version 0x100 quirks 0x0000200000000890
[   11.679164] scsi host1: ahci
[   11.689257] xhci_hcd 0002:c6:00.0: xHCI Host Controller
[   11.692134] scsi host2: ahci
[   11.696523] xhci_hcd 0002:c6:00.0: new USB bus registered, assigned bus number 4
[   11.701654] scsi host3: ahci
[   11.702289] r8169 0002:c9:00.0 enP2p201s0: renamed from eth1
[   11.705361] [drm] radeon kernel modesetting enabled.
[   11.705529] radeon 0000:01:00.0: vgaarb: deactivate vga console
[   11.706618] xhci_hcd 0002:c6:00.0: Host supports USB 3.0 SuperSpeed
[   11.710666] scsi host4: ahci
[   11.715888] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.06
[   11.721238] ata1: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410100 irq 66
[   11.726370] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[   11.726394] ata2: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410180 irq 66
[   11.726410] usb usb3: Product: xHCI Host Controller
[   11.726426] ata3: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410200 irq 66
[   11.726437] usb usb3: Manufacturer: Linux 6.6.127+ xhci-hcd
[   11.726451] ata4: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410280 irq 66
[   11.726460] usb usb3: SerialNumber: 0002:c6:00.0
[   11.726472] ata5: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410300 irq 66
[   11.727467] hub 3-0:1.0: USB hub found
[   11.735813] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   11.744126] hub 3-0:1.0: 1 port detected
[   11.752345] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   11.760122] usb usb4: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.06
[   11.768558] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   11.771859] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[   11.771870] usb usb4: Product: xHCI Host Controller
[   11.771876] usb usb4: Manufacturer: Linux 6.6.127+ xhci-hcd
[   11.772432] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   11.779686] usb usb4: SerialNumber: 0002:c6:00.0
[   11.874317] radeon 0000:01:00.0: enabling device (0006 -> 0007)
[   11.874856] hub 4-0:1.0: USB hub found
[   11.880999] [drm] initializing kernel modesetting (OLAND 0x1002:0x6611 0x1642:0x1601 0x87).
[   11.884201] hub 4-0:1.0: 4 ports detected
[   11.898907] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   11.906904] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   11.920679] usb 2-1: New USB device found, idVendor=2109, idProduct=0822, bcdDevice= 7.94
[   11.928938] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   11.936115] usb 2-1: Product: USB3.1 Hub             
[   11.941209] usb 2-1: Manufacturer: VIA Labs, Inc.         
[   11.946728] usb 2-1: SerialNumber: 000000001
[   11.957650] hub 2-1:1.0: USB hub found
[   11.961924] hub 2-1:1.0: 4 ports detected
[   12.041196] usb 1-2: new high-speed USB device number 3 using xhci_hcd
[   12.047693] ata1: SATA link down (SStatus 0 SControl 300)
[  OK  ] Finished Virtual Console Setup.
[   12.072425] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   12.080726] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   12.196393] usb 1-2: New USB device found, idVendor=2109, idProduct=2822, bcdDevice= 7.94
[   12.204612] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   12.211783] usb 1-2: Product: USB2.0 Hub             
[   12.211882] ATOM BIOS: C57701
[   12.216863] usb 1-2: Manufacturer: VIA Labs, Inc.         
[   12.216871] usb 1-2: SerialNumber: 000000001
[   12.223839] hub 1-2:1.0: USB hub found
[   12.225548] radeon 0000:01:00.0: VRAM: 2048M 0x0000000000000000 - 0x000000007FFFFFFF (2048M used)
[   12.229807] hub 1-2:1.0: 4 ports detected
[   12.233471] radeon 0000:01:00.0: GTT: 2048M 0x0000000080000000 - 0x00000000FFFFFFFF
[   12.233479] [drm] Detected VRAM RAM=2048M, BAR=256M
[   12.233484] [drm] RAM width 64bits DDR
[   12.233996] [drm] radeon: 2048M of VRAM memory ready
[   12.267754] [drm] radeon: 2048M of GTT memory ready.
[   12.272791] [drm] Loading oland Microcode
[   12.279651] [drm] Internal thermal controller with fan control
[   12.296355] [drm] radeon: dpm initialized
[   12.304205] [drm] GART: num cpu pages 524288, num gpu pages 524288
[   12.329186] usb 1-1.4: new full-speed USB device number 4 using xhci_hcd
[   12.345770] [drm] PCIE GART of 2048M enabled (table at 0x0000000000165000).
[   12.352936] radeon 0000:01:00.0: WB enabled
[   12.357188] radeon 0000:01:00.0: fence driver on ring 0 use gpu addr 0x0000000080000c00
[   12.357196] usb 3-1: new high-speed USB device number 2 using xhci_hcd
[   12.365218] radeon 0000:01:00.0: fence driver on ring 1 use gpu addr 0x0000000080000c04
[   12.365225] radeon 0000:01:00.0: fence driver on ring 2 use gpu addr 0x0000000080000c08
[   12.365230] radeon 0000:01:00.0: fence driver on ring 3 use gpu addr 0x0000000080000c0c
[   12.365234] radeon 0000:01:00.0: fence driver on ring 4 use gpu addr 0x0000000080000c10
[   12.366896] radeon 0000:01:00.0: fence driver on ring 5 use gpu addr 0x0000000000075a18
[   12.367665] ata2: SATA link down (SStatus 0 SControl 300)
[   12.373928] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   12.380499] radeon 0000:01:00.0: radeon: using MSI.
[   12.388370] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   12.396048] [drm] radeon: irq initialized.
[   12.522840] usb 3-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.20
[   12.531066] usb 3-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[   12.538240] usb 3-1: Product: USB2.0 Hub
[   12.577094] usb 1-1.4: New USB device found, idVendor=09da, idProduct=fa10, bcdDevice= 0.77
[   12.585483] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   12.592826] usb 1-1.4: Product: USB Device 
[   12.596623] [drm] ring test on 0 succeeded in 1 usecs
[   12.597042] usb 1-1.4: Manufacturer: COMPANY 
[   12.602114] [drm] ring test on 1 succeeded in 1 usecs
[   12.607827] hub 3-1:1.0: USB hub found
[   12.611593] [drm] ring test on 2 succeeded in 1 usecs
[   12.611606] [drm] ring test on 3 succeeded in 3 usecs
[   12.611781] hub 3-1:1.0: 4 ports detected
[   12.615402] [drm] ring test on 4 succeeded in 3 usecs
[   12.625523] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   12.642608] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   12.651342] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   12.683753] ata3: SATA link down (SStatus 0 SControl 300)
[   12.701892] usb 2-2: new SuperSpeed USB device number 3 using xhci_hcd
[   12.762424] usb 2-2: New USB device found, idVendor=2109, idProduct=0822, bcdDevice= 7.94
[   12.770630] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   12.777807] usb 2-2: Product: USB3.1 Hub             
[   12.782919] usb 2-2: Manufacturer: VIA Labs, Inc.         
[   12.788437] usb 2-2: SerialNumber: 000000001
[   12.792537] [drm] ring test on 5 succeeded in 2 usecs
[   12.797806] [drm] UVD initialized successfully.
[   12.800383] hub 2-2:1.0: USB hub found
[   12.802695] [drm] ib test on ring 0 succeeded in 0 usecs
[   12.806694] hub 2-2:1.0: 4 ports detected
[   12.811543] [drm] ib test on ring 1 succeeded in 0 usecs
[   12.811580] [drm] ib test on ring 2 succeeded in 0 usecs
[   12.826254] [drm] ib test on ring 3 succeeded in 0 usecs
[   12.831620] [drm] ib test on ring 4 succeeded in 0 usecs
[   12.921074] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   12.930025] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   13.003736] ata4: SATA link down (SStatus 0 SControl 300)
[   13.323673] ata5: SATA link down (SStatus 0 SControl 300)
[   13.416500] hid: raw HID events driver (C) Jiri Kosina
[   13.434630] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   13.443852] usbcore: registered new interface driver usbhid
[   13.449517] usbhid: USB HID core driver
[   13.451652] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   13.461802] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   13.470927] input: COMPANY  USB Device  as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:09DA:FA10.0001/input/input32
[   13.497319] [drm] ib test on ring 5 succeeded
[   13.503488] [drm] Radeon Display Connectors
[   13.507749] [drm] Connector 0:
[   13.510849] [drm]   HDMI-A-1
[   13.513757] [drm]   HPD2
[   13.516294] [drm]   DDC: 0x6530 0x6530 0x6534 0x6534 0x6538 0x6538 0x653c 0x653c
[   13.523720] [drm]   Encoders:
[   13.526712] [drm]     DFP1: INTERNAL_UNIPHY
[   13.530918] [drm] Connector 1:
[   13.533995] [drm]   VGA-1
[   13.536618] [drm]   DDC: 0x65c0 0x65c0 0x65c4 0x65c4 0x65c8 0x65c8 0x65cc 0x65cc
[   13.544033] [drm]   Encoders:
[   13.547022] [drm]     CRT1: INTERNAL_KLDSCP_DAC1
[   13.552882] [drm] Initialized radeon 2.50.0 20080528 for 0000:01:00.0 on minor 0
[   13.649535] [drm] fb mappable at 0x4200571000
[   13.653933] [drm] vram apper at 0x4200000000
[   13.658245] [drm] size 8294400
[   13.661326] [drm] fb depth is 24
[   13.664557] [drm]    pitch is 7680
[   13.821511] hid-generic 0003:09DA:FA10.0001: input,hidraw0: USB HID v1.11 Keyboard [COMPANY  USB Device ] on usb-0002:c4:00.0-1.4/input0
[   13.822032] input: COMPANY  USB Device  as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.1/0003:09DA:FA10.0002/input/input33
[   13.823145] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   13.823500] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   13.824169] hid-generic 0003:09DA:FA10.0002: input,hidraw1: USB HID v1.11 Mouse [COMPANY  USB Device ] on usb-0002:c4:00.0-1.4/input1
[   13.824963] input: COMPANY  USB Device  Keyboard as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.2/0003:09DA:FA10.0003/input/input36
[   13.826076] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   13.826385] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   13.828024] Console: switching to colour frame buffer device 240x67
[   13.885382] input: COMPANY  USB Device  as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.2/0003:09DA:FA10.0003/input/input37
[   13.885475] radeon 0000:01:00.0: [drm] fb0: radeondrmfb frame buffer device
[   13.886262] hid-generic 0003:09DA:FA10.0003: input,hiddev0,hidraw2: USB HID v1.11 Keyboard [COMPANY  USB Device ] on usb-0002:c4:00.0-1.4/input2
[   13.976925] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[  OK  ] Stopped    13.986432] gpio-keys soc:gpio-restart: there is not valid maps for state default
1;39mVirtual Console Setup.
         Stopping Vir[   13.999301] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
tual Console Setup...
[   14.009787] gpio-keys soc:gpio-restart: there is not valid maps for state default
         Starting Virtual Console Setup...
[  OK  ] Finished Virtual Console Setup.
[   32.115772] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   32.124451] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   32.162575] platform soc:gpio-poweroff: deferred probe pending
[   32.168564] platform soc:gpio-restart: deferred probe pending
[   32.174460] platform 704002a000.bm-emmc: deferred probe pending
[   32.180526] platform 704002b000.bm-sd: deferred probe pending
[   32.186415] platform 7030005000.i2c: deferred probe pending
[   32.192119] platform 7030006000.i2c: deferred probe pending
[   32.197825] platform 7030007000.i2c: deferred probe pending
[   32.203524] platform 7030008000.i2c: deferred probe pending
[   32.210850] [drm] amdgpu kernel modesetting enabled.
[  OK  ] Finished dracut pre-pivot and cleanup hook.
         Starting Cleaning Up and Shutting Down Daemons...
[  OK  ] Stopped target Timer Units.
[  OK  ] Stopped dracut pre-pivot and cleanup hook.
[  OK  ] Stopped target Initrd Default Target.
[  OK  ] Stopped target Basic System.
[  OK  ] Stopped target Initrd Root Device.
[  OK  ] Stopped target Initrd /usr File System.
[  OK  ] Stopped target Path Units.
[  OK  ] Stopped target Remote File Systems.
[  OK  ] Stopped target Preparation for Remote File Systems.
[  OK  ] Stopped target Slice Units.
[  OK  ] Stopped target Socket Units.
[  OK  ] Stopped target System Initialization.
[  OK  ] Stopped target Swaps.
[  OK  ] Stopped dracut pre-mount hook.
[  OK  ] Stopped dracut initqueue hook.
[  OK  ] Stopped Create List of Static Device Nodes.
         Starting Plymouth switch root service...
[  OK  ] Stopped Apply Kernel Variables.
[  OK  ] Stopped Create Volatile Files and Directories.
[  OK  ] Stopped target Local File Systems.
[  OK  ] Stopped target Preparation for Local File Systems.
[  OK  ] Stopped Coldplug All udev Devices.
[  OK  ] Stopped dracut pre-trigger hook.
         Stopping Rule-based Manager for Device Events and Files...
[  OK  ] Finished Cleaning Up and Shutting Down Daemons.
[  OK  ] Finished Plymouth switch root service.
[  OK  ] Stopped Rule-based Manager for Device Events and Files.
[  OK  ] Closed udev Control Socket.
[  OK  ] Closed udev Kernel Socket.
[  OK  ] Stopped dracut pre-udev hook.
[  OK  ] Stopped dracut cmdline hook.
         Starting Cleanup udev Database...
[  OK  ] Stopped Create Static Device Nodes in /dev.
[  OK  ] Finished Cleanup udev Database.
[  OK  ] Reached target Switch Root.
         Starting Switch Root...
[   33.209267] systemd-journald[606]: Received SIGTERM from PID 1 (systemd).
[   33.620485] systemd[1]: systemd v255-34.oe2403sp1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA -SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDIS)
[   33.664117] systemd[1]: Detected architecture riscv64.

Welcome to openEuler 24.03 (LTS-SP1)!

[   33.680609] systemd[1]: Hostname set to <openeuler-riscv64>.
[   34.006662] systemd[1]: /usr/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file acc.
[   34.460534] systemd[1]: initrd-switch-root.service: Deactivated successfully.
[   34.474062] systemd[1]: Stopped Switch Root.
[   34.487965] systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 1.
[  OK  ] Stopped Switch Root.
[   34.505914] systemd[1]: Created slice Slice /system/getty.
[  OK  ] Created slice Slice /system/getty.
[   34.518916] systemd[1]: Created slice Slice /system/modprobe.
[  OK  ] Created slice Slice /system/modprobe.
[   34.532925] systemd[1]: Created slice Slice /system/serial-getty.
[  OK  ] Created slice Slice /system/serial-getty.
[   34.547392] systemd[1]: Created slice Slice /system/sshd-keygen.
[  OK  ] Created slice Slice /system/sshd-keygen.
[   34.561592] systemd[1]: Created slice User and Session Slice.
[  OK  ] Created slice User and Session Slice.
[   34.573784] systemd[1]: Dispatch Password Requests to Console Directory Watch was skipped because of an unmet condition check (ConditionPathExists=!/run/plymouth/pid).
[   34.574193] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[   34.610316] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[  OK  ] Set up automount Arbitrary Executable File Formats File System Automount Point.
[   34.628480] systemd[1]: Stopped target Switch Root.
[  OK  ] Stopped target Switch Root.
[   34.643364] systemd[1]: Stopped target Initrd File Systems.
[  OK  ] Stopped target Initrd File Systems.
[   34.658685] systemd[1]: Stopped target Initrd Root File System.
[   34.674425] systemd[1]: Reached target Path Units.
[  OK  ] Stopped target Initrd Root File System.
[   34.684328] systemd[1]: Reached target rpc_pipefs.target.
[  OK  ] Reached target Path Units.
[   34.699508] systemd[1]: Reached target Slice Units.
[  OK  ] Reached target rpc_pipefs.target.
[   34.714393] systemd[1]: Reached target Swaps.
[  OK  ] Reached target Slice Units.
[  OK  ] Reached target Swaps.
[   34.729511] systemd[1]: Listening on Device-mapper event daemon FIFOs.
[   34.749456] systemd[1]: Listening on LVM2 poll daemon socket.
[  OK  ] Listening on Device-mapper event daemon FIFOs.
[   34.763014] systemd[1]: Listening on RPCbind Server Activation Socket.
[  OK  ] Listening on LVM2 poll daemon socket.
[   34.779158] systemd[1]: Reached target RPC Port Mapper.
[  OK  ] Listening on RPCbind Server Activation Socket.
[  OK  ] Reached target RPC Port Mapper.
[   34.800509] systemd[1]: Listening on Process Core Dump Socket.
[  OK  ] Listening on Process Core Dump Socket.
[   34.817575] systemd[1]: Listening on initctl Compatibility Named Pipe.
[  OK  ] Listening on initctl Compatibility Named Pipe.
[   34.835866] systemd[1]: Listening on udev Control Socket.
[  OK  ] Listening on udev Control Socket.
[   34.851731] systemd[1]: Listening on udev Kernel Socket.
[  OK  ] Listening on udev Kernel Socket.
[   34.901469] systemd[1]: Mounting Huge Pages File System...
         Mounting Huge Pages File System...
[   34.921586] systemd[1]: Mounting POSIX Message Queue File System...
         Mounting POSIX Message Queue File System...
[   34.946587] systemd[1]: Mounting Kernel Debug File System...
         Mounting Kernel Debug File System...
[   34.969333] systemd[1]: Mounting Kernel Trace File System...
         Mounting Kernel Trace File System...
[   34.991219] systemd[1]: Mounting Temporary Directory /tmp...
         Mounting Temporary Directory /tmp...
[   35.002823] systemd[1]: Kernel Module supporting RPCSEC_GSS was skipped because of an unmet condition check (ConditionPathExists=/etc/krb5.keytab).
[   35.008768] systemd[1]: Starting Create List of Static Device Nodes...
         Starting Create List of Static Device Nodes...
[   35.045982] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
         Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
[   35.065358] systemd[1]: Starting Load Kernel Module configfs...
         Starting Load Kernel Module configfs...
[   35.087331] systemd[1]: Starting Load Kernel Module drm...
         Starting Load Kernel Module drm...
[   35.107834] systemd[1]: Starting Load Kernel Module fuse...
         Starting Load Kernel Module fuse...
[   35.122507] systemd[1]: plymouth-switch-root.service: Deactivated successfully.
[   35.123189] systemd[1]: Stopped Plymouth switch root service.
[  OK  ] Stopped Plymouth switch root service.
[   35.152572] systemd[1]: systemd-fsck-root.service: Deactivated successfully.
[   35.153217] systemd[1]: Stopped File System Check on Root Device.
[  OK  ] Stopped File System Check on Root Device.
[   35.188134] systemd[1]: Starting Journal Service...
         Starting Journal Service...
[   35.198581] systemd[1]: Load Kernel Modules was skipped because no trigger condition checks were met.
[   35.203780] systemd[1]: Starting Generate network units from Kernel command line...
         Starting Generate network units from Kernel command line...
[   35.233827] systemd[1]: Starting Remount Root and Kernel File Systems...
         Starting Remount Root and Kernel File Systems...
[   35.250723] systemd[1]: Starting Apply Kernel Variables...
         Starting Apply Kernel Variables...
[   35.267004] systemd[1]: Starting Coldplug All udev Devices...
         Starting Coldplug All udev Devices...
[   35.281708] systemd-journald[1201]: Collecting audit messages is disabled.
[   35.282511] systemd[1]: Mounted Huge Pages File System.
[  OK  ] Mounted Huge Pages File System.
[   35.305714] systemd[1]: Mounted POSIX Message Queue File System.
[   35.315684] EXT4-fs (nvme0n1p3): re-mounted 07617bd8-13da-4749-97a3-2b548687b739 r/w.
[  OK  ] Mounted POSIX Message Queue File System.
[   35.335786] systemd[1]: Started Journal Service.
[  OK  ] Started Journal Service.
[  OK  ] Mounted Kernel Debug File System.
[  OK  ] Mounted Kernel Trace File System.
[  OK  ] Mounted Temporary Directory /tmp.
[  OK  ] Finished Create List of Static Device Nodes.
[  OK  ] Finished Load Kernel Module configfs.
[  OK  ] Finished Load Kernel Module drm.
[  OK  ] Finished Load Kernel Module fuse.
[  OK  ] Finished Generate network units from Kernel command line.
[  OK  ] Finished Remount Root and Kernel File Systems.
         Mounting FUSE Control File System...
         Mounting Kernel Configuration File System...
         Starting Flush Journal to Persistent Storage...
         Starting Load/Save OS Random Seed...
         Starting Create Static Device Nodes in /dev gracefully...
[  OK  ] Mounted FUSE Control File System.
[  OK  ] Mounted Kernel Configuration File System.
[  OK  ] Finished Apply Kernel Variables.
[   35.526662] systemd-journald[1201]: Received client request to flush runtime journal.
[   35.550024] systemd-journald[1201]: /var/log/journal/552c396b6af0485990643f5de1788949/system.journal: Realtime clock jumped backwards relative to last journal entry, rotating.
[  OK  ] Finished    35.568502] systemd-journald[1201]: Rotating system journal.
;1;39mCreate Static Device Nodes in /dev gracefully.
         Starting Create Static Device Nodes in /dev...
[  OK  ] Finished Create Static Device Nodes in /dev.
         Starting Rule-based Manager for Device Events and Files...
[  OK  ] Finished Flush Journal to Persistent Storage.
[  OK  ] Started Rule-based Manager for Device Events and Files.
         Starting Load Kernel Module fuse...
[  OK  ] Finished Coldplug All udev Devices.
[  OK  ] Finished Load Kernel Module fuse.
[   36.191287] sophgo-spifmc 7000180000.flash-controller: gd25lb512me (65536 Kbytes)
[  OK  ] Stopped Virtual Console Setup.
         Stopping Virtual Console Setup...
[   36.221724] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   36.225775] sophgo-spifmc 7002180000.flash-controller: gd25lb512me (65536 Kbytes)
[   36.232401] gpio-keys soc:gpio-restart: there is not valid maps for state default
         Starting Virtual Console Setup...
[   36.256299] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   36.256647] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   36.273598] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
[   36.290837] snd_hda_intel 0000:01:00.1: Force to snoop mode by module option
[   36.306357] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   36.316354] gpio-keys soc:gpio-restart: there is not valid maps for state default
[  OK  ] Finished Virtual Console Setup.
[   36.617211] random: crng init done
[  OK  ] Finished Load/Save OS Random Seed.
[  OK  ] Finished Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
[  OK  ] Reached target Preparation for Local File Systems.
         Mounting /boot...
[   36.760150] FAT-fs (nvme0n1p2): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[  OK  ] Mounted /boot.
         Mounting /boot/efi...
[   36.833966] FAT-fs (nvme0n1p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[  OK  ] Mounted /boot/efi.
[  OK  ] Reached target Local File Systems.
         Starting Tell Plymouth To Write Out Runtime Data...
         Starting Create Volatile Files and Directories...
[  OK  ] Finished Tell Plymouth To Write Out Runtime Data.
[  OK  ] Finished Create Volatile Files and Directories.
         Starting Security Auditing Service...
         Starting RPC Bind...
[  OK  ] Started RPC Bind.
[  OK  ] Started Security Auditing Service.
         Starting Record System Boot/Shutdown in UTMP...
[  OK  ] Finished Record System Boot/Shutdown in UTMP.
[  OK  ] Reached target System Initialization.
[  OK  ] Started dnf makecache --timer.
[  OK  ] Started Daily Cleanup of Temporary Dire[   37.309183] snd_hda_intel 0000:01:00.1: azx_get_response timeout, switching to polling mode: last cmd=0x000f0000
ctories.
[  OK  ] Reached target Timer Units.
[  OK  [   37.323629] snd_hda_intel 0000:01:00.1: bound 0000:01:00.0 (ops radeon_audio_component_bind_ops [radeon])
] Listening on D-Bus System Message Bus Socket.
[  OK  ] Listening on PC/SC Smart Card Daemon[   37.341862] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
 Activation Socket.
[   37.342172] gpio-keys soc:gpio-restart: there is not valid maps for state default
2m  OK  ] Reached target    37.345625] input: HDA ATI HDMI HDMI/DP,pcm=3 as /devices/platform/7060000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.1/sound/card0/input52
;1;39mSocket Units.
[  OK  ] Reached target Basic System.
         Starting NTP client/server...
         Starting D-Bus System Message Bus...
         Starting Restore /run/initramfs on shutdown...
         Starting Update RTC With System Clock...
         Starting irqbalance daemon...
[  OK  ] Started libstoragemgmt plug-in server daemon.
[  OK  ] Started resize rootfs.
[  OK  ] Started Hardware RNG Entropy Gatherer Daemon.
         Starting Self Monitoring and Reporting Technology (SMART) Daemon...
[  OK  ] Reached target sshd-keygen.target.
         Starting User Login Management...
         Starting Run a configured list of systemtap scripts at system startup....
[  OK  ] Started D-Bus System Message Bus.
[  OK  ] Finished Restore /run/initramfs on shutdown.
[  OK  ] Finished Update RTC With System Clock.
[  OK  ] Started irqbalance daemon.
[  OK  ] Reached target Sound Card.
         Starting firewalld - dynamic firewall daemon...
[  OK  ] Started Self Monitoring and Reporting Technology (SMART) Daemon.
[  OK  ] Started NTP client/server.
[  OK  ] Finished Run a configured list of systemtap scripts at system startup..
[  OK  ] Started User Login Management.
[  OK  ] Started firewalld - dynamic firewall daemon.
[  OK  ] Reached target Preparation for Network.
         Starting Network Manager...
         Starting Hostname Service...
[  OK  ] Started Hostname Service.
         Starting Network Manager Script Dispatcher Service...
[   39.253277] RTL8226B_RTL8221B 2.5Gbps PHY r8169-2-c500:00: attached PHY driver (mii_bus:phy_addr=r8169-2-c500:00, irq=MAC)
[  OK  ] Started Network Manager Script Dispatcher Service.
[   39.469916] r8169 0002:c5:00.0 enP2p197s0: Link is Down
[   39.517430] RTL8226B_RTL8221B 2.5Gbps PHY r8169-2-c900:00: attached PHY driver (mii_bus:phy_addr=r8169-2-c900:00, irq=MAC)
[   39.752713] r8169 0002:c9:00.0 enP2p201s0: Link is Down
[  OK  ] Started Network Manager.
[  OK  ] Reached target Network.
         Starting Network Manager Wait Online...
         Starting GSSAPI Proxy Daemon...
         Starting /etc/rc.d/rc.local Compatibility...
         Starting OpenSSH server daemon...
         Starting Dynamic System Tuning Daemon...
         Starting Authorization Manager...
[  OK  ] Started /etc/rc.d/rc.local Compatibility.
[  OK  ] Started OpenSSH server daemon.
[  OK  ] Started GSSAPI Proxy Daemon.
[  OK  ] Reached target NFS client services.
[  OK  ] Reached target Preparation for Remote File Systems.
[  OK  ] Reached target Remote File Systems.
         Starting Permit User Sessions...
[  OK  ] Finished Permit User Sessions.
[  OK  ] Started Deferred execution scheduler.
[  OK  ] Started Command Scheduler.
         Starting Hold until boot process finishes up...
         Starting Terminate Plymouth Boot Screen...
[   41.894739] r8169 0002:c5:00.0 enP2p197s0: Link is Up - 1Gbps/Full - flow control rx/tx


Authorized users only. All activities may be monitored and reported.
openeuler-riscv64 login: root
Password: 
Last login: Mon Mar 30 22:23:28 on tty1

Authorized users only. All activities may be monitored and reported.


Welcome to 6.6.127+

System information as of time:  Mon Mar 30 22:38:22 CST 2026

System load:    0.16
Memory used:    .5%
Swap used:      0.0%
Usage On:       3%
IP address:     192.168.1.9
Users online:   1


[root@openeuler-riscv64 ~]# poweroff
```

poweroff
```
[  OK  ] Reached target Switch Root.
         Starting Switch Root...
[   33.209267] systemd-journald[606]: Received SIGTERM from PID 1 (systemd).
[   33.620485] systemd[1]: systemd v255-34.oe2403sp1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA -SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDIS)
[   33.664117] systemd[1]: Detected architecture riscv64.

Welcome to openEuler 24.03 (LTS-SP1)!

[   33.680609] systemd[1]: Hostname set to <openeuler-riscv64>.
[   34.006662] systemd[1]: /usr/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file acc.
[   34.460534] systemd[1]: initrd-switch-root.service: Deactivated successfully.
[   34.474062] systemd[1]: Stopped Switch Root.
[   34.487965] systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 1.
[  OK  ] Stopped Switch Root.
[   34.505914] systemd[1]: Created slice Slice /system/getty.
[  OK  ] Created slice Slice /system/getty.
[   34.518916] systemd[1]: Created slice Slice /system/modprobe.
[  OK  ] Created slice Slice /system/modprobe.
[   34.532925] systemd[1]: Created slice Slice /system/serial-getty.
[  OK  ] Created slice Slice /system/serial-getty.
[   34.547392] systemd[1]: Created slice Slice /system/sshd-keygen.
[  OK  ] Created slice Slice /system/sshd-keygen.
[   34.561592] systemd[1]: Created slice User and Session Slice.
[  OK  ] Created slice User and Session Slice.
[   34.573784] systemd[1]: Dispatch Password Requests to Console Directory Watch was skipped because of an unmet condition check (ConditionPathExists=!/run/plymouth/pid).
[   34.574193] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[   34.610316] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[  OK  ] Set up automount Arbitrary Executable File Formats File System Automount Point.
[   34.628480] systemd[1]: Stopped target Switch Root.
[  OK  ] Stopped target Switch Root.
[   34.643364] systemd[1]: Stopped target Initrd File Systems.
[  OK  ] Stopped target Initrd File Systems.
[   34.658685] systemd[1]: Stopped target Initrd Root File System.
[   34.674425] systemd[1]: Reached target Path Units.
[  OK  ] Stopped target Initrd Root File System.
[   34.684328] systemd[1]: Reached target rpc_pipefs.target.
[  OK  ] Reached target Path Units.
[   34.699508] systemd[1]: Reached target Slice Units.
[  OK  ] Reached target rpc_pipefs.target.
[   34.714393] systemd[1]: Reached target Swaps.
[  OK  ] Reached target Slice Units.
[  OK  ] Reached target Swaps.
[   34.729511] systemd[1]: Listening on Device-mapper event daemon FIFOs.
[   34.749456] systemd[1]: Listening on LVM2 poll daemon socket.
[  OK  ] Listening on Device-mapper event daemon FIFOs.
[   34.763014] systemd[1]: Listening on RPCbind Server Activation Socket.
[  OK  ] Listening on LVM2 poll daemon socket.
[   34.779158] systemd[1]: Reached target RPC Port Mapper.
[  OK  ] Listening on RPCbind Server Activation Socket.
[  OK  ] Reached target RPC Port Mapper.
[   34.800509] systemd[1]: Listening on Process Core Dump Socket.
[  OK  ] Listening on Process Core Dump Socket.
[   34.817575] systemd[1]: Listening on initctl Compatibility Named Pipe.
[  OK  ] Listening on initctl Compatibility Named Pipe.
[   34.835866] systemd[1]: Listening on udev Control Socket.
[  OK  ] Listening on udev Control Socket.
[   34.851731] systemd[1]: Listening on udev Kernel Socket.
[  OK  ] Listening on udev Kernel Socket.
[   34.901469] systemd[1]: Mounting Huge Pages File System...
         Mounting Huge Pages File System...
[   34.921586] systemd[1]: Mounting POSIX Message Queue File System...
         Mounting POSIX Message Queue File System...
[   34.946587] systemd[1]: Mounting Kernel Debug File System...
         Mounting Kernel Debug File System...
[   34.969333] systemd[1]: Mounting Kernel Trace File System...
         Mounting Kernel Trace File System...
[   34.991219] systemd[1]: Mounting Temporary Directory /tmp...
         Mounting Temporary Directory /tmp...
[   35.002823] systemd[1]: Kernel Module supporting RPCSEC_GSS was skipped because of an unmet condition check (ConditionPathExists=/etc/krb5.keytab).
[   35.008768] systemd[1]: Starting Create List of Static Device Nodes...
         Starting Create List of Static Device Nodes...
[   35.045982] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
         Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
[   35.065358] systemd[1]: Starting Load Kernel Module configfs...
         Starting Load Kernel Module configfs...
[   35.087331] systemd[1]: Starting Load Kernel Module drm...
         Starting Load Kernel Module drm...
[   35.107834] systemd[1]: Starting Load Kernel Module fuse...
         Starting Load Kernel Module fuse...
[   35.122507] systemd[1]: plymouth-switch-root.service: Deactivated successfully.
[   35.123189] systemd[1]: Stopped Plymouth switch root service.
[  OK  ] Stopped Plymouth switch root service.
[   35.152572] systemd[1]: systemd-fsck-root.service: Deactivated successfully.
[   35.153217] systemd[1]: Stopped File System Check on Root Device.
[  OK  ] Stopped File System Check on Root Device.
[   35.188134] systemd[1]: Starting Journal Service...
         Starting Journal Service...
[   35.198581] systemd[1]: Load Kernel Modules was skipped because no trigger condition checks were met.
[   35.203780] systemd[1]: Starting Generate network units from Kernel command line...
         Starting Generate network units from Kernel command line...
[   35.233827] systemd[1]: Starting Remount Root and Kernel File Systems...
         Starting Remount Root and Kernel File Systems...
[   35.250723] systemd[1]: Starting Apply Kernel Variables...
         Starting Apply Kernel Variables...
[   35.267004] systemd[1]: Starting Coldplug All udev Devices...
         Starting Coldplug All udev Devices...
[   35.281708] systemd-journald[1201]: Collecting audit messages is disabled.
[   35.282511] systemd[1]: Mounted Huge Pages File System.
[  OK  ] Mounted Huge Pages File System.
[   35.305714] systemd[1]: Mounted POSIX Message Queue File System.
[   35.315684] EXT4-fs (nvme0n1p3): re-mounted 07617bd8-13da-4749-97a3-2b548687b739 r/w.
[  OK  ] Mounted POSIX Message Queue File System.
[   35.335786] systemd[1]: Started Journal Service.
[  OK  ] Started Journal Service.
[  OK  ] Mounted Kernel Debug File System.
[  OK  ] Mounted Kernel Trace File System.
[  OK  ] Mounted Temporary Directory /tmp.
[  OK  ] Finished Create List of Static Device Nodes.
[  OK  ] Finished Load Kernel Module configfs.
[  OK  ] Finished Load Kernel Module drm.
[  OK  ] Finished Load Kernel Module fuse.
[  OK  ] Finished Generate network units from Kernel command line.
[  OK  ] Finished Remount Root and Kernel File Systems.
         Mounting FUSE Control File System...
         Mounting Kernel Configuration File System...
         Starting Flush Journal to Persistent Storage...
         Starting Load/Save OS Random Seed...
         Starting Create Static Device Nodes in /dev gracefully...
[  OK  ] Mounted FUSE Control File System.
[  OK  ] Mounted Kernel Configuration File System.
[  OK  ] Finished Apply Kernel Variables.
[   35.526662] systemd-journald[1201]: Received client request to flush runtime journal.
[   35.550024] systemd-journald[1201]: /var/log/journal/552c396b6af0485990643f5de1788949/system.journal: Realtime clock jumped backwards relative to last journal entry, rotating.
[  OK  ] Finished    35.568502] systemd-journald[1201]: Rotating system journal.
;1;39mCreate Static Device Nodes in /dev gracefully.
         Starting Create Static Device Nodes in /dev...
[  OK  ] Finished Create Static Device Nodes in /dev.
         Starting Rule-based Manager for Device Events and Files...
[  OK  ] Finished Flush Journal to Persistent Storage.
[  OK  ] Started Rule-based Manager for Device Events and Files.
         Starting Load Kernel Module fuse...
[  OK  ] Finished Coldplug All udev Devices.
[  OK  ] Finished Load Kernel Module fuse.
[   36.191287] sophgo-spifmc 7000180000.flash-controller: gd25lb512me (65536 Kbytes)
[  OK  ] Stopped Virtual Console Setup.
         Stopping Virtual Console Setup...
[   36.221724] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   36.225775] sophgo-spifmc 7002180000.flash-controller: gd25lb512me (65536 Kbytes)
[   36.232401] gpio-keys soc:gpio-restart: there is not valid maps for state default
         Starting Virtual Console Setup...
[   36.256299] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   36.256647] gpio-keys soc:gpio-restart: there is not valid maps for state default
[   36.273598] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
[   36.290837] snd_hda_intel 0000:01:00.1: Force to snoop mode by module option
[   36.306357] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
[   36.316354] gpio-keys soc:gpio-restart: there is not valid maps for state default
[  OK  ] Finished Virtual Console Setup.
[   36.617211] random: crng init done
[  OK  ] Finished Load/Save OS Random Seed.
[  OK  ] Finished Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
[  OK  ] Reached target Preparation for Local File Systems.
         Mounting /boot...
[   36.760150] FAT-fs (nvme0n1p2): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[  OK  ] Mounted /boot.
         Mounting /boot/efi...
[   36.833966] FAT-fs (nvme0n1p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[  OK  ] Mounted /boot/efi.
[  OK  ] Reached target Local File Systems.
         Starting Tell Plymouth To Write Out Runtime Data...
         Starting Create Volatile Files and Directories...
[  OK  ] Finished Tell Plymouth To Write Out Runtime Data.
[  OK  ] Finished Create Volatile Files and Directories.
         Starting Security Auditing Service...
         Starting RPC Bind...
[  OK  ] Started RPC Bind.
[  OK  ] Started Security Auditing Service.
         Starting Record System Boot/Shutdown in UTMP...
[  OK  ] Finished Record System Boot/Shutdown in UTMP.
[  OK  ] Reached target System Initialization.
[  OK  ] Started dnf makecache --timer.
[  OK  ] Started Daily Cleanup of Temporary Dire[   37.309183] snd_hda_intel 0000:01:00.1: azx_get_response timeout, switching to polling mode: last cmd=0x000f0000
ctories.
[  OK  ] Reached target Timer Units.
[  OK  [   37.323629] snd_hda_intel 0000:01:00.1: bound 0000:01:00.0 (ops radeon_audio_component_bind_ops [radeon])
] Listening on D-Bus System Message Bus Socket.
[  OK  ] Listening on PC/SC Smart Card Daemon[   37.341862] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
 Activation Socket.
[   37.342172] gpio-keys soc:gpio-restart: there is not valid maps for state default
2m  OK  ] Reached target    37.345625] input: HDA ATI HDMI HDMI/DP,pcm=3 as /devices/platform/7060000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.1/sound/card0/input52
;1;39mSocket Units.
[  OK  ] Reached target Basic System.
         Starting NTP client/server...
         Starting D-Bus System Message Bus...
         Starting Restore /run/initramfs on shutdown...
         Starting Update RTC With System Clock...
         Starting irqbalance daemon...
[  OK  ] Started libstoragemgmt plug-in server daemon.
[  OK  ] Started resize rootfs.
[  OK  ] Started Hardware RNG Entropy Gatherer Daemon.
         Starting Self Monitoring and Reporting Technology (SMART) Daemon...
[  OK  ] Reached target sshd-keygen.target.
         Starting User Login Management...
         Starting Run a configured list of systemtap scripts at system startup....
[  OK  ] Started D-Bus System Message Bus.
[  OK  ] Finished Restore /run/initramfs on shutdown.
1;-1f[  OK  ] Stopped Permit User Sessions.
[  OK  ] Stopped target Remote File Systems.
[  OK  ] Stopped target Preparation for Remote File Systems.
[  OK  ] Stopped target NFS client services.
         Stopping GSSAPI Proxy Daemon...
[  OK  ] Stopped Dynamic System Tuning Daemon.
[  OK  ] Stopped GSSAPI Proxy Daemon.
[  OK  ] Started Show Plymouth Power Off Screen.
[  OK  ] Stopped target Network.
         Stopping Network Manager...
[  OK  ] Stopped Network Manager.
[  OK  ] Stopped target Preparation for Network.
         Stopping firewalld - dynamic firewall daemon...
[  OK  ] Stopped Generate network units from Kernel command line.
[  OK  ] Stopped firewalld - dynamic firewall daemon.
         Stopping D-Bus System Message Bus...
         Stopping Authorization Manager...
[  OK  ] Stopped D-Bus System Message Bus.
[  OK  ] Stopped Authorization Manager.
[  OK  ] Stopped target Basic System.
[  OK  ] Stopped Forward Password Requests to Plymouth Directory Watch.
[  OK  ] Stopped target Path Units.
[  OK  ] Stopped Forward Password Requests to Wall Directory Watch.
[  OK  ] Stopped target Slice Units.
[  OK  ] Removed slice User and Session Slice.
[  OK  ] Stopped target Socket Units.
[  OK  ] Closed D-Bus System Message Bus Socket.
[  OK  ] Closed PC/SC Smart Card Daemon Activation Socket.
[  OK  ] Stopped target System Initialization.
[  OK  ] Unset automount Arbitrary Executable File Formats File System Automount Point.
[  OK  ] Stopped Apply Kernel Variables.
[  OK  ] Closed Process Core Dump Socket.
         Stopping Record System Boot/Shutdown in UTMP...
[  OK  ] Stopped Record System Boot/Shutdown in UTMP.
         Stopping Security Auditing Servi[  636.281948] audit: type=1305 audit(1774881583.167:96): op=set audit_pid=0 old=1422 auid=4294967295 ses=4294967295 subj=unconfined res=1
ce...
[  636.299707] audit: type=1131 audit(1774881583.183:97): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=auditd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  OK  ] Stopped   636.319649] audit: type=1131 audit(1774881583.203:98): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termi'
1;39mSecurity Auditing Service.
[  OK  ] Stopped Create Volatile Files and Directories.
[  OK  ] Stopped target Local File Systems.
         Unmounting /boot/efi...
         Unmounting Temporary Directory /tmp...
[  OK  ] Unmounted Temporary Directory /tmp.
[  OK  ] Stopped target Swaps.
[  OK  ] Unmounted /boot/efi.
         Unmounting /boot...
[  OK  ] Unmounted /boot.
[  OK  ] Stopped target Preparation for Local File Syste[  636.485345] audit: type=1131 audit(1774881583.367:99): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-remount-fs comm="systemd" exe="/usr/lib/syst'
ms.
[  OK  ] Re[  636.509090] audit: type=1131 audit(1774881583.391:100): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup-dev comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termi'
ached target Unmount Al[  636.533088] audit: type=1131 audit(1774881583.415:101): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup-dev-early comm="systemd" exe="/usr/lib/systemd/systemd" hostn'
l Filesystems.
         St[  636.559414] audit: type=1131 audit(1774881583.443:102): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=lvm2-monitor comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=succ'
opping Monitoring of LV[  636.581659] audit: type=1130 audit(1774881583.463:103): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-poweroff comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? ter'
M2 mirrors, snapshots etc. using[  636.603011] audit: type=1131 audit(1774881583.463:104): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-poweroff comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? a'
 dmeventd or progress polling...
[  OK  ] Stopped Remount Root and Kernel File Systems.
[  OK  ] Stopped Create Static Device Nodes in /dev.
[  OK  ] Stopped Create Static Device Nodes in /dev gracefully.
[  OK  ] Stopped Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
[  OK  ] Reached target System Shutdown.
[  OK  ] Reached target Late Shutdown Services.
[  OK  ] Finished System Power Off.
[  OK  ] Reached target System Power Off.
[  636.797550] systemd-shutdown[1]: Syncing filesystems and block devices.
[  636.812866] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  636.922730] systemd-journald[1201]: Received SIGTERM from PID 1 (systemd-shutdow).
[  636.984247] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  637.177412] systemd-shutdown[1]: Unmounting file systems.
[  637.186000] (sd-remount)[2172]: Remounting '/' read-only with options ''.
[  637.244917] EXT4-fs (nvme0n1p3): re-mounted 07617bd8-13da-4749-97a3-2b548687b739 ro.
[  637.307447] systemd-shutdown[1]: All filesystems unmounted.
[  637.313192] systemd-shutdown[1]: Deactivating swaps.
[  637.318493] systemd-shutdown[1]: All swaps deactivated.
[  637.323865] systemd-shutdown[1]: Detaching loop devices.
[  637.334092] systemd-shutdown[1]: All loop devices detached.
[  637.339772] systemd-shutdown[1]: Stopping MD devices.
[  637.345168] systemd-shutdown[1]: All MD devices stopped.
[  637.350568] systemd-shutdown[1]: Detaching DM devices.
[  637.355991] systemd-shutdown[1]: All DM devices detached.
[  637.361474] systemd-shutdown[1]: All filesystems, swaps, loop devices, MD devices and DM devices detached.
[  637.410897] systemd-shutdown[1]: Syncing filesystems and block devices.
[  637.417769] systemd-shutdown[1]: Powering off.
[  637.522257] r8169 0002:c5:00.0 enP2p197s0: Link is Down
[  637.553174] reboot: Power down
mango_system_reset: chip is not mango

```
此时风扇狂转

**Comment by uestc-gr** [comment]
> > > 我在milkv pioneer上测试，这个pr在空负载时降低了风扇转速，很安静。但是执行poweroff后，风扇转速升高，主板不下电，关机失败。这个pr需要更多的物理机测试。
> > 
> > 
> > 理论上这个功能 在不支持sbi3.0的设备不会开启，即使开启了也只会处理非对齐处理，不会影响其它流程，是否是与lava故障一样initramfs没有重新编译导致，能否取一下上下电串口日志看看
> 
> boot
> 
> ```
> [    0.000000] software IO TLB: mapped [mem 0x00000000bbe3d000-0x00000000bfe3d000] (64MB)
> [    0.000000] Memory: 126955100K/130023424K available (11202K kernel code, 5727K rwdata, 10240K rodata, 2714K init, 520K bss, 2806180K reserved, 262144K cma-reserved)
> [    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=64, Nodes=4
> [    0.000000] ftrace: allocating 41282 entries in 162 pages
> [    0.000000] ftrace: allocated 162 pages with 3 groups
> [    0.000000] rcu: Hierarchical RCU implementation.
> [    0.000000]  Rude variant of Tasks RCU enabled.
> [    0.000000]  Tracing variant of Tasks RCU enabled.
> [    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
> [    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
> [    0.000000] riscv-intc: 64 local interrupts mapped
> [    0.000000] riscv-plic: interrupt-controller@7090000000: mapped 224 interrupts with 64 handlers for 128 contexts.
> [    0.000000] riscv: providing IPIs using SBI IPI extension
> [    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
> [    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0xb8812736b, max_idle_ns: 440795202655 ns
> [    0.000000] sched_clock: 64 bits at 50MHz, resolution 20ns, wraps every 4398046511100ns
> [    0.008513] clocksource: dw-apb-timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 38225208935 ns
> [    0.018423] sched_clock: 32 bits at 50MHz, resolution 20ns, wraps every 42949672950ns
> [    0.026951] Console: colour dummy device 80x25
> [    0.031422] printk: console [tty0] enabled
> [    0.035532] printk: bootconsole [uart0] disabled
> [    0.000000] Linux version 6.6.127+ (root@openeuler-riscv64) (gcc (GCC) 12.3.1 (openEuler 12.3.1-62.oe2403sp1), GNU ld (GNU Binutils) 2.41) #4 SMP Fri Mar 27 01:16:22 CST 2026
> [    0.000000] Machine model: Sophgo Mango
> [    0.000000] SBI specification v1.0 detected
> [    0.000000] SBI implementation ID=0x1 Version=0x10002
> [    0.000000] SBI TIME extension detected
> [    0.000000] SBI IPI extension detected
> [    0.000000] SBI RFENCE extension detected
> [    0.000000] SBI SRST extension detected
> [    0.000000] efi: EFI v2.7 by EDK II
> [    0.000000] efi: SMBIOS=0xbffdc000 INITRD=0xb7a0ea98 MEMRESERVE=0xb7a0e118 
> [    0.000000] OF: reserved mem: 0x0000000000000000..0x00000000001fffff (2048 KiB) map non-reusable mmode_resv0@0
> [    0.000000] cma: Reserved 256 MiB at 0x0000000098200000 on node -1
> [    0.000000] earlycon: uart0 at MMIO32 0x0000007040000000 (options '')
> [    0.000000] printk: bootconsole [uart0] enabled
> [    0.000000] OF: NUMA: parsing numa-distance-map-v1
> [    0.000000] NUMA: NODE_DATA [mem 0x7ffffdfc0-0x7ffffffff]
> [    0.000000] NUMA: NODE_DATA [mem 0xfffffdfc0-0xfffffffff]
> [    0.000000] NUMA: NODE_DATA [mem 0x17ffffdfc0-0x17ffffffff]
> [    0.000000] NUMA: NODE_DATA [mem 0x1f42531fc0-0x1f42533fff]
> [    0.000000] Zone ranges:
> [    0.000000]   DMA32    [mem 0x0000000002800000-0x00000000ffffffff]
> [    0.000000]   Normal   [mem 0x0000000100000000-0x0000001f427fffff]
> [    0.000000] Movable zone start for each node
> [    0.000000] Early memory node ranges
> [    0.000000]   node   0: [mem 0x0000000002800000-0x00000000bfe3cfff]
> [    0.000000]   node   0: [mem 0x00000000bfe3d000-0x00000000bfffefff]
> [    0.000000]   node   0: [mem 0x00000000bffff000-0x00000000bfffffff]
> [    0.000000]   node   0: [mem 0x0000000100000000-0x00000007ffffffff]
> [    0.000000]   node   1: [mem 0x0000000800000000-0x0000000fffffffff]
> [    0.000000]   node   2: [mem 0x0000001000000000-0x00000017ffffffff]
> [    0.000000]   node   3: [mem 0x0000001800000000-0x0000001f427fffff]
> [    0.000000] Initmem setup node 0 [mem 0x0000000002800000-0x00000007ffffffff]
> [    0.000000] Initmem setup node 1 [mem 0x0000000800000000-0x0000000fffffffff]
> [    0.000000] Initmem setup node 2 [mem 0x0000001000000000-0x00000017ffffffff]
> [    0.000000] Initmem setup node 3 [mem 0x0000001800000000-0x0000001f427fffff]
> [    0.000000] On node 0, zone DMA32: 10240 pages in unavailable ranges
> [    0.000000] On node 3, zone Normal: 22528 pages in unavailable ranges
> [    0.000000] SBI HSM extension detected
> [    0.000000] Falling back to deprecated "riscv,isa"
> [    0.000000] Vendor extensions are ignored in riscv,isa. Use riscv,isa-extensions instead.
> [    0.000000] riscv: base ISA extensions acdfim
> [    0.000000] riscv: ELF capabilities acdfim
> [    0.000000] Ticket spinlock: enabled
> [    0.000000] percpu: cpu 0 has no node -1 or node-local memory
> [    0.000000] percpu: Embedded 29 pages/cpu s80872 r8192 d29720 u118784
> [    0.000000] Kernel command line: BOOT_IMAGE=/Image root=/dev/nvme0n1p3 ro selinux=0 console=ttyS0,115200 console=tty earlycon rootwait
> [    0.000000] Unknown kernel command line parameters "selinux=0", will be passed to user space.
> [    0.000000] printk: log_buf_len individual max cpu contribution: 4096 bytes
> [    0.000000] printk: log_buf_len total cpu_extra contributions: 258048 bytes
> [    0.000000] printk: log_buf_len min size: 131072 bytes
> [    0.000000] printk: log_buf_len: 524288 bytes
> [    0.000000] printk: early log buf free: 127264(97%)
> [    0.000000] Fallback order for Node 0: 0 1 2 3 
> [    0.000000] Fallback order for Node 1: 1 0 3 2 
> [    0.000000] Fallback order for Node 2: 2 3 0 1 
> [    0.000000] Fallback order for Node 3: 3 2 1 0 
> [    0.000000] Built 4 zonelists, mobility grouping on.  Total pages: 31870976
> [    0.000000] Policy zone: Normal
> [    0.000000] mem auto-init: stack:all(pattern), heap alloc:on, heap free:off
> [    0.000000] software IO TLB: area num 64.
> [    0.000000] software IO TLB: mapped [mem 0x00000000bbe3d000-0x00000000bfe3d000] (64MB)
> [    0.000000] Memory: 126955100K/130023424K available (11202K kernel code, 5727K rwdata, 10240K rodata, 2714K init, 520K bss, 2806180K reserved, 262144K cma-reserved)
> [    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=64, Nodes=4
> [    0.000000] ftrace: allocating 41282 entries in 162 pages
> [    0.000000] ftrace: allocated 162 pages with 3 groups
> [    0.000000] rcu: Hierarchical RCU implementation.
> [    0.000000]  Rude variant of Tasks RCU enabled.
> [    0.000000]  Tracing variant of Tasks RCU enabled.
> [    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
> [    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
> [    0.000000] riscv-intc: 64 local interrupts mapped
> [    0.000000] riscv-plic: interrupt-controller@7090000000: mapped 224 interrupts with 64 handlers for 128 contexts.
> [    0.000000] riscv: providing IPIs using SBI IPI extension
> [    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
> [    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0xb8812736b, max_idle_ns: 440795202655 ns
> [    0.000000] sched_clock: 64 bits at 50MHz, resolution 20ns, wraps every 4398046511100ns
> [    0.008513] clocksource: dw-apb-timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 38225208935 ns
> [    0.018423] sched_clock: 32 bits at 50MHz, resolution 20ns, wraps every 42949672950ns
> [    0.026951] Console: colour dummy device 80x25
> [    0.031422] printk: console [tty0] enabled
> [    0.035532] printk: bootconsole [uart0] disabled
> [    0.041611] mempolicy: Enabling automatic NUMA balancing. Configure with numa_balancing= or the kernel.numa_balancing sysctl
> [    0.041730] Calibrating delay loop (skipped), value calculated using timer frequency.. 100.00 BogoMIPS (lpj=200000)
> [    0.041756] pid_max: default: 65536 minimum: 512
> [    0.044623] LSM: initializing lsm=lockdown,capability,landlock,yama,apparmor,tomoyo,bpf,integrity
> [    0.044689] landlock: Up and running.
> [    0.044698] Yama: becoming mindful.
> [    0.044817] AppArmor: AppArmor initialized
> [    0.044837] TOMOYO Linux initialized
> [    0.044868] LSM support for eBPF active
> [    0.068355] Dentry cache hash table entries: 8388608 (order: 14, 67108864 bytes, vmalloc hugepage)
> [    0.080238] Inode-cache hash table entries: 4194304 (order: 13, 33554432 bytes, vmalloc hugepage)
> [    0.081298] Mount-cache hash table entries: 131072 (order: 8, 1048576 bytes, vmalloc)
> [    0.081808] Mountpoint-cache hash table entries: 131072 (order: 8, 1048576 bytes, vmalloc)
> [    0.130600] RCU Tasks Rude: Setting shift to 6 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=64.
> [    0.130766] RCU Tasks Trace: Setting shift to 6 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=64.
> [    0.130865] riscv: ELF compat mode unsupported
> [    0.131020] ASID allocator using 16 bits (65536 entries)
> [    0.131182] rcu: Hierarchical SRCU implementation.
> [    0.131197] rcu:     Max phase no-delay instances is 1000.
> [    0.131863] Remapping and enabling EFI services.
> [    0.135082] smp: Bringing up secondary CPUs ...
> [    0.180707] smp: Brought up 4 nodes, 64 CPUs
> [    0.212594] devtmpfs: initialized
> [    0.221711] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
> [    0.222216] futex hash table entries: 16384 (order: 8, 1048576 bytes, vmalloc)
> [    0.229045] pinctrl core: initialized pinctrl subsystem
> [    0.229882] SMBIOS 2.8 present.
> [    0.229913] DMI: SOPHGO Sophgo SG2042 EVB Board/Sophgo SG2042 EVB Board, BIOS V1.0 Mar 27 2024
> [    0.231476] NET: Registered PF_NETLINK/PF_ROUTE protocol family
> [    0.234102] DMA: preallocated 4096 KiB GFP_KERNEL pool for atomic allocations
> [    0.235062] DMA: preallocated 4096 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
> [    0.236066] audit: initializing netlink subsys (disabled)
> [    0.236423] audit: type=2000 audit(0.208:1): state=initialized audit_enabled=0 res=1
> [    0.237182] thermal_sys: Registered thermal governor 'fair_share'
> [    0.237194] thermal_sys: Registered thermal governor 'bang_bang'
> [    0.237216] thermal_sys: Registered thermal governor 'step_wise'
> [    0.237227] thermal_sys: Registered thermal governor 'user_space'
> [    0.237238] thermal_sys: Registered thermal governor 'power_allocator'
> [    0.237359] cpuidle: using governor ladder
> [    0.237423] cpuidle: using governor menu
> [    0.265051] cpu63: Ratio of byte access time to unaligned word access is 2.86, unaligned accesses are fast
> [    0.265051] cpu62: Ratio of byte access time to unaligned word access is 2.81, unaligned accesses are fast
> [    0.265051] cpu61: Ratio of byte access time to unaligned word access is 2.86, unaligned accesses are fast
> [    0.265051] cpu60: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
> [    0.265055] cpu5: Ratio of byte access time to unaligned word access is 3.98, unaligned accesses are fast
> [    0.265054] cpu47: Ratio of byte access time to unaligned word access is 3.01, unaligned accesses are fast
> [    0.265054] cpu45: Ratio of byte access time to unaligned word access is 3.00, unaligned accesses are fast
> [    0.265055] cpu36: Ratio of byte access time to unaligned word access is 3.14, unaligned accesses are fast
> [    0.265051] cpu11: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> [    0.265051] cpu24: Ratio of byte access time to unaligned word access is 3.30, unaligned accesses are fast
> [    0.265054] cpu44: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
> [    0.265054] cpu46: Ratio of byte access time to unaligned word access is 2.95, unaligned accesses are fast
> [    0.265052] cpu25: Ratio of byte access time to unaligned word access is 3.38, unaligned accesses are fast
> [    0.265055] cpu2: Ratio of byte access time to unaligned word access is 2.88, unaligned accesses are fast
> [    0.265055] cpu3: Ratio of byte access time to unaligned word access is 2.82, unaligned accesses are fast
> [    0.265054] cpu35: Ratio of byte access time to unaligned word access is 3.19, unaligned accesses are fast
> [    0.265051] cpu10: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
> [    0.265054] cpu32: Ratio of byte access time to unaligned word access is 3.26, unaligned accesses are fast
> [    0.265056] cpu29: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
> [    0.265053] cpu56: Ratio of byte access time to unaligned word access is 3.07, unaligned accesses are fast
> [    0.265053] cpu58: Ratio of byte access time to unaligned word access is 2.98, unaligned accesses are fast
> [    0.265055] cpu37: Ratio of byte access time to unaligned word access is 4.56, unaligned accesses are fast
> [    0.265055] cpu4: Ratio of byte access time to unaligned word access is 2.82, unaligned accesses are fast
> [    0.265052] cpu48: Ratio of byte access time to unaligned word access is 3.11, unaligned accesses are fast
> [    0.265055] cpu1: Ratio of byte access time to unaligned word access is 2.80, unaligned accesses are fast
> [    0.265056] cpu7: Ratio of byte access time to unaligned word access is 3.91, unaligned accesses are fast
> [    0.265056] cpu6: Ratio of byte access time to unaligned word access is 4.02, unaligned accesses are fast
> [    0.265055] cpu21: Ratio of byte access time to unaligned word access is 3.07, unaligned accesses are fast
> [    0.265054] cpu13: Ratio of byte access time to unaligned word access is 3.75, unaligned accesses are fast
> [    0.265053] cpu53: Ratio of byte access time to unaligned word access is 2.91, unaligned accesses are fast
> [    0.265056] cpu30: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> [    0.265052] cpu17: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
> [    0.265053] cpu40: Ratio of byte access time to unaligned word access is 3.14, unaligned accesses are fast
> [    0.265054] cpu43: Ratio of byte access time to unaligned word access is 3.26, unaligned accesses are fast
> [    0.265053] cpu42: Ratio of byte access time to unaligned word access is 3.23, unaligned accesses are fast
> [    0.265053] cpu41: Ratio of byte access time to unaligned word access is 3.22, unaligned accesses are fast
> [    0.265054] cpu14: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
> [    0.265051] cpu9: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
> [    0.265052] cpu27: Ratio of byte access time to unaligned word access is 3.42, unaligned accesses are fast
> [    0.265054] cpu34: Ratio of byte access time to unaligned word access is 3.38, unaligned accesses are fast
> [    0.265054] cpu33: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
> [    0.265053] cpu54: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
> [    0.265051] cpu8: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
> [    0.265056] cpu31: Ratio of byte access time to unaligned word access is 3.04, unaligned accesses are fast
> [    0.265055] cpu39: Ratio of byte access time to unaligned word access is 3.22, unaligned accesses are fast
> [    0.265055] cpu38: Ratio of byte access time to unaligned word access is 3.60, unaligned accesses are fast
> [    0.265055] cpu22: Ratio of byte access time to unaligned word access is 3.13, unaligned accesses are fast
> [    0.265054] cpu15: Ratio of byte access time to unaligned word access is 2.88, unaligned accesses are fast
> [    0.265052] cpu49: Ratio of byte access time to unaligned word access is 2.83, unaligned accesses are fast
> [    0.265055] cpu20: Ratio of byte access time to unaligned word access is 3.18, unaligned accesses are fast
> [    0.265053] cpu52: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> [    0.265053] cpu55: Ratio of byte access time to unaligned word access is 2.92, unaligned accesses are fast
> [    0.265052] cpu16: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> [    0.265052] cpu26: Ratio of byte access time to unaligned word access is 3.18, unaligned accesses are fast
> [    0.265052] cpu51: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
> [    0.265055] cpu23: Ratio of byte access time to unaligned word access is 3.07, unaligned accesses are fast
> [    0.265054] cpu12: Ratio of byte access time to unaligned word access is 3.32, unaligned accesses are fast
> [    0.265054] cpu19: Ratio of byte access time to unaligned word access is 2.98, unaligned accesses are fast
> [    0.265052] cpu50: Ratio of byte access time to unaligned word access is 2.80, unaligned accesses are fast
> [    0.265053] cpu59: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> [    0.265053] cpu57: Ratio of byte access time to unaligned word access is 3.06, unaligned accesses are fast
> [    0.265056] cpu28: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
> [    0.265054] cpu18: Ratio of byte access time to unaligned word access is 3.00, unaligned accesses are fast
> [    0.289100] cpu0: Ratio of byte access time to unaligned word access is 5.97, unaligned accesses are fast
> [    0.290415] Serial: LRW UART driver
> [    0.290665] sse: Missing SBI SSE extension
> [    0.311076] sophgo,top-intc 70300102e0.top_intc: is a msi parent
> [    0.327406] HugeTLB: registered 1.00 GiB page size, pre-allocated 0 pages
> [    0.327430] HugeTLB: 0 KiB vmemmap can be freed for a 1.00 GiB page
> [    0.327444] HugeTLB: registered 2.00 MiB page size, pre-allocated 0 pages
> [    0.327455] HugeTLB: 0 KiB vmemmap can be freed for a 2.00 MiB page
> [    0.332494] ACPI: Interpreter disabled.
> [    0.333142] iommu: Default domain type: Translated
> [    0.333161] iommu: DMA domain TLB invalidation policy: strict mode
> [    0.333759] pps_core: LinuxPPS API ver. 1 registered
> [    0.333779] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
> [    0.333804] PTP clock support registered
> [    0.334314] efivars: Registered efivars operations
> [    0.335699] NetLabel: Initializing
> [    0.335723] NetLabel:  domain hash size = 128
> [    0.335734] NetLabel:  protocols = UNLABELED CIPSOv4 CALIPSO
> [    0.335804] NetLabel:  unlabeled traffic allowed by default
> [    0.336150] vgaarb: loaded
> [    0.337190] clocksource: Switched to clocksource riscv_clocksource
> [    0.343385] VFS: Disk quotas dquot_6.6.0
> [    0.343633] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
> [    0.346650] AppArmor: AppArmor Filesystem Enabled
> [    0.346810] pnp: PnP ACPI: disabled
> [    0.358401] NET: Registered PF_INET protocol family
> [    0.359469] IP idents hash table entries: 262144 (order: 9, 2097152 bytes, vmalloc)
> [    0.373312] tcp_listen_portaddr_hash hash table entries: 65536 (order: 8, 1048576 bytes, vmalloc)
> [    0.373987] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, vmalloc)
> [    0.375584] TCP established hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)
> [    0.377485] TCP bind hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
> [    0.378590] TCP: Hash tables configured (established 524288 bind 65536)
> [    0.380288] MPTCP token hash table entries: 65536 (order: 9, 1572864 bytes, vmalloc)
> [    0.382060] UDP hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
> [    0.383229] UDP-Lite hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
> [    0.384259] NET: Registered PF_UNIX/PF_LOCAL protocol family
> [    0.384308] NET: Registered PF_XDP protocol family
> [    0.384333] PCI: CLS 0 bytes, default 64
> [    0.385763] Trying to unpack rootfs image as initramfs...
> [    0.389153] Initialise system trusted keyrings
> [    0.389318] Key type blacklist registered
> [    0.390041] workingset: timestamp_bits=43 max_order=25 bucket_order=0
> [    0.390114] zbud: loaded
> [    0.396835] fuse: init (API version 7.39)
> [    0.399678] integrity: Platform Keyring initialized
> [    0.399734] integrity: Machine keyring initialized
> [    0.399766] Key type asymmetric registered
> [    0.399779] Asymmetric key parser 'x509' registered
> [    3.296324] Freeing initrd memory: 117684K
> [    3.378869] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 246)
> [    3.379281] io scheduler mq-deadline registered
> [    3.391286] pwm_sophgo_probe
> [    3.391850] cdns-pcie-host 7060000000.pcie: host bridge /pcie@7060000000 ranges:
> [    3.391899] cdns-pcie-host 7060000000.pcie:       IO 0x40c0000000..0x40c03fffff -> 0x00c0000000
> [    3.391933] cdns-pcie-host 7060000000.pcie:      MEM 0x40d0000000..0x40dfffffff -> 0x00d0000000
> [    3.391960] cdns-pcie-host 7060000000.pcie:      MEM 0x40e0000000..0x40ffffffff -> 0x00e0000000
> [    3.391982] cdns-pcie-host 7060000000.pcie:      MEM 0x4200000000..0x43ffffffff -> 0x4200000000
> [    3.392002] cdns-pcie-host 7060000000.pcie:      MEM 0x4100000000..0x41ffffffff -> 0x4100000000
> [    3.392031] cdns-pcie-host 7060000000.pcie: Memory resource size exceeds max for 32 bits
> [    3.392084] cdns-pcie-host 7060000000.pcie: no phy-names.  PHY will not be initialized
> [    3.392458] cdns-pcie-host 7060000000.pcie: PCI host bridge to bus 0000:00
> [    3.392480] pci_bus 0000:00: Unknown NUMA node; performance will be reduced
> [    3.392495] pci_bus 0000:00: root bus resource [bus 00-3f]
> [    3.392513] pci_bus 0000:00: root bus resource [io  0x0000-0x3fffff] (bus address [0xc0000000-0xc03fffff])
> [    3.392531] pci_bus 0000:00: root bus resource [mem 0x40d0000000-0x40dfffffff pref] (bus address [0xd0000000-0xdfffffff])
> [    3.392548] pci_bus 0000:00: root bus resource [mem 0x40e0000000-0x40ffffffff] (bus address [0xe0000000-0xffffffff])
> [    3.392562] pci_bus 0000:00: root bus resource [mem 0x4200000000-0x43ffffffff pref]
> [    3.392576] pci_bus 0000:00: root bus resource [mem 0x4100000000-0x41ffffffff]
> [    3.392619] pci 0000:00:00.0: [1e30:2042] type 01 class 0x060400
> [    3.392728] pci 0000:00:00.0: supports D1
> [    3.392744] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
> [    3.395695] pci 0000:01:00.0: [1002:6611] type 00 class 0x030000
> [    3.395758] pci 0000:01:00.0: reg 0x10: [mem 0xc0000000-0xcfffffff 64bit pref]
> [    3.395797] pci 0000:01:00.0: reg 0x18: [mem 0x40d0000000-0x40d003ffff 64bit]
> [    3.395824] pci 0000:01:00.0: reg 0x20: initial BAR value 0x00000000 invalid
> [    3.395837] pci 0000:01:00.0: reg 0x20: [io  size 0x0100]
> [    3.395876] pci 0000:01:00.0: reg 0x30: [mem 0x40fffe0000-0x40ffffffff pref]
> [    3.395899] pci 0000:01:00.0: enabling Extended Tags
> [    3.396031] pci 0000:01:00.0: supports D1 D2
> [    3.396044] pci 0000:01:00.0: PME# supported from D1 D2 D3hot
> [    3.396430] pci 0000:01:00.0: vgaarb: setting as boot VGA device
> [    3.396446] pci 0000:01:00.0: vgaarb: bridge control possible
> [    3.396458] pci 0000:01:00.0: vgaarb: VGA device added: decodes=io+mem,owns=none,locks=none
> [    3.396525] pci 0000:01:00.1: [1002:aab0] type 00 class 0x040300
> [    3.396568] pci 0000:01:00.1: reg 0x10: [mem 0x40d0040000-0x40d0043fff 64bit]
> [    3.396637] pci 0000:01:00.1: enabling Extended Tags
> [    3.396744] pci 0000:01:00.1: supports D1 D2
> [    3.405287] pci_bus 0000:01: busn_res: [bus 01-3f] end is updated to 01
> [    3.405334] pci 0000:00:00.0: BAR 15: assigned [mem 0x4200000000-0x420fffffff 64bit pref]
> [    3.405354] pci 0000:00:00.0: BAR 14: assigned [mem 0x40e0000000-0x40e00fffff]
> [    3.405369] pci 0000:00:00.0: BAR 13: assigned [io  0x1000-0x1fff]
> [    3.405389] pci 0000:01:00.0: BAR 0: assigned [mem 0x4200000000-0x420fffffff 64bit pref]
> [    3.405420] pci 0000:01:00.0: BAR 2: assigned [mem 0x40e0000000-0x40e003ffff 64bit]
> [    3.405449] pci 0000:01:00.0: BAR 6: assigned [mem 0x40e0040000-0x40e005ffff pref]
> [    3.405463] pci 0000:01:00.1: BAR 0: assigned [mem 0x40e0060000-0x40e0063fff 64bit]
> [    3.405490] pci 0000:01:00.0: BAR 4: assigned [io  0x1000-0x10ff]
> [    3.405509] pci 0000:00:00.0: PCI bridge to [bus 01]
> [    3.405521] pci 0000:00:00.0:   bridge window [io  0x1000-0x1fff]
> [    3.405535] pci 0000:00:00.0:   bridge window [mem 0x40e0000000-0x40e00fffff]
> [    3.405549] pci 0000:00:00.0:   bridge window [mem 0x4200000000-0x420fffffff 64bit pref]
> [    3.405980] pcieport 0000:00:00.0: PME: Signaling with IRQ 45
> [    3.406441] pcieport 0000:00:00.0: AER: enabled with IRQ 45
> [    3.406727] pci 0000:01:00.1: D0 power state depends on 0000:01:00.0
> [    3.406972] cdns-pcie-host 7062000000.pcie: host bridge /pcie@7062000000 ranges:
> [    3.407016] cdns-pcie-host 7062000000.pcie:       IO 0x48c0800000..0x48c0bfffff -> 0x00c0800000
> [    3.407047] cdns-pcie-host 7062000000.pcie:      MEM 0x48d0000000..0x48dfffffff -> 0x00d0000000
> [    3.407071] cdns-pcie-host 7062000000.pcie:      MEM 0x48e0000000..0x48ffffffff -> 0x00e0000000
> [    3.407094] cdns-pcie-host 7062000000.pcie:      MEM 0x4900000000..0x49ffffffff -> 0x4900000000
> [    3.407112] cdns-pcie-host 7062000000.pcie:      MEM 0x4a00000000..0x4bffffffff -> 0x4a00000000
> [    3.407163] cdns-pcie-host 7062000000.pcie: Memory resource size exceeds max for 32 bits
> [    3.407217] cdns-pcie-host 7062000000.pcie: no phy-names.  PHY will not be initialized
> [    3.407292] cdns-pcie-host 7062000000.pcie: msi_data is 0xaf000000
> [    3.407605] cdns-pcie-host 7062000000.pcie: PCI host bridge to bus 0001:80
> [    3.407624] pci_bus 0001:80: Unknown NUMA node; performance will be reduced
> [    3.407638] pci_bus 0001:80: root bus resource [bus 80-bf]
> [    3.407653] pci_bus 0001:80: root bus resource [io  0x400000-0x7fffff] (bus address [0xc0800000-0xc0bfffff])
> [    3.407670] pci_bus 0001:80: root bus resource [mem 0x48d0000000-0x48dfffffff pref] (bus address [0xd0000000-0xdfffffff])
> [    3.407687] pci_bus 0001:80: root bus resource [mem 0x48e0000000-0x48ffffffff] (bus address [0xe0000000-0xffffffff])
> [    3.407702] pci_bus 0001:80: root bus resource [mem 0x4900000000-0x49ffffffff]
> [    3.407715] pci_bus 0001:80: root bus resource [mem 0x4a00000000-0x4bffffffff pref]
> [    3.407751] pci 0001:80:00.0: [1e30:2042] type 01 class 0x060400
> [    3.407849] pci 0001:80:00.0: supports D1
> [    3.407863] pci 0001:80:00.0: PME# supported from D0 D1 D3hot
> [    3.410185] pci_bus 0001:81: busn_res: [bus 81-bf] end is updated to 81
> [    3.410219] pci 0001:80:00.0: PCI bridge to [bus 81]
> [    3.410439] cdns-pcie-host 7062000000.pcie: msi#0 address_hi 0x0 address_lo 0xaf000000
> [    3.410588] pcieport 0001:80:00.0: PME: Signaling with IRQ 47
> [    3.411013] pcieport 0001:80:00.0: AER: enabled with IRQ 47
> [    3.411311] cdns-pcie-host 4c00000000.pcie: host bridge /pcie@7062800000 ranges:
> [    3.411355] cdns-pcie-host 4c00000000.pcie:       IO 0x4cc0c00000..0x4cc0ffffff -> 0x00c0c00000
> [    3.411386] cdns-pcie-host 4c00000000.pcie:      MEM 0x4cf8000000..0x4cfbffffff -> 0x00f8000000
> [    3.411411] cdns-pcie-host 4c00000000.pcie:      MEM 0x4cfc000000..0x4cffffffff -> 0x00fc000000
> [    3.411451] cdns-pcie-host 4c00000000.pcie:      MEM 0x4e00000000..0x4fffffffff -> 0x4e00000000
> [    3.411472] cdns-pcie-host 4c00000000.pcie:      MEM 0x4d00000000..0x4dffffffff -> 0x4d00000000
> [    3.411502] cdns-pcie-host 4c00000000.pcie: Memory resource size exceeds max for 32 bits
> [    3.411540] cdns-pcie-host 4c00000000.pcie: no phy-names.  PHY will not be initialized
> [    3.411711] cdns-pcie-host 4c00000000.pcie: PCI host bridge to bus 0002:c0
> [    3.411727] pci_bus 0002:c0: Unknown NUMA node; performance will be reduced
> [    3.411742] pci_bus 0002:c0: root bus resource [bus c0-ff]
> [    3.411756] pci_bus 0002:c0: root bus resource [io  0x800000-0xbfffff] (bus address [0xc0c00000-0xc0ffffff])
> [    3.411772] pci_bus 0002:c0: root bus resource [mem 0x4cf8000000-0x4cfbffffff pref] (bus address [0xf8000000-0xfbffffff])
> [    3.411788] pci_bus 0002:c0: root bus resource [mem 0x4cfc000000-0x4cffffffff] (bus address [0xfc000000-0xffffffff])
> [    3.411803] pci_bus 0002:c0: root bus resource [mem 0x4e00000000-0x4fffffffff pref]
> [    3.411816] pci_bus 0002:c0: root bus resource [mem 0x4d00000000-0x4dffffffff]
> [    3.411850] pci 0002:c0:00.0: [1e30:2042] type 01 class 0x060400
> [    3.411945] pci 0002:c0:00.0: supports D1
> [    3.411958] pci 0002:c0:00.0: PME# supported from D0 D1 D3hot
> [    3.414269] pci 0002:c1:00.0: [1b21:2824] type 01 class 0x060400
> [    3.414382] pci 0002:c1:00.0: enabling Extended Tags
> [    3.414540] pci 0002:c1:00.0: PME# supported from D0 D3hot D3cold
> [    3.425436] pci 0002:c2:00.0: [1b21:2824] type 01 class 0x060400
> [    3.425551] pci 0002:c2:00.0: enabling Extended Tags
> [    3.425713] pci 0002:c2:00.0: PME# supported from D0 D3hot D3cold
> [    3.426443] pci 0002:c2:04.0: [1b21:2824] type 01 class 0x060400
> [    3.426557] pci 0002:c2:04.0: enabling Extended Tags
> [    3.426717] pci 0002:c2:04.0: PME# supported from D0 D3hot D3cold
> [    3.427216] pci 0002:c2:06.0: [1b21:2824] type 01 class 0x060400
> [    3.427325] pci 0002:c2:06.0: enabling Extended Tags
> [    3.427483] pci 0002:c2:06.0: PME# supported from D0 D3hot D3cold
> [    3.427911] pci 0002:c2:07.0: [1b21:2824] type 01 class 0x060400
> [    3.428019] pci 0002:c2:07.0: enabling Extended Tags
> [    3.428176] pci 0002:c2:07.0: PME# supported from D0 D3hot D3cold
> [    3.428579] pci 0002:c2:08.0: [1b21:2824] type 01 class 0x060400
> [    3.428685] pci 0002:c2:08.0: enabling Extended Tags
> [    3.428841] pci 0002:c2:08.0: PME# supported from D0 D3hot D3cold
> [    3.429563] pci 0002:c2:0c.0: [1b21:2824] type 01 class 0x060400
> [    3.429676] pci 0002:c2:0c.0: enabling Extended Tags
> [    3.429837] pci 0002:c2:0c.0: PME# supported from D0 D3hot D3cold
> [    3.430365] pci 0002:c2:0e.0: [1b21:2824] type 01 class 0x060400
> [    3.430475] pci 0002:c2:0e.0: enabling Extended Tags
> [    3.430634] pci 0002:c2:0e.0: PME# supported from D0 D3hot D3cold
> [    3.431059] pci 0002:c2:0f.0: [1b21:2824] type 01 class 0x060400
> [    3.431165] pci 0002:c2:0f.0: enabling Extended Tags
> [    3.431322] pci 0002:c2:0f.0: PME# supported from D0 D3hot D3cold
> [    3.432977] pci_bus 0002:c3: busn_res: [bus c3-ff] end is updated to c3
> [    3.433313] pci 0002:c4:00.0: [1b21:2142] type 00 class 0x0c0330
> [    3.433374] pci 0002:c4:00.0: reg 0x10: [mem 0xc0500000-0xc0507fff 64bit]
> [    3.433470] pci 0002:c4:00.0: enabling Extended Tags
> [    3.433648] pci 0002:c4:00.0: PME# supported from D0 D3hot D3cold
> [    3.445242] pci_bus 0002:c4: busn_res: [bus c4-ff] end is updated to c4
> [    3.445447] pci 0002:c5:00.0: [10ec:8125] type 00 class 0x020000
> [    3.445493] pci 0002:c5:00.0: reg 0x10: [io  0xc02000-0xc020ff]
> [    3.445544] pci 0002:c5:00.0: reg 0x18: [mem 0xc0400000-0xc040ffff 64bit]
> [    3.445581] pci 0002:c5:00.0: reg 0x20: [mem 0xc0410000-0xc0413fff 64bit]
> [    3.445820] pci 0002:c5:00.0: supports D1 D2
> [    3.445833] pci 0002:c5:00.0: PME# supported from D0 D1 D2 D3hot D3cold
> [    3.457248] pci_bus 0002:c5: busn_res: [bus c5-ff] end is updated to c5
> [    3.457460] pci 0002:c6:00.0: [1106:3483] type 00 class 0x0c0330
> [    3.457514] pci 0002:c6:00.0: reg 0x10: [mem 0xc0300000-0xc0300fff 64bit]
> [    3.457697] pci 0002:c6:00.0: PME# supported from D0 D3hot D3cold
> [    3.458042] pci_bus 0002:c6: busn_res: [bus c6-ff] end is updated to c6
> [    3.458236] pci 0002:c7:00.0: [1bb1:5027] type 00 class 0x010802
> [    3.458314] pci 0002:c7:00.0: reg 0x10: [mem 0xc0200000-0xc0203fff 64bit]
> [    3.459034] pci 0002:c7:00.0: 31.504 Gb/s available PCIe bandwidth, limited by 8.0 GT/s PCIe x4 link at 0002:c2:08.0 (capable of 63.012 Gb/s with 16.0 GT/s PCIe x4 link)
> [    3.469236] pci_bus 0002:c7: busn_res: [bus c7-ff] end is updated to c7
> [    3.469427] pci 0002:c8:00.0: [197b:0585] type 00 class 0x010601
> [    3.469477] pci 0002:c8:00.0: reg 0x10: [io  0xc01200-0xc0127f]
> [    3.469508] pci 0002:c8:00.0: reg 0x14: [io  0xc01180-0xc011ff]
> [    3.469538] pci 0002:c8:00.0: reg 0x18: [io  0xc01100-0xc0117f]
> [    3.469568] pci 0002:c8:00.0: reg 0x1c: [io  0xc01080-0xc010ff]
> [    3.469597] pci 0002:c8:00.0: reg 0x20: [io  0xc01000-0xc0107f]
> [    3.469626] pci 0002:c8:00.0: reg 0x24: [mem 0xc0100000-0xc0101fff]
> [    3.469656] pci 0002:c8:00.0: reg 0x30: [mem 0x4cffff0000-0x4cffffffff pref]
> [    3.469837] pci 0002:c8:00.0: PME# supported from D3hot
> [    3.470310] pci_bus 0002:c8: busn_res: [bus c8-ff] end is updated to c8
> [    3.470513] pci 0002:c9:00.0: [10ec:8125] type 00 class 0x020000
> [    3.470558] pci 0002:c9:00.0: reg 0x10: [io  0xc00000-0xc000ff]
> [    3.470609] pci 0002:c9:00.0: reg 0x18: [mem 0xc0000000-0xc000ffff 64bit]
> [    3.470646] pci 0002:c9:00.0: reg 0x20: [mem 0xc0010000-0xc0013fff 64bit]
> [    3.470881] pci 0002:c9:00.0: supports D1 D2
> [    3.470893] pci 0002:c9:00.0: PME# supported from D0 D1 D2 D3hot D3cold
> [    3.481236] pci_bus 0002:c9: busn_res: [bus c9-ff] end is updated to c9
> [    3.481585] pci_bus 0002:ca: busn_res: [bus ca-ff] end is updated to ca
> [    3.481612] pci_bus 0002:c2: busn_res: [bus c2-ff] end is updated to ca
> [    3.481631] pci_bus 0002:c1: busn_res: [bus c1-ff] end is updated to ca
> [    3.481676] pci 0002:c0:00.0: BAR 14: assigned [mem 0x4cfc000000-0x4cfc5fffff]
> [    3.481694] pci 0002:c0:00.0: BAR 13: assigned [io  0x800000-0x802fff]
> [    3.481712] pci 0002:c1:00.0: BAR 14: assigned [mem 0x4cfc000000-0x4cfc5fffff]
> [    3.481726] pci 0002:c1:00.0: BAR 13: assigned [io  0x800000-0x802fff]
> [    3.481746] pci 0002:c2:04.0: BAR 14: assigned [mem 0x4cfc000000-0x4cfc0fffff]
> [    3.481761] pci 0002:c2:06.0: BAR 14: assigned [mem 0x4cfc100000-0x4cfc1fffff]
> [    3.481775] pci 0002:c2:07.0: BAR 14: assigned [mem 0x4cfc200000-0x4cfc2fffff]
> [    3.481789] pci 0002:c2:08.0: BAR 14: assigned [mem 0x4cfc300000-0x4cfc3fffff]
> [    3.481802] pci 0002:c2:0c.0: BAR 14: assigned [mem 0x4cfc400000-0x4cfc4fffff]
> [    3.481816] pci 0002:c2:0e.0: BAR 14: assigned [mem 0x4cfc500000-0x4cfc5fffff]
> [    3.481829] pci 0002:c2:06.0: BAR 13: assigned [io  0x800000-0x800fff]
> [    3.481842] pci 0002:c2:0c.0: BAR 13: assigned [io  0x801000-0x801fff]
> [    3.481854] pci 0002:c2:0e.0: BAR 13: assigned [io  0x802000-0x802fff]
> [    3.481868] pci 0002:c2:00.0: PCI bridge to [bus c3]
> [    3.481902] pci 0002:c4:00.0: BAR 0: assigned [mem 0x4cfc000000-0x4cfc007fff 64bit]
> [    3.481937] pci 0002:c2:04.0: PCI bridge to [bus c4]
> [    3.481954] pci 0002:c2:04.0:   bridge window [mem 0x4cfc000000-0x4cfc0fffff]
> [    3.481982] pci 0002:c5:00.0: BAR 2: assigned [mem 0x4cfc100000-0x4cfc10ffff 64bit]
> [    3.482017] pci 0002:c5:00.0: BAR 4: assigned [mem 0x4cfc110000-0x4cfc113fff 64bit]
> [    3.482050] pci 0002:c5:00.0: BAR 0: assigned [io  0x800000-0x8000ff]
> [    3.482069] pci 0002:c2:06.0: PCI bridge to [bus c5]
> [    3.482082] pci 0002:c2:06.0:   bridge window [io  0x800000-0x800fff]
> [    3.482099] pci 0002:c2:06.0:   bridge window [mem 0x4cfc100000-0x4cfc1fffff]
> [    3.482125] pci 0002:c6:00.0: BAR 0: assigned [mem 0x4cfc200000-0x4cfc200fff 64bit]
> [    3.482158] pci 0002:c2:07.0: PCI bridge to [bus c6]
> [    3.482174] pci 0002:c2:07.0:   bridge window [mem 0x4cfc200000-0x4cfc2fffff]
> [    3.482200] pci 0002:c7:00.0: BAR 0: assigned [mem 0x4cfc300000-0x4cfc303fff 64bit]
> [    3.482240] pci 0002:c2:08.0: PCI bridge to [bus c7]
> [    3.482257] pci 0002:c2:08.0:   bridge window [mem 0x4cfc300000-0x4cfc3fffff]
> [    3.482284] pci 0002:c8:00.0: BAR 6: assigned [mem 0x4cfc400000-0x4cfc40ffff pref]
> [    3.482299] pci 0002:c8:00.0: BAR 5: assigned [mem 0x4cfc410000-0x4cfc411fff]
> [    3.482317] pci 0002:c8:00.0: BAR 0: assigned [io  0x801000-0x80107f]
> [    3.482334] pci 0002:c8:00.0: BAR 1: assigned [io  0x801080-0x8010ff]
> [    3.482351] pci 0002:c8:00.0: BAR 2: assigned [io  0x801100-0x80117f]
> [    3.482368] pci 0002:c8:00.0: BAR 3: assigned [io  0x801180-0x8011ff]
> [    3.482385] pci 0002:c8:00.0: BAR 4: assigned [io  0x801200-0x80127f]
> [    3.482403] pci 0002:c2:0c.0: PCI bridge to [bus c8]
> [    3.482416] pci 0002:c2:0c.0:   bridge window [io  0x801000-0x801fff]
> [    3.482433] pci 0002:c2:0c.0:   bridge window [mem 0x4cfc400000-0x4cfc4fffff]
> [    3.482459] pci 0002:c9:00.0: BAR 2: assigned [mem 0x4cfc500000-0x4cfc50ffff 64bit]
> [    3.482492] pci 0002:c9:00.0: BAR 4: assigned [mem 0x4cfc510000-0x4cfc513fff 64bit]
> [    3.482525] pci 0002:c9:00.0: BAR 0: assigned [io  0x802000-0x8020ff]
> [    3.482543] pci 0002:c2:0e.0: PCI bridge to [bus c9]
> [    3.482556] pci 0002:c2:0e.0:   bridge window [io  0x802000-0x802fff]
> [    3.482573] pci 0002:c2:0e.0:   bridge window [mem 0x4cfc500000-0x4cfc5fffff]
> [    3.482597] pci 0002:c2:0f.0: PCI bridge to [bus ca]
> [    3.482626] pci 0002:c1:00.0: PCI bridge to [bus c2-ca]
> [    3.482638] pci 0002:c1:00.0:   bridge window [io  0x800000-0x802fff]
> [    3.482656] pci 0002:c1:00.0:   bridge window [mem 0x4cfc000000-0x4cfc5fffff]
> [    3.482680] pci 0002:c0:00.0: PCI bridge to [bus c1-ca]
> [    3.482691] pci 0002:c0:00.0:   bridge window [io  0x800000-0x802fff]
> [    3.482704] pci 0002:c0:00.0:   bridge window [mem 0x4cfc000000-0x4cfc5fffff]
> [    3.483107] pcieport 0002:c0:00.0: PME: Signaling with IRQ 48
> [    3.483596] pcieport 0002:c0:00.0: AER: enabled with IRQ 48
> [    3.487131] pci 0002:c4:00.0: PME# does not work under D0, disabling it
> [    3.487164] pci 0002:c4:00.0: enabling device (0000 -> 0002)
> [    3.487259] pci 0002:c6:00.0: enabling device (0000 -> 0002)
> [    3.488568] EINJ: ACPI disabled.
> [    3.488589] ERST DBG: ERST support is disabled.
> [    3.492343] no vdmabuf_reserved_memory node
> [    3.492365] virtio-vdmabuf: carveout buf not setup -22
> [    3.493828] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
> [    3.496550] printk: console [ttyS0] disabled
> [    3.496941] 7040000000.serial: ttyS0 at MMIO 0x7040000000 (irq = 57, base_baud = 31250000) is a 16550A
> [    3.497008] printk: console [ttyS0] enabled
> [    6.653616] 7040001000.serial: ttyS1 at MMIO 0x7040001000 (irq = 58, base_baud = 31250000) is a 16550A
> [    6.664291] 7040002000.serial: ttyS2 at MMIO 0x7040002000 (irq = 59, base_baud = 31250000) is a 16550A
> [    6.674993] 7040003000.serial: ttyS3 at MMIO 0x7040003000 (irq = 60, base_baud = 31250000) is a 16550A
> [    6.691432] nvme nvme0: pci function 0002:c7:00.0
> [    6.693487] mousedev: PS/2 mouse device common for all mice
> [    6.703782] sdhci: Secure Digital Host Controller Interface driver
> [    6.710021] sdhci: Copyright(c) Pierre Ossman
> [    6.711847] hwmon hwmon0: temp1_input not attached to any thermal zone
> [    6.714740] sdhci-pltfm: SDHCI platform and OF driver helper
> [    6.721065] hwmon hwmon0: temp2_input not attached to any thermal zone
> [    6.737204] ledtrig-cpu: registered to indicate activity on CPUs
> [    6.743578] pstore: Using crash dump compression: deflate
> [    6.749064] pstore: Registered efi_pstore as persistent store backend
> [    6.756324] riscv-pmu-sbi: SBI PMU extension is available
> [    6.761974] riscv-pmu-sbi: 16 firmware and 31 hardware counters
> [    6.774971] NET: Registered PF_INET6 protocol family
> [    6.775258] nvme nvme0: allocated 64 MiB host memory buffer.
> [    6.792744] nvme nvme0: 1/0/0 default/read/poll queues
> [    6.798818] Segment Routing with IPv6
> [    6.802615] In-situ OAM (IOAM) with IPv6
> [    6.806651] mip6: Mobile IPv6
> [    6.809657] NET: Registered PF_PACKET protocol family
> [    6.814951] mpls_gso: MPLS GSO support
> [    6.826385] registered taskstats version 1
> [    6.828554]  nvme0n1: p1 p2 p3
> [    6.832483] Loading compiled-in X.509 certificates
> [    6.881423] Loaded X.509 cert 'Build time autogenerated kernel key: a949a38ba7402beaa827889ff304b05fc9df7c05'
> [    6.910444] Key type .fscrypt registered
> [    6.914452] Key type fscrypt-provisioning registered
> [    6.931636] Key type encrypted registered
> [    6.935707] AppArmor: AppArmor sha1 policy hashing enabled
> [    6.941498] ima: No TPM chip found, activating TPM-bypass!
> [    6.947038] ima: Allocated hash algorithm: sha256
> [    6.951806] ima: No architecture policies found
> [    6.956459] evm: Initialising EVM extended attributes:
> [    6.961618] evm: security.selinux
> [    6.964937] evm: security.SMACK64 (disabled)
> [    6.969217] evm: security.SMACK64EXEC (disabled)
> [    6.973848] evm: security.SMACK64TRANSMUTE (disabled)
> [    6.978909] evm: security.SMACK64MMAP (disabled)
> [    6.983536] evm: security.apparmor
> [    6.986948] evm: security.ima
> [    6.989927] evm: security.capability
> [    6.993513] evm: HMAC attrs: 0x1
> [    7.247426] clk: Disabling unused clocks
> [    7.256860] Freeing unused kernel image (initmem) memory: 2712K
> [   10.882016] r8169 0002:c9:00.0 eth1: RTL8125B, 00:e0:4c:68:02:e6, XID 641, IRQ 68
> 1;-1f[   10.882032] r8169 0002:c9:00.0 eth1: jumbo features [frames: 9194 bytes, tx checksumming: ko]
> [   10.889827] xhci_hcd 0002:c4:00.0: xHCI Host Controller
> [   10.891369] r8169 0002:c5:00.0 enP2p197s0: renamed from eth0
> [   10.896488] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   10.904233] xhci_hcd 0002:c4:00.0: new USB bus registered, assigned bus number 2
> [   10.904253] xhci_hcd 0002:c4:00.0: Host supports USB 3.1 Enhanced SuperSpeed
> [   10.905580] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   10.913690] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.06
> [   10.962246] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> [   10.962253] usb usb1: Product: xHCI Host Controller
> [   10.962257] usb usb1: Manufacturer: Linux 6.6.127+ xhci-hcd
> [   10.962261] usb usb1: SerialNumber: 0002:c4:00.0
> [   10.962987] hub 1-0:1.0: USB hub found
> [   10.988466] hub 1-0:1.0: 2 ports detected
> [   10.989373] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   10.991053] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
> [   10.991187] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.06
> [   10.991197] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> [   10.991204] usb usb2: Product: xHCI Host Controller
> [   10.991208] usb usb2: Manufacturer: Linux 6.6.127+ xhci-hcd
> [   10.991212] usb usb2: SerialNumber: 0002:c4:00.0
> [   10.991915] hub 2-0:1.0: USB hub found
> [   10.991958] hub 2-0:1.0: 2 ports detected
> [   10.992696] xhci_hcd 0002:c6:00.0: xHCI Host Controller
> [   11.001456] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   11.008198] xhci_hcd 0002:c6:00.0: new USB bus registered, assigned bus number 3
> [   11.016938] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [  OK  ] Finished dracut initqueue hook.
> [  OK  ] Found device Seagate ZP2048CM30003 oERV.
> [  OK  ] Reached target Initrd Root Device.
> [  OK  ] Reached target Preparation for Remote File Systems.
> [  OK  ] Reached target Remote File Systems.
>          Starting dracut pre-mount hook...
> [  OK  ] Started Show Plymouth Boot Screen.
> [  OK  ] Started Forward Password Requests to Plymouth Directory Watch.
> [  OK  ] Reached target Path Units.
> [  OK  ] Reached target Basic System.
> [  OK  ] Stopped Virtual Console Setup.
>          Stopping Virtual Console Setup...
>          Starting Virtual Console Setup...
> [  OK  ] Finished dracut pre-mount hook.
>          Starting File System Check on /dev/nvme0n1p3...
> [   11.245223] usb 1-1: new high-speed USB device number 2 using xhci_hcd
> [  OK  ] Finished File System Check on /dev/nvme0n1p3.
>          Mounting /sysroot...
> [   11.385246] EXT4-fs (nvme0n1p3): mounted filesystem 07617bd8-13da-4749-97a3-2b548687b739 ro with ordered data mode. Quota mode: none.
> [   11.400683] usb 1-1: New USB device found, idVendor=2109, idProduct=2822, bcdDevice= 7.94
> [   11.408909] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [   11.408916] usb 1-1: Product: USB2.0 Hub             
> [  OK  ] Mounted    11.408921] usb 1-1: Manufacturer: VIA Labs, Inc.         
> 1;39m/sysroot.
> [   11.408925] usb 1-1: SerialNumber: 000000001
> [   11.414710] hub 1-1:1.0: USB hub found
> [   11.439385] hub 1-1:1.0: 4 ports detected
> [  OK  ] Reached target Initrd Root File System.
>          Starting Mountpoints Configured in the Real Root...
> [  OK  ] Finished Mountpoints Configured in the Real Root.
> [  OK  ] Reached target    11.542161] usb 2-1: new SuperSpeed USB device number 2 using xhci_hcd
> mInitrd File Systems.
> [  OK  ] Reached target Initrd Default Target.
>          Starting dracut pre-pivot and cleanup hook...
> [   11.573510] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   11.581589] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   11.674720] scsi host0: ahci
> [   11.678766] xhci_hcd 0002:c6:00.0: hcc params 0x002841eb hci version 0x100 quirks 0x0000200000000890
> [   11.679164] scsi host1: ahci
> [   11.689257] xhci_hcd 0002:c6:00.0: xHCI Host Controller
> [   11.692134] scsi host2: ahci
> [   11.696523] xhci_hcd 0002:c6:00.0: new USB bus registered, assigned bus number 4
> [   11.701654] scsi host3: ahci
> [   11.702289] r8169 0002:c9:00.0 enP2p201s0: renamed from eth1
> [   11.705361] [drm] radeon kernel modesetting enabled.
> [   11.705529] radeon 0000:01:00.0: vgaarb: deactivate vga console
> [   11.706618] xhci_hcd 0002:c6:00.0: Host supports USB 3.0 SuperSpeed
> [   11.710666] scsi host4: ahci
> [   11.715888] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.06
> [   11.721238] ata1: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410100 irq 66
> [   11.726370] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> [   11.726394] ata2: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410180 irq 66
> [   11.726410] usb usb3: Product: xHCI Host Controller
> [   11.726426] ata3: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410200 irq 66
> [   11.726437] usb usb3: Manufacturer: Linux 6.6.127+ xhci-hcd
> [   11.726451] ata4: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410280 irq 66
> [   11.726460] usb usb3: SerialNumber: 0002:c6:00.0
> [   11.726472] ata5: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410300 irq 66
> [   11.727467] hub 3-0:1.0: USB hub found
> [   11.735813] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   11.744126] hub 3-0:1.0: 1 port detected
> [   11.752345] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   11.760122] usb usb4: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.06
> [   11.768558] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   11.771859] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> [   11.771870] usb usb4: Product: xHCI Host Controller
> [   11.771876] usb usb4: Manufacturer: Linux 6.6.127+ xhci-hcd
> [   11.772432] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   11.779686] usb usb4: SerialNumber: 0002:c6:00.0
> [   11.874317] radeon 0000:01:00.0: enabling device (0006 -> 0007)
> [   11.874856] hub 4-0:1.0: USB hub found
> [   11.880999] [drm] initializing kernel modesetting (OLAND 0x1002:0x6611 0x1642:0x1601 0x87).
> [   11.884201] hub 4-0:1.0: 4 ports detected
> [   11.898907] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   11.906904] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   11.920679] usb 2-1: New USB device found, idVendor=2109, idProduct=0822, bcdDevice= 7.94
> [   11.928938] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [   11.936115] usb 2-1: Product: USB3.1 Hub             
> [   11.941209] usb 2-1: Manufacturer: VIA Labs, Inc.         
> [   11.946728] usb 2-1: SerialNumber: 000000001
> [   11.957650] hub 2-1:1.0: USB hub found
> [   11.961924] hub 2-1:1.0: 4 ports detected
> [   12.041196] usb 1-2: new high-speed USB device number 3 using xhci_hcd
> [   12.047693] ata1: SATA link down (SStatus 0 SControl 300)
> [  OK  ] Finished Virtual Console Setup.
> [   12.072425] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   12.080726] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   12.196393] usb 1-2: New USB device found, idVendor=2109, idProduct=2822, bcdDevice= 7.94
> [   12.204612] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [   12.211783] usb 1-2: Product: USB2.0 Hub             
> [   12.211882] ATOM BIOS: C57701
> [   12.216863] usb 1-2: Manufacturer: VIA Labs, Inc.         
> [   12.216871] usb 1-2: SerialNumber: 000000001
> [   12.223839] hub 1-2:1.0: USB hub found
> [   12.225548] radeon 0000:01:00.0: VRAM: 2048M 0x0000000000000000 - 0x000000007FFFFFFF (2048M used)
> [   12.229807] hub 1-2:1.0: 4 ports detected
> [   12.233471] radeon 0000:01:00.0: GTT: 2048M 0x0000000080000000 - 0x00000000FFFFFFFF
> [   12.233479] [drm] Detected VRAM RAM=2048M, BAR=256M
> [   12.233484] [drm] RAM width 64bits DDR
> [   12.233996] [drm] radeon: 2048M of VRAM memory ready
> [   12.267754] [drm] radeon: 2048M of GTT memory ready.
> [   12.272791] [drm] Loading oland Microcode
> [   12.279651] [drm] Internal thermal controller with fan control
> [   12.296355] [drm] radeon: dpm initialized
> [   12.304205] [drm] GART: num cpu pages 524288, num gpu pages 524288
> [   12.329186] usb 1-1.4: new full-speed USB device number 4 using xhci_hcd
> [   12.345770] [drm] PCIE GART of 2048M enabled (table at 0x0000000000165000).
> [   12.352936] radeon 0000:01:00.0: WB enabled
> [   12.357188] radeon 0000:01:00.0: fence driver on ring 0 use gpu addr 0x0000000080000c00
> [   12.357196] usb 3-1: new high-speed USB device number 2 using xhci_hcd
> [   12.365218] radeon 0000:01:00.0: fence driver on ring 1 use gpu addr 0x0000000080000c04
> [   12.365225] radeon 0000:01:00.0: fence driver on ring 2 use gpu addr 0x0000000080000c08
> [   12.365230] radeon 0000:01:00.0: fence driver on ring 3 use gpu addr 0x0000000080000c0c
> [   12.365234] radeon 0000:01:00.0: fence driver on ring 4 use gpu addr 0x0000000080000c10
> [   12.366896] radeon 0000:01:00.0: fence driver on ring 5 use gpu addr 0x0000000000075a18
> [   12.367665] ata2: SATA link down (SStatus 0 SControl 300)
> [   12.373928] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   12.380499] radeon 0000:01:00.0: radeon: using MSI.
> [   12.388370] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   12.396048] [drm] radeon: irq initialized.
> [   12.522840] usb 3-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.20
> [   12.531066] usb 3-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
> [   12.538240] usb 3-1: Product: USB2.0 Hub
> [   12.577094] usb 1-1.4: New USB device found, idVendor=09da, idProduct=fa10, bcdDevice= 0.77
> [   12.585483] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
> [   12.592826] usb 1-1.4: Product: USB Device 
> [   12.596623] [drm] ring test on 0 succeeded in 1 usecs
> [   12.597042] usb 1-1.4: Manufacturer: COMPANY 
> [   12.602114] [drm] ring test on 1 succeeded in 1 usecs
> [   12.607827] hub 3-1:1.0: USB hub found
> [   12.611593] [drm] ring test on 2 succeeded in 1 usecs
> [   12.611606] [drm] ring test on 3 succeeded in 3 usecs
> [   12.611781] hub 3-1:1.0: 4 ports detected
> [   12.615402] [drm] ring test on 4 succeeded in 3 usecs
> [   12.625523] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   12.642608] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   12.651342] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   12.683753] ata3: SATA link down (SStatus 0 SControl 300)
> [   12.701892] usb 2-2: new SuperSpeed USB device number 3 using xhci_hcd
> [   12.762424] usb 2-2: New USB device found, idVendor=2109, idProduct=0822, bcdDevice= 7.94
> [   12.770630] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [   12.777807] usb 2-2: Product: USB3.1 Hub             
> [   12.782919] usb 2-2: Manufacturer: VIA Labs, Inc.         
> [   12.788437] usb 2-2: SerialNumber: 000000001
> [   12.792537] [drm] ring test on 5 succeeded in 2 usecs
> [   12.797806] [drm] UVD initialized successfully.
> [   12.800383] hub 2-2:1.0: USB hub found
> [   12.802695] [drm] ib test on ring 0 succeeded in 0 usecs
> [   12.806694] hub 2-2:1.0: 4 ports detected
> [   12.811543] [drm] ib test on ring 1 succeeded in 0 usecs
> [   12.811580] [drm] ib test on ring 2 succeeded in 0 usecs
> [   12.826254] [drm] ib test on ring 3 succeeded in 0 usecs
> [   12.831620] [drm] ib test on ring 4 succeeded in 0 usecs
> [   12.921074] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   12.930025] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   13.003736] ata4: SATA link down (SStatus 0 SControl 300)
> [   13.323673] ata5: SATA link down (SStatus 0 SControl 300)
> [   13.416500] hid: raw HID events driver (C) Jiri Kosina
> [   13.434630] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   13.443852] usbcore: registered new interface driver usbhid
> [   13.449517] usbhid: USB HID core driver
> [   13.451652] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   13.461802] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   13.470927] input: COMPANY  USB Device  as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:09DA:FA10.0001/input/input32
> [   13.497319] [drm] ib test on ring 5 succeeded
> [   13.503488] [drm] Radeon Display Connectors
> [   13.507749] [drm] Connector 0:
> [   13.510849] [drm]   HDMI-A-1
> [   13.513757] [drm]   HPD2
> [   13.516294] [drm]   DDC: 0x6530 0x6530 0x6534 0x6534 0x6538 0x6538 0x653c 0x653c
> [   13.523720] [drm]   Encoders:
> [   13.526712] [drm]     DFP1: INTERNAL_UNIPHY
> [   13.530918] [drm] Connector 1:
> [   13.533995] [drm]   VGA-1
> [   13.536618] [drm]   DDC: 0x65c0 0x65c0 0x65c4 0x65c4 0x65c8 0x65c8 0x65cc 0x65cc
> [   13.544033] [drm]   Encoders:
> [   13.547022] [drm]     CRT1: INTERNAL_KLDSCP_DAC1
> [   13.552882] [drm] Initialized radeon 2.50.0 20080528 for 0000:01:00.0 on minor 0
> [   13.649535] [drm] fb mappable at 0x4200571000
> [   13.653933] [drm] vram apper at 0x4200000000
> [   13.658245] [drm] size 8294400
> [   13.661326] [drm] fb depth is 24
> [   13.664557] [drm]    pitch is 7680
> [   13.821511] hid-generic 0003:09DA:FA10.0001: input,hidraw0: USB HID v1.11 Keyboard [COMPANY  USB Device ] on usb-0002:c4:00.0-1.4/input0
> [   13.822032] input: COMPANY  USB Device  as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.1/0003:09DA:FA10.0002/input/input33
> [   13.823145] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   13.823500] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   13.824169] hid-generic 0003:09DA:FA10.0002: input,hidraw1: USB HID v1.11 Mouse [COMPANY  USB Device ] on usb-0002:c4:00.0-1.4/input1
> [   13.824963] input: COMPANY  USB Device  Keyboard as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.2/0003:09DA:FA10.0003/input/input36
> [   13.826076] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   13.826385] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   13.828024] Console: switching to colour frame buffer device 240x67
> [   13.885382] input: COMPANY  USB Device  as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.2/0003:09DA:FA10.0003/input/input37
> [   13.885475] radeon 0000:01:00.0: [drm] fb0: radeondrmfb frame buffer device
> [   13.886262] hid-generic 0003:09DA:FA10.0003: input,hiddev0,hidraw2: USB HID v1.11 Keyboard [COMPANY  USB Device ] on usb-0002:c4:00.0-1.4/input2
> [   13.976925] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [  OK  ] Stopped    13.986432] gpio-keys soc:gpio-restart: there is not valid maps for state default
> 1;39mVirtual Console Setup.
>          Stopping Vir[   13.999301] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> tual Console Setup...
> [   14.009787] gpio-keys soc:gpio-restart: there is not valid maps for state default
>          Starting Virtual Console Setup...
> [  OK  ] Finished Virtual Console Setup.
> [   32.115772] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   32.124451] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   32.162575] platform soc:gpio-poweroff: deferred probe pending
> [   32.168564] platform soc:gpio-restart: deferred probe pending
> [   32.174460] platform 704002a000.bm-emmc: deferred probe pending
> [   32.180526] platform 704002b000.bm-sd: deferred probe pending
> [   32.186415] platform 7030005000.i2c: deferred probe pending
> [   32.192119] platform 7030006000.i2c: deferred probe pending
> [   32.197825] platform 7030007000.i2c: deferred probe pending
> [   32.203524] platform 7030008000.i2c: deferred probe pending
> [   32.210850] [drm] amdgpu kernel modesetting enabled.
> [  OK  ] Finished dracut pre-pivot and cleanup hook.
>          Starting Cleaning Up and Shutting Down Daemons...
> [  OK  ] Stopped target Timer Units.
> [  OK  ] Stopped dracut pre-pivot and cleanup hook.
> [  OK  ] Stopped target Initrd Default Target.
> [  OK  ] Stopped target Basic System.
> [  OK  ] Stopped target Initrd Root Device.
> [  OK  ] Stopped target Initrd /usr File System.
> [  OK  ] Stopped target Path Units.
> [  OK  ] Stopped target Remote File Systems.
> [  OK  ] Stopped target Preparation for Remote File Systems.
> [  OK  ] Stopped target Slice Units.
> [  OK  ] Stopped target Socket Units.
> [  OK  ] Stopped target System Initialization.
> [  OK  ] Stopped target Swaps.
> [  OK  ] Stopped dracut pre-mount hook.
> [  OK  ] Stopped dracut initqueue hook.
> [  OK  ] Stopped Create List of Static Device Nodes.
>          Starting Plymouth switch root service...
> [  OK  ] Stopped Apply Kernel Variables.
> [  OK  ] Stopped Create Volatile Files and Directories.
> [  OK  ] Stopped target Local File Systems.
> [  OK  ] Stopped target Preparation for Local File Systems.
> [  OK  ] Stopped Coldplug All udev Devices.
> [  OK  ] Stopped dracut pre-trigger hook.
>          Stopping Rule-based Manager for Device Events and Files...
> [  OK  ] Finished Cleaning Up and Shutting Down Daemons.
> [  OK  ] Finished Plymouth switch root service.
> [  OK  ] Stopped Rule-based Manager for Device Events and Files.
> [  OK  ] Closed udev Control Socket.
> [  OK  ] Closed udev Kernel Socket.
> [  OK  ] Stopped dracut pre-udev hook.
> [  OK  ] Stopped dracut cmdline hook.
>          Starting Cleanup udev Database...
> [  OK  ] Stopped Create Static Device Nodes in /dev.
> [  OK  ] Finished Cleanup udev Database.
> [  OK  ] Reached target Switch Root.
>          Starting Switch Root...
> [   33.209267] systemd-journald[606]: Received SIGTERM from PID 1 (systemd).
> [   33.620485] systemd[1]: systemd v255-34.oe2403sp1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA -SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDIS)
> [   33.664117] systemd[1]: Detected architecture riscv64.
> 
> Welcome to openEuler 24.03 (LTS-SP1)!
> 
> [   33.680609] systemd[1]: Hostname set to <openeuler-riscv64>.
> [   34.006662] systemd[1]: /usr/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file acc.
> [   34.460534] systemd[1]: initrd-switch-root.service: Deactivated successfully.
> [   34.474062] systemd[1]: Stopped Switch Root.
> [   34.487965] systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 1.
> [  OK  ] Stopped Switch Root.
> [   34.505914] systemd[1]: Created slice Slice /system/getty.
> [  OK  ] Created slice Slice /system/getty.
> [   34.518916] systemd[1]: Created slice Slice /system/modprobe.
> [  OK  ] Created slice Slice /system/modprobe.
> [   34.532925] systemd[1]: Created slice Slice /system/serial-getty.
> [  OK  ] Created slice Slice /system/serial-getty.
> [   34.547392] systemd[1]: Created slice Slice /system/sshd-keygen.
> [  OK  ] Created slice Slice /system/sshd-keygen.
> [   34.561592] systemd[1]: Created slice User and Session Slice.
> [  OK  ] Created slice User and Session Slice.
> [   34.573784] systemd[1]: Dispatch Password Requests to Console Directory Watch was skipped because of an unmet condition check (ConditionPathExists=!/run/plymouth/pid).
> [   34.574193] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
> [  OK  ] Started Forward Password Requests to Wall Directory Watch.
> [   34.610316] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
> [  OK  ] Set up automount Arbitrary Executable File Formats File System Automount Point.
> [   34.628480] systemd[1]: Stopped target Switch Root.
> [  OK  ] Stopped target Switch Root.
> [   34.643364] systemd[1]: Stopped target Initrd File Systems.
> [  OK  ] Stopped target Initrd File Systems.
> [   34.658685] systemd[1]: Stopped target Initrd Root File System.
> [   34.674425] systemd[1]: Reached target Path Units.
> [  OK  ] Stopped target Initrd Root File System.
> [   34.684328] systemd[1]: Reached target rpc_pipefs.target.
> [  OK  ] Reached target Path Units.
> [   34.699508] systemd[1]: Reached target Slice Units.
> [  OK  ] Reached target rpc_pipefs.target.
> [   34.714393] systemd[1]: Reached target Swaps.
> [  OK  ] Reached target Slice Units.
> [  OK  ] Reached target Swaps.
> [   34.729511] systemd[1]: Listening on Device-mapper event daemon FIFOs.
> [   34.749456] systemd[1]: Listening on LVM2 poll daemon socket.
> [  OK  ] Listening on Device-mapper event daemon FIFOs.
> [   34.763014] systemd[1]: Listening on RPCbind Server Activation Socket.
> [  OK  ] Listening on LVM2 poll daemon socket.
> [   34.779158] systemd[1]: Reached target RPC Port Mapper.
> [  OK  ] Listening on RPCbind Server Activation Socket.
> [  OK  ] Reached target RPC Port Mapper.
> [   34.800509] systemd[1]: Listening on Process Core Dump Socket.
> [  OK  ] Listening on Process Core Dump Socket.
> [   34.817575] systemd[1]: Listening on initctl Compatibility Named Pipe.
> [  OK  ] Listening on initctl Compatibility Named Pipe.
> [   34.835866] systemd[1]: Listening on udev Control Socket.
> [  OK  ] Listening on udev Control Socket.
> [   34.851731] systemd[1]: Listening on udev Kernel Socket.
> [  OK  ] Listening on udev Kernel Socket.
> [   34.901469] systemd[1]: Mounting Huge Pages File System...
>          Mounting Huge Pages File System...
> [   34.921586] systemd[1]: Mounting POSIX Message Queue File System...
>          Mounting POSIX Message Queue File System...
> [   34.946587] systemd[1]: Mounting Kernel Debug File System...
>          Mounting Kernel Debug File System...
> [   34.969333] systemd[1]: Mounting Kernel Trace File System...
>          Mounting Kernel Trace File System...
> [   34.991219] systemd[1]: Mounting Temporary Directory /tmp...
>          Mounting Temporary Directory /tmp...
> [   35.002823] systemd[1]: Kernel Module supporting RPCSEC_GSS was skipped because of an unmet condition check (ConditionPathExists=/etc/krb5.keytab).
> [   35.008768] systemd[1]: Starting Create List of Static Device Nodes...
>          Starting Create List of Static Device Nodes...
> [   35.045982] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
>          Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
> [   35.065358] systemd[1]: Starting Load Kernel Module configfs...
>          Starting Load Kernel Module configfs...
> [   35.087331] systemd[1]: Starting Load Kernel Module drm...
>          Starting Load Kernel Module drm...
> [   35.107834] systemd[1]: Starting Load Kernel Module fuse...
>          Starting Load Kernel Module fuse...
> [   35.122507] systemd[1]: plymouth-switch-root.service: Deactivated successfully.
> [   35.123189] systemd[1]: Stopped Plymouth switch root service.
> [  OK  ] Stopped Plymouth switch root service.
> [   35.152572] systemd[1]: systemd-fsck-root.service: Deactivated successfully.
> [   35.153217] systemd[1]: Stopped File System Check on Root Device.
> [  OK  ] Stopped File System Check on Root Device.
> [   35.188134] systemd[1]: Starting Journal Service...
>          Starting Journal Service...
> [   35.198581] systemd[1]: Load Kernel Modules was skipped because no trigger condition checks were met.
> [   35.203780] systemd[1]: Starting Generate network units from Kernel command line...
>          Starting Generate network units from Kernel command line...
> [   35.233827] systemd[1]: Starting Remount Root and Kernel File Systems...
>          Starting Remount Root and Kernel File Systems...
> [   35.250723] systemd[1]: Starting Apply Kernel Variables...
>          Starting Apply Kernel Variables...
> [   35.267004] systemd[1]: Starting Coldplug All udev Devices...
>          Starting Coldplug All udev Devices...
> [   35.281708] systemd-journald[1201]: Collecting audit messages is disabled.
> [   35.282511] systemd[1]: Mounted Huge Pages File System.
> [  OK  ] Mounted Huge Pages File System.
> [   35.305714] systemd[1]: Mounted POSIX Message Queue File System.
> [   35.315684] EXT4-fs (nvme0n1p3): re-mounted 07617bd8-13da-4749-97a3-2b548687b739 r/w.
> [  OK  ] Mounted POSIX Message Queue File System.
> [   35.335786] systemd[1]: Started Journal Service.
> [  OK  ] Started Journal Service.
> [  OK  ] Mounted Kernel Debug File System.
> [  OK  ] Mounted Kernel Trace File System.
> [  OK  ] Mounted Temporary Directory /tmp.
> [  OK  ] Finished Create List of Static Device Nodes.
> [  OK  ] Finished Load Kernel Module configfs.
> [  OK  ] Finished Load Kernel Module drm.
> [  OK  ] Finished Load Kernel Module fuse.
> [  OK  ] Finished Generate network units from Kernel command line.
> [  OK  ] Finished Remount Root and Kernel File Systems.
>          Mounting FUSE Control File System...
>          Mounting Kernel Configuration File System...
>          Starting Flush Journal to Persistent Storage...
>          Starting Load/Save OS Random Seed...
>          Starting Create Static Device Nodes in /dev gracefully...
> [  OK  ] Mounted FUSE Control File System.
> [  OK  ] Mounted Kernel Configuration File System.
> [  OK  ] Finished Apply Kernel Variables.
> [   35.526662] systemd-journald[1201]: Received client request to flush runtime journal.
> [   35.550024] systemd-journald[1201]: /var/log/journal/552c396b6af0485990643f5de1788949/system.journal: Realtime clock jumped backwards relative to last journal entry, rotating.
> [  OK  ] Finished    35.568502] systemd-journald[1201]: Rotating system journal.
> ;1;39mCreate Static Device Nodes in /dev gracefully.
>          Starting Create Static Device Nodes in /dev...
> [  OK  ] Finished Create Static Device Nodes in /dev.
>          Starting Rule-based Manager for Device Events and Files...
> [  OK  ] Finished Flush Journal to Persistent Storage.
> [  OK  ] Started Rule-based Manager for Device Events and Files.
>          Starting Load Kernel Module fuse...
> [  OK  ] Finished Coldplug All udev Devices.
> [  OK  ] Finished Load Kernel Module fuse.
> [   36.191287] sophgo-spifmc 7000180000.flash-controller: gd25lb512me (65536 Kbytes)
> [  OK  ] Stopped Virtual Console Setup.
>          Stopping Virtual Console Setup...
> [   36.221724] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   36.225775] sophgo-spifmc 7002180000.flash-controller: gd25lb512me (65536 Kbytes)
> [   36.232401] gpio-keys soc:gpio-restart: there is not valid maps for state default
>          Starting Virtual Console Setup...
> [   36.256299] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   36.256647] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   36.273598] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
> [   36.290837] snd_hda_intel 0000:01:00.1: Force to snoop mode by module option
> [   36.306357] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   36.316354] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [  OK  ] Finished Virtual Console Setup.
> [   36.617211] random: crng init done
> [  OK  ] Finished Load/Save OS Random Seed.
> [  OK  ] Finished Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
> [  OK  ] Reached target Preparation for Local File Systems.
>          Mounting /boot...
> [   36.760150] FAT-fs (nvme0n1p2): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> [  OK  ] Mounted /boot.
>          Mounting /boot/efi...
> [   36.833966] FAT-fs (nvme0n1p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> [  OK  ] Mounted /boot/efi.
> [  OK  ] Reached target Local File Systems.
>          Starting Tell Plymouth To Write Out Runtime Data...
>          Starting Create Volatile Files and Directories...
> [  OK  ] Finished Tell Plymouth To Write Out Runtime Data.
> [  OK  ] Finished Create Volatile Files and Directories.
>          Starting Security Auditing Service...
>          Starting RPC Bind...
> [  OK  ] Started RPC Bind.
> [  OK  ] Started Security Auditing Service.
>          Starting Record System Boot/Shutdown in UTMP...
> [  OK  ] Finished Record System Boot/Shutdown in UTMP.
> [  OK  ] Reached target System Initialization.
> [  OK  ] Started dnf makecache --timer.
> [  OK  ] Started Daily Cleanup of Temporary Dire[   37.309183] snd_hda_intel 0000:01:00.1: azx_get_response timeout, switching to polling mode: last cmd=0x000f0000
> ctories.
> [  OK  ] Reached target Timer Units.
> [  OK  [   37.323629] snd_hda_intel 0000:01:00.1: bound 0000:01:00.0 (ops radeon_audio_component_bind_ops [radeon])
> ] Listening on D-Bus System Message Bus Socket.
> [  OK  ] Listening on PC/SC Smart Card Daemon[   37.341862] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
>  Activation Socket.
> [   37.342172] gpio-keys soc:gpio-restart: there is not valid maps for state default
> 2m  OK  ] Reached target    37.345625] input: HDA ATI HDMI HDMI/DP,pcm=3 as /devices/platform/7060000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.1/sound/card0/input52
> ;1;39mSocket Units.
> [  OK  ] Reached target Basic System.
>          Starting NTP client/server...
>          Starting D-Bus System Message Bus...
>          Starting Restore /run/initramfs on shutdown...
>          Starting Update RTC With System Clock...
>          Starting irqbalance daemon...
> [  OK  ] Started libstoragemgmt plug-in server daemon.
> [  OK  ] Started resize rootfs.
> [  OK  ] Started Hardware RNG Entropy Gatherer Daemon.
>          Starting Self Monitoring and Reporting Technology (SMART) Daemon...
> [  OK  ] Reached target sshd-keygen.target.
>          Starting User Login Management...
>          Starting Run a configured list of systemtap scripts at system startup....
> [  OK  ] Started D-Bus System Message Bus.
> [  OK  ] Finished Restore /run/initramfs on shutdown.
> [  OK  ] Finished Update RTC With System Clock.
> [  OK  ] Started irqbalance daemon.
> [  OK  ] Reached target Sound Card.
>          Starting firewalld - dynamic firewall daemon...
> [  OK  ] Started Self Monitoring and Reporting Technology (SMART) Daemon.
> [  OK  ] Started NTP client/server.
> [  OK  ] Finished Run a configured list of systemtap scripts at system startup..
> [  OK  ] Started User Login Management.
> [  OK  ] Started firewalld - dynamic firewall daemon.
> [  OK  ] Reached target Preparation for Network.
>          Starting Network Manager...
>          Starting Hostname Service...
> [  OK  ] Started Hostname Service.
>          Starting Network Manager Script Dispatcher Service...
> [   39.253277] RTL8226B_RTL8221B 2.5Gbps PHY r8169-2-c500:00: attached PHY driver (mii_bus:phy_addr=r8169-2-c500:00, irq=MAC)
> [  OK  ] Started Network Manager Script Dispatcher Service.
> [   39.469916] r8169 0002:c5:00.0 enP2p197s0: Link is Down
> [   39.517430] RTL8226B_RTL8221B 2.5Gbps PHY r8169-2-c900:00: attached PHY driver (mii_bus:phy_addr=r8169-2-c900:00, irq=MAC)
> [   39.752713] r8169 0002:c9:00.0 enP2p201s0: Link is Down
> [  OK  ] Started Network Manager.
> [  OK  ] Reached target Network.
>          Starting Network Manager Wait Online...
>          Starting GSSAPI Proxy Daemon...
>          Starting /etc/rc.d/rc.local Compatibility...
>          Starting OpenSSH server daemon...
>          Starting Dynamic System Tuning Daemon...
>          Starting Authorization Manager...
> [  OK  ] Started /etc/rc.d/rc.local Compatibility.
> [  OK  ] Started OpenSSH server daemon.
> [  OK  ] Started GSSAPI Proxy Daemon.
> [  OK  ] Reached target NFS client services.
> [  OK  ] Reached target Preparation for Remote File Systems.
> [  OK  ] Reached target Remote File Systems.
>          Starting Permit User Sessions...
> [  OK  ] Finished Permit User Sessions.
> [  OK  ] Started Deferred execution scheduler.
> [  OK  ] Started Command Scheduler.
>          Starting Hold until boot process finishes up...
>          Starting Terminate Plymouth Boot Screen...
> [   41.894739] r8169 0002:c5:00.0 enP2p197s0: Link is Up - 1Gbps/Full - flow control rx/tx
> 
> 
> Authorized users only. All activities may be monitored and reported.
> openeuler-riscv64 login: root
> Password: 
> Last login: Mon Mar 30 22:23:28 on tty1
> 
> Authorized users only. All activities may be monitored and reported.
> 
> 
> Welcome to 6.6.127+
> 
> System information as of time:  Mon Mar 30 22:38:22 CST 2026
> 
> System load:    0.16
> Memory used:    .5%
> Swap used:      0.0%
> Usage On:       3%
> IP address:     192.168.1.9
> Users online:   1
> 
> 
> [root@openeuler-riscv64 ~]# poweroff
> ```
> 
> poweroff
> 
> ```
> [  OK  ] Reached target Switch Root.
>          Starting Switch Root...
> [   33.209267] systemd-journald[606]: Received SIGTERM from PID 1 (systemd).
> [   33.620485] systemd[1]: systemd v255-34.oe2403sp1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA -SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDIS)
> [   33.664117] systemd[1]: Detected architecture riscv64.
> 
> Welcome to openEuler 24.03 (LTS-SP1)!
> 
> [   33.680609] systemd[1]: Hostname set to <openeuler-riscv64>.
> [   34.006662] systemd[1]: /usr/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file acc.
> [   34.460534] systemd[1]: initrd-switch-root.service: Deactivated successfully.
> [   34.474062] systemd[1]: Stopped Switch Root.
> [   34.487965] systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 1.
> [  OK  ] Stopped Switch Root.
> [   34.505914] systemd[1]: Created slice Slice /system/getty.
> [  OK  ] Created slice Slice /system/getty.
> [   34.518916] systemd[1]: Created slice Slice /system/modprobe.
> [  OK  ] Created slice Slice /system/modprobe.
> [   34.532925] systemd[1]: Created slice Slice /system/serial-getty.
> [  OK  ] Created slice Slice /system/serial-getty.
> [   34.547392] systemd[1]: Created slice Slice /system/sshd-keygen.
> [  OK  ] Created slice Slice /system/sshd-keygen.
> [   34.561592] systemd[1]: Created slice User and Session Slice.
> [  OK  ] Created slice User and Session Slice.
> [   34.573784] systemd[1]: Dispatch Password Requests to Console Directory Watch was skipped because of an unmet condition check (ConditionPathExists=!/run/plymouth/pid).
> [   34.574193] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
> [  OK  ] Started Forward Password Requests to Wall Directory Watch.
> [   34.610316] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
> [  OK  ] Set up automount Arbitrary Executable File Formats File System Automount Point.
> [   34.628480] systemd[1]: Stopped target Switch Root.
> [  OK  ] Stopped target Switch Root.
> [   34.643364] systemd[1]: Stopped target Initrd File Systems.
> [  OK  ] Stopped target Initrd File Systems.
> [   34.658685] systemd[1]: Stopped target Initrd Root File System.
> [   34.674425] systemd[1]: Reached target Path Units.
> [  OK  ] Stopped target Initrd Root File System.
> [   34.684328] systemd[1]: Reached target rpc_pipefs.target.
> [  OK  ] Reached target Path Units.
> [   34.699508] systemd[1]: Reached target Slice Units.
> [  OK  ] Reached target rpc_pipefs.target.
> [   34.714393] systemd[1]: Reached target Swaps.
> [  OK  ] Reached target Slice Units.
> [  OK  ] Reached target Swaps.
> [   34.729511] systemd[1]: Listening on Device-mapper event daemon FIFOs.
> [   34.749456] systemd[1]: Listening on LVM2 poll daemon socket.
> [  OK  ] Listening on Device-mapper event daemon FIFOs.
> [   34.763014] systemd[1]: Listening on RPCbind Server Activation Socket.
> [  OK  ] Listening on LVM2 poll daemon socket.
> [   34.779158] systemd[1]: Reached target RPC Port Mapper.
> [  OK  ] Listening on RPCbind Server Activation Socket.
> [  OK  ] Reached target RPC Port Mapper.
> [   34.800509] systemd[1]: Listening on Process Core Dump Socket.
> [  OK  ] Listening on Process Core Dump Socket.
> [   34.817575] systemd[1]: Listening on initctl Compatibility Named Pipe.
> [  OK  ] Listening on initctl Compatibility Named Pipe.
> [   34.835866] systemd[1]: Listening on udev Control Socket.
> [  OK  ] Listening on udev Control Socket.
> [   34.851731] systemd[1]: Listening on udev Kernel Socket.
> [  OK  ] Listening on udev Kernel Socket.
> [   34.901469] systemd[1]: Mounting Huge Pages File System...
>          Mounting Huge Pages File System...
> [   34.921586] systemd[1]: Mounting POSIX Message Queue File System...
>          Mounting POSIX Message Queue File System...
> [   34.946587] systemd[1]: Mounting Kernel Debug File System...
>          Mounting Kernel Debug File System...
> [   34.969333] systemd[1]: Mounting Kernel Trace File System...
>          Mounting Kernel Trace File System...
> [   34.991219] systemd[1]: Mounting Temporary Directory /tmp...
>          Mounting Temporary Directory /tmp...
> [   35.002823] systemd[1]: Kernel Module supporting RPCSEC_GSS was skipped because of an unmet condition check (ConditionPathExists=/etc/krb5.keytab).
> [   35.008768] systemd[1]: Starting Create List of Static Device Nodes...
>          Starting Create List of Static Device Nodes...
> [   35.045982] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
>          Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
> [   35.065358] systemd[1]: Starting Load Kernel Module configfs...
>          Starting Load Kernel Module configfs...
> [   35.087331] systemd[1]: Starting Load Kernel Module drm...
>          Starting Load Kernel Module drm...
> [   35.107834] systemd[1]: Starting Load Kernel Module fuse...
>          Starting Load Kernel Module fuse...
> [   35.122507] systemd[1]: plymouth-switch-root.service: Deactivated successfully.
> [   35.123189] systemd[1]: Stopped Plymouth switch root service.
> [  OK  ] Stopped Plymouth switch root service.
> [   35.152572] systemd[1]: systemd-fsck-root.service: Deactivated successfully.
> [   35.153217] systemd[1]: Stopped File System Check on Root Device.
> [  OK  ] Stopped File System Check on Root Device.
> [   35.188134] systemd[1]: Starting Journal Service...
>          Starting Journal Service...
> [   35.198581] systemd[1]: Load Kernel Modules was skipped because no trigger condition checks were met.
> [   35.203780] systemd[1]: Starting Generate network units from Kernel command line...
>          Starting Generate network units from Kernel command line...
> [   35.233827] systemd[1]: Starting Remount Root and Kernel File Systems...
>          Starting Remount Root and Kernel File Systems...
> [   35.250723] systemd[1]: Starting Apply Kernel Variables...
>          Starting Apply Kernel Variables...
> [   35.267004] systemd[1]: Starting Coldplug All udev Devices...
>          Starting Coldplug All udev Devices...
> [   35.281708] systemd-journald[1201]: Collecting audit messages is disabled.
> [   35.282511] systemd[1]: Mounted Huge Pages File System.
> [  OK  ] Mounted Huge Pages File System.
> [   35.305714] systemd[1]: Mounted POSIX Message Queue File System.
> [   35.315684] EXT4-fs (nvme0n1p3): re-mounted 07617bd8-13da-4749-97a3-2b548687b739 r/w.
> [  OK  ] Mounted POSIX Message Queue File System.
> [   35.335786] systemd[1]: Started Journal Service.
> [  OK  ] Started Journal Service.
> [  OK  ] Mounted Kernel Debug File System.
> [  OK  ] Mounted Kernel Trace File System.
> [  OK  ] Mounted Temporary Directory /tmp.
> [  OK  ] Finished Create List of Static Device Nodes.
> [  OK  ] Finished Load Kernel Module configfs.
> [  OK  ] Finished Load Kernel Module drm.
> [  OK  ] Finished Load Kernel Module fuse.
> [  OK  ] Finished Generate network units from Kernel command line.
> [  OK  ] Finished Remount Root and Kernel File Systems.
>          Mounting FUSE Control File System...
>          Mounting Kernel Configuration File System...
>          Starting Flush Journal to Persistent Storage...
>          Starting Load/Save OS Random Seed...
>          Starting Create Static Device Nodes in /dev gracefully...
> [  OK  ] Mounted FUSE Control File System.
> [  OK  ] Mounted Kernel Configuration File System.
> [  OK  ] Finished Apply Kernel Variables.
> [   35.526662] systemd-journald[1201]: Received client request to flush runtime journal.
> [   35.550024] systemd-journald[1201]: /var/log/journal/552c396b6af0485990643f5de1788949/system.journal: Realtime clock jumped backwards relative to last journal entry, rotating.
> [  OK  ] Finished    35.568502] systemd-journald[1201]: Rotating system journal.
> ;1;39mCreate Static Device Nodes in /dev gracefully.
>          Starting Create Static Device Nodes in /dev...
> [  OK  ] Finished Create Static Device Nodes in /dev.
>          Starting Rule-based Manager for Device Events and Files...
> [  OK  ] Finished Flush Journal to Persistent Storage.
> [  OK  ] Started Rule-based Manager for Device Events and Files.
>          Starting Load Kernel Module fuse...
> [  OK  ] Finished Coldplug All udev Devices.
> [  OK  ] Finished Load Kernel Module fuse.
> [   36.191287] sophgo-spifmc 7000180000.flash-controller: gd25lb512me (65536 Kbytes)
> [  OK  ] Stopped Virtual Console Setup.
>          Stopping Virtual Console Setup...
> [   36.221724] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   36.225775] sophgo-spifmc 7002180000.flash-controller: gd25lb512me (65536 Kbytes)
> [   36.232401] gpio-keys soc:gpio-restart: there is not valid maps for state default
>          Starting Virtual Console Setup...
> [   36.256299] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   36.256647] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [   36.273598] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
> [   36.290837] snd_hda_intel 0000:01:00.1: Force to snoop mode by module option
> [   36.306357] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> [   36.316354] gpio-keys soc:gpio-restart: there is not valid maps for state default
> [  OK  ] Finished Virtual Console Setup.
> [   36.617211] random: crng init done
> [  OK  ] Finished Load/Save OS Random Seed.
> [  OK  ] Finished Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
> [  OK  ] Reached target Preparation for Local File Systems.
>          Mounting /boot...
> [   36.760150] FAT-fs (nvme0n1p2): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> [  OK  ] Mounted /boot.
>          Mounting /boot/efi...
> [   36.833966] FAT-fs (nvme0n1p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> [  OK  ] Mounted /boot/efi.
> [  OK  ] Reached target Local File Systems.
>          Starting Tell Plymouth To Write Out Runtime Data...
>          Starting Create Volatile Files and Directories...
> [  OK  ] Finished Tell Plymouth To Write Out Runtime Data.
> [  OK  ] Finished Create Volatile Files and Directories.
>          Starting Security Auditing Service...
>          Starting RPC Bind...
> [  OK  ] Started RPC Bind.
> [  OK  ] Started Security Auditing Service.
>          Starting Record System Boot/Shutdown in UTMP...
> [  OK  ] Finished Record System Boot/Shutdown in UTMP.
> [  OK  ] Reached target System Initialization.
> [  OK  ] Started dnf makecache --timer.
> [  OK  ] Started Daily Cleanup of Temporary Dire[   37.309183] snd_hda_intel 0000:01:00.1: azx_get_response timeout, switching to polling mode: last cmd=0x000f0000
> ctories.
> [  OK  ] Reached target Timer Units.
> [  OK  [   37.323629] snd_hda_intel 0000:01:00.1: bound 0000:01:00.0 (ops radeon_audio_component_bind_ops [radeon])
> ] Listening on D-Bus System Message Bus Socket.
> [  OK  ] Listening on PC/SC Smart Card Daemon[   37.341862] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
>  Activation Socket.
> [   37.342172] gpio-keys soc:gpio-restart: there is not valid maps for state default
> 2m  OK  ] Reached target    37.345625] input: HDA ATI HDMI HDMI/DP,pcm=3 as /devices/platform/7060000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.1/sound/card0/input52
> ;1;39mSocket Units.
> [  OK  ] Reached target Basic System.
>          Starting NTP client/server...
>          Starting D-Bus System Message Bus...
>          Starting Restore /run/initramfs on shutdown...
>          Starting Update RTC With System Clock...
>          Starting irqbalance daemon...
> [  OK  ] Started libstoragemgmt plug-in server daemon.
> [  OK  ] Started resize rootfs.
> [  OK  ] Started Hardware RNG Entropy Gatherer Daemon.
>          Starting Self Monitoring and Reporting Technology (SMART) Daemon...
> [  OK  ] Reached target sshd-keygen.target.
>          Starting User Login Management...
>          Starting Run a configured list of systemtap scripts at system startup....
> [  OK  ] Started D-Bus System Message Bus.
> [  OK  ] Finished Restore /run/initramfs on shutdown.
> 1;-1f[  OK  ] Stopped Permit User Sessions.
> [  OK  ] Stopped target Remote File Systems.
> [  OK  ] Stopped target Preparation for Remote File Systems.
> [  OK  ] Stopped target NFS client services.
>          Stopping GSSAPI Proxy Daemon...
> [  OK  ] Stopped Dynamic System Tuning Daemon.
> [  OK  ] Stopped GSSAPI Proxy Daemon.
> [  OK  ] Started Show Plymouth Power Off Screen.
> [  OK  ] Stopped target Network.
>          Stopping Network Manager...
> [  OK  ] Stopped Network Manager.
> [  OK  ] Stopped target Preparation for Network.
>          Stopping firewalld - dynamic firewall daemon...
> [  OK  ] Stopped Generate network units from Kernel command line.
> [  OK  ] Stopped firewalld - dynamic firewall daemon.
>          Stopping D-Bus System Message Bus...
>          Stopping Authorization Manager...
> [  OK  ] Stopped D-Bus System Message Bus.
> [  OK  ] Stopped Authorization Manager.
> [  OK  ] Stopped target Basic System.
> [  OK  ] Stopped Forward Password Requests to Plymouth Directory Watch.
> [  OK  ] Stopped target Path Units.
> [  OK  ] Stopped Forward Password Requests to Wall Directory Watch.
> [  OK  ] Stopped target Slice Units.
> [  OK  ] Removed slice User and Session Slice.
> [  OK  ] Stopped target Socket Units.
> [  OK  ] Closed D-Bus System Message Bus Socket.
> [  OK  ] Closed PC/SC Smart Card Daemon Activation Socket.
> [  OK  ] Stopped target System Initialization.
> [  OK  ] Unset automount Arbitrary Executable File Formats File System Automount Point.
> [  OK  ] Stopped Apply Kernel Variables.
> [  OK  ] Closed Process Core Dump Socket.
>          Stopping Record System Boot/Shutdown in UTMP...
> [  OK  ] Stopped Record System Boot/Shutdown in UTMP.
>          Stopping Security Auditing Servi[  636.281948] audit: type=1305 audit(1774881583.167:96): op=set audit_pid=0 old=1422 auid=4294967295 ses=4294967295 subj=unconfined res=1
> ce...
> [  636.299707] audit: type=1131 audit(1774881583.183:97): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=auditd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
> [  OK  ] Stopped   636.319649] audit: type=1131 audit(1774881583.203:98): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termi'
> 1;39mSecurity Auditing Service.
> [  OK  ] Stopped Create Volatile Files and Directories.
> [  OK  ] Stopped target Local File Systems.
>          Unmounting /boot/efi...
>          Unmounting Temporary Directory /tmp...
> [  OK  ] Unmounted Temporary Directory /tmp.
> [  OK  ] Stopped target Swaps.
> [  OK  ] Unmounted /boot/efi.
>          Unmounting /boot...
> [  OK  ] Unmounted /boot.
> [  OK  ] Stopped target Preparation for Local File Syste[  636.485345] audit: type=1131 audit(1774881583.367:99): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-remount-fs comm="systemd" exe="/usr/lib/syst'
> ms.
> [  OK  ] Re[  636.509090] audit: type=1131 audit(1774881583.391:100): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup-dev comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termi'
> ached target Unmount Al[  636.533088] audit: type=1131 audit(1774881583.415:101): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup-dev-early comm="systemd" exe="/usr/lib/systemd/systemd" hostn'
> l Filesystems.
>          St[  636.559414] audit: type=1131 audit(1774881583.443:102): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=lvm2-monitor comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=succ'
> opping Monitoring of LV[  636.581659] audit: type=1130 audit(1774881583.463:103): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-poweroff comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? ter'
> M2 mirrors, snapshots etc. using[  636.603011] audit: type=1131 audit(1774881583.463:104): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-poweroff comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? a'
>  dmeventd or progress polling...
> [  OK  ] Stopped Remount Root and Kernel File Systems.
> [  OK  ] Stopped Create Static Device Nodes in /dev.
> [  OK  ] Stopped Create Static Device Nodes in /dev gracefully.
> [  OK  ] Stopped Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
> [  OK  ] Reached target System Shutdown.
> [  OK  ] Reached target Late Shutdown Services.
> [  OK  ] Finished System Power Off.
> [  OK  ] Reached target System Power Off.
> [  636.797550] systemd-shutdown[1]: Syncing filesystems and block devices.
> [  636.812866] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
> [  636.922730] systemd-journald[1201]: Received SIGTERM from PID 1 (systemd-shutdow).
> [  636.984247] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
> [  637.177412] systemd-shutdown[1]: Unmounting file systems.
> [  637.186000] (sd-remount)[2172]: Remounting '/' read-only with options ''.
> [  637.244917] EXT4-fs (nvme0n1p3): re-mounted 07617bd8-13da-4749-97a3-2b548687b739 ro.
> [  637.307447] systemd-shutdown[1]: All filesystems unmounted.
> [  637.313192] systemd-shutdown[1]: Deactivating swaps.
> [  637.318493] systemd-shutdown[1]: All swaps deactivated.
> [  637.323865] systemd-shutdown[1]: Detaching loop devices.
> [  637.334092] systemd-shutdown[1]: All loop devices detached.
> [  637.339772] systemd-shutdown[1]: Stopping MD devices.
> [  637.345168] systemd-shutdown[1]: All MD devices stopped.
> [  637.350568] systemd-shutdown[1]: Detaching DM devices.
> [  637.355991] systemd-shutdown[1]: All DM devices detached.
> [  637.361474] systemd-shutdown[1]: All filesystems, swaps, loop devices, MD devices and DM devices detached.
> [  637.410897] systemd-shutdown[1]: Syncing filesystems and block devices.
> [  637.417769] systemd-shutdown[1]: Powering off.
> [  637.522257] r8169 0002:c5:00.0 enP2p197s0: Link is Down
> [  637.553174] reboot: Power down
> mango_system_reset: chip is not mango
> ```
> 
> 此时风扇狂转

[    0.000000] Machine model: Sophgo Mango
[    0.000000] SBI specification v1.0 detected
[    0.000000] SBI implementation ID=0x1 Version=0x10002
[    0.000000] SBI TIME extension detected
[    0.000000] SBI IPI extension detected
[    0.000000] SBI RFENCE extension detected
[    0.000000] SBI SRST extension detected
如上日志可以看出sbi并没有开启FWFT特性（如果打开会有SBI FWFT extension detected输出），因此这个系列的补丁其实并没有生效。

而最后打印
 [  637.553174] reboot: Power down
 mango_system_reset: chip is not mango
代表内核层面的关机流程已经完成，但硬件/固件复位阶段失败，芯片无法正确进入断电状态导致风扇狂转；这是一个底层固件/硬件兼容性问题，不是内核通用代码的问题。如果有其它型号的设备，是否可以更换一个再测试一下呢

**Comment by sterling-teng** [comment]
> > > > 我在milkv pioneer上测试，这个pr在空负载时降低了风扇转速，很安静。但是执行poweroff后，风扇转速升高，主板不下电，关机失败。这个pr需要更多的物理机测试。
> > > 
> > > 
> > > 理论上这个功能 在不支持sbi3.0的设备不会开启，即使开启了也只会处理非对齐处理，不会影响其它流程，是否是与lava故障一样initramfs没有重新编译导致，能否取一下上下电串口日志看看
> > 
> > 
> > boot
> > ```
> > [    0.000000] software IO TLB: mapped [mem 0x00000000bbe3d000-0x00000000bfe3d000] (64MB)
> > [    0.000000] Memory: 126955100K/130023424K available (11202K kernel code, 5727K rwdata, 10240K rodata, 2714K init, 520K bss, 2806180K reserved, 262144K cma-reserved)
> > [    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=64, Nodes=4
> > [    0.000000] ftrace: allocating 41282 entries in 162 pages
> > [    0.000000] ftrace: allocated 162 pages with 3 groups
> > [    0.000000] rcu: Hierarchical RCU implementation.
> > [    0.000000]  Rude variant of Tasks RCU enabled.
> > [    0.000000]  Tracing variant of Tasks RCU enabled.
> > [    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
> > [    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
> > [    0.000000] riscv-intc: 64 local interrupts mapped
> > [    0.000000] riscv-plic: interrupt-controller@7090000000: mapped 224 interrupts with 64 handlers for 128 contexts.
> > [    0.000000] riscv: providing IPIs using SBI IPI extension
> > [    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
> > [    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0xb8812736b, max_idle_ns: 440795202655 ns
> > [    0.000000] sched_clock: 64 bits at 50MHz, resolution 20ns, wraps every 4398046511100ns
> > [    0.008513] clocksource: dw-apb-timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 38225208935 ns
> > [    0.018423] sched_clock: 32 bits at 50MHz, resolution 20ns, wraps every 42949672950ns
> > [    0.026951] Console: colour dummy device 80x25
> > [    0.031422] printk: console [tty0] enabled
> > [    0.035532] printk: bootconsole [uart0] disabled
> > [    0.000000] Linux version 6.6.127+ (root@openeuler-riscv64) (gcc (GCC) 12.3.1 (openEuler 12.3.1-62.oe2403sp1), GNU ld (GNU Binutils) 2.41) #4 SMP Fri Mar 27 01:16:22 CST 2026
> > [    0.000000] Machine model: Sophgo Mango
> > [    0.000000] SBI specification v1.0 detected
> > [    0.000000] SBI implementation ID=0x1 Version=0x10002
> > [    0.000000] SBI TIME extension detected
> > [    0.000000] SBI IPI extension detected
> > [    0.000000] SBI RFENCE extension detected
> > [    0.000000] SBI SRST extension detected
> > [    0.000000] efi: EFI v2.7 by EDK II
> > [    0.000000] efi: SMBIOS=0xbffdc000 INITRD=0xb7a0ea98 MEMRESERVE=0xb7a0e118 
> > [    0.000000] OF: reserved mem: 0x0000000000000000..0x00000000001fffff (2048 KiB) map non-reusable mmode_resv0@0
> > [    0.000000] cma: Reserved 256 MiB at 0x0000000098200000 on node -1
> > [    0.000000] earlycon: uart0 at MMIO32 0x0000007040000000 (options '')
> > [    0.000000] printk: bootconsole [uart0] enabled
> > [    0.000000] OF: NUMA: parsing numa-distance-map-v1
> > [    0.000000] NUMA: NODE_DATA [mem 0x7ffffdfc0-0x7ffffffff]
> > [    0.000000] NUMA: NODE_DATA [mem 0xfffffdfc0-0xfffffffff]
> > [    0.000000] NUMA: NODE_DATA [mem 0x17ffffdfc0-0x17ffffffff]
> > [    0.000000] NUMA: NODE_DATA [mem 0x1f42531fc0-0x1f42533fff]
> > [    0.000000] Zone ranges:
> > [    0.000000]   DMA32    [mem 0x0000000002800000-0x00000000ffffffff]
> > [    0.000000]   Normal   [mem 0x0000000100000000-0x0000001f427fffff]
> > [    0.000000] Movable zone start for each node
> > [    0.000000] Early memory node ranges
> > [    0.000000]   node   0: [mem 0x0000000002800000-0x00000000bfe3cfff]
> > [    0.000000]   node   0: [mem 0x00000000bfe3d000-0x00000000bfffefff]
> > [    0.000000]   node   0: [mem 0x00000000bffff000-0x00000000bfffffff]
> > [    0.000000]   node   0: [mem 0x0000000100000000-0x00000007ffffffff]
> > [    0.000000]   node   1: [mem 0x0000000800000000-0x0000000fffffffff]
> > [    0.000000]   node   2: [mem 0x0000001000000000-0x00000017ffffffff]
> > [    0.000000]   node   3: [mem 0x0000001800000000-0x0000001f427fffff]
> > [    0.000000] Initmem setup node 0 [mem 0x0000000002800000-0x00000007ffffffff]
> > [    0.000000] Initmem setup node 1 [mem 0x0000000800000000-0x0000000fffffffff]
> > [    0.000000] Initmem setup node 2 [mem 0x0000001000000000-0x00000017ffffffff]
> > [    0.000000] Initmem setup node 3 [mem 0x0000001800000000-0x0000001f427fffff]
> > [    0.000000] On node 0, zone DMA32: 10240 pages in unavailable ranges
> > [    0.000000] On node 3, zone Normal: 22528 pages in unavailable ranges
> > [    0.000000] SBI HSM extension detected
> > [    0.000000] Falling back to deprecated "riscv,isa"
> > [    0.000000] Vendor extensions are ignored in riscv,isa. Use riscv,isa-extensions instead.
> > [    0.000000] riscv: base ISA extensions acdfim
> > [    0.000000] riscv: ELF capabilities acdfim
> > [    0.000000] Ticket spinlock: enabled
> > [    0.000000] percpu: cpu 0 has no node -1 or node-local memory
> > [    0.000000] percpu: Embedded 29 pages/cpu s80872 r8192 d29720 u118784
> > [    0.000000] Kernel command line: BOOT_IMAGE=/Image root=/dev/nvme0n1p3 ro selinux=0 console=ttyS0,115200 console=tty earlycon rootwait
> > [    0.000000] Unknown kernel command line parameters "selinux=0", will be passed to user space.
> > [    0.000000] printk: log_buf_len individual max cpu contribution: 4096 bytes
> > [    0.000000] printk: log_buf_len total cpu_extra contributions: 258048 bytes
> > [    0.000000] printk: log_buf_len min size: 131072 bytes
> > [    0.000000] printk: log_buf_len: 524288 bytes
> > [    0.000000] printk: early log buf free: 127264(97%)
> > [    0.000000] Fallback order for Node 0: 0 1 2 3 
> > [    0.000000] Fallback order for Node 1: 1 0 3 2 
> > [    0.000000] Fallback order for Node 2: 2 3 0 1 
> > [    0.000000] Fallback order for Node 3: 3 2 1 0 
> > [    0.000000] Built 4 zonelists, mobility grouping on.  Total pages: 31870976
> > [    0.000000] Policy zone: Normal
> > [    0.000000] mem auto-init: stack:all(pattern), heap alloc:on, heap free:off
> > [    0.000000] software IO TLB: area num 64.
> > [    0.000000] software IO TLB: mapped [mem 0x00000000bbe3d000-0x00000000bfe3d000] (64MB)
> > [    0.000000] Memory: 126955100K/130023424K available (11202K kernel code, 5727K rwdata, 10240K rodata, 2714K init, 520K bss, 2806180K reserved, 262144K cma-reserved)
> > [    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=64, Nodes=4
> > [    0.000000] ftrace: allocating 41282 entries in 162 pages
> > [    0.000000] ftrace: allocated 162 pages with 3 groups
> > [    0.000000] rcu: Hierarchical RCU implementation.
> > [    0.000000]  Rude variant of Tasks RCU enabled.
> > [    0.000000]  Tracing variant of Tasks RCU enabled.
> > [    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
> > [    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
> > [    0.000000] riscv-intc: 64 local interrupts mapped
> > [    0.000000] riscv-plic: interrupt-controller@7090000000: mapped 224 interrupts with 64 handlers for 128 contexts.
> > [    0.000000] riscv: providing IPIs using SBI IPI extension
> > [    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
> > [    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0xb8812736b, max_idle_ns: 440795202655 ns
> > [    0.000000] sched_clock: 64 bits at 50MHz, resolution 20ns, wraps every 4398046511100ns
> > [    0.008513] clocksource: dw-apb-timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 38225208935 ns
> > [    0.018423] sched_clock: 32 bits at 50MHz, resolution 20ns, wraps every 42949672950ns
> > [    0.026951] Console: colour dummy device 80x25
> > [    0.031422] printk: console [tty0] enabled
> > [    0.035532] printk: bootconsole [uart0] disabled
> > [    0.041611] mempolicy: Enabling automatic NUMA balancing. Configure with numa_balancing= or the kernel.numa_balancing sysctl
> > [    0.041730] Calibrating delay loop (skipped), value calculated using timer frequency.. 100.00 BogoMIPS (lpj=200000)
> > [    0.041756] pid_max: default: 65536 minimum: 512
> > [    0.044623] LSM: initializing lsm=lockdown,capability,landlock,yama,apparmor,tomoyo,bpf,integrity
> > [    0.044689] landlock: Up and running.
> > [    0.044698] Yama: becoming mindful.
> > [    0.044817] AppArmor: AppArmor initialized
> > [    0.044837] TOMOYO Linux initialized
> > [    0.044868] LSM support for eBPF active
> > [    0.068355] Dentry cache hash table entries: 8388608 (order: 14, 67108864 bytes, vmalloc hugepage)
> > [    0.080238] Inode-cache hash table entries: 4194304 (order: 13, 33554432 bytes, vmalloc hugepage)
> > [    0.081298] Mount-cache hash table entries: 131072 (order: 8, 1048576 bytes, vmalloc)
> > [    0.081808] Mountpoint-cache hash table entries: 131072 (order: 8, 1048576 bytes, vmalloc)
> > [    0.130600] RCU Tasks Rude: Setting shift to 6 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=64.
> > [    0.130766] RCU Tasks Trace: Setting shift to 6 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=64.
> > [    0.130865] riscv: ELF compat mode unsupported
> > [    0.131020] ASID allocator using 16 bits (65536 entries)
> > [    0.131182] rcu: Hierarchical SRCU implementation.
> > [    0.131197] rcu:     Max phase no-delay instances is 1000.
> > [    0.131863] Remapping and enabling EFI services.
> > [    0.135082] smp: Bringing up secondary CPUs ...
> > [    0.180707] smp: Brought up 4 nodes, 64 CPUs
> > [    0.212594] devtmpfs: initialized
> > [    0.221711] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
> > [    0.222216] futex hash table entries: 16384 (order: 8, 1048576 bytes, vmalloc)
> > [    0.229045] pinctrl core: initialized pinctrl subsystem
> > [    0.229882] SMBIOS 2.8 present.
> > [    0.229913] DMI: SOPHGO Sophgo SG2042 EVB Board/Sophgo SG2042 EVB Board, BIOS V1.0 Mar 27 2024
> > [    0.231476] NET: Registered PF_NETLINK/PF_ROUTE protocol family
> > [    0.234102] DMA: preallocated 4096 KiB GFP_KERNEL pool for atomic allocations
> > [    0.235062] DMA: preallocated 4096 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
> > [    0.236066] audit: initializing netlink subsys (disabled)
> > [    0.236423] audit: type=2000 audit(0.208:1): state=initialized audit_enabled=0 res=1
> > [    0.237182] thermal_sys: Registered thermal governor 'fair_share'
> > [    0.237194] thermal_sys: Registered thermal governor 'bang_bang'
> > [    0.237216] thermal_sys: Registered thermal governor 'step_wise'
> > [    0.237227] thermal_sys: Registered thermal governor 'user_space'
> > [    0.237238] thermal_sys: Registered thermal governor 'power_allocator'
> > [    0.237359] cpuidle: using governor ladder
> > [    0.237423] cpuidle: using governor menu
> > [    0.265051] cpu63: Ratio of byte access time to unaligned word access is 2.86, unaligned accesses are fast
> > [    0.265051] cpu62: Ratio of byte access time to unaligned word access is 2.81, unaligned accesses are fast
> > [    0.265051] cpu61: Ratio of byte access time to unaligned word access is 2.86, unaligned accesses are fast
> > [    0.265051] cpu60: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
> > [    0.265055] cpu5: Ratio of byte access time to unaligned word access is 3.98, unaligned accesses are fast
> > [    0.265054] cpu47: Ratio of byte access time to unaligned word access is 3.01, unaligned accesses are fast
> > [    0.265054] cpu45: Ratio of byte access time to unaligned word access is 3.00, unaligned accesses are fast
> > [    0.265055] cpu36: Ratio of byte access time to unaligned word access is 3.14, unaligned accesses are fast
> > [    0.265051] cpu11: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> > [    0.265051] cpu24: Ratio of byte access time to unaligned word access is 3.30, unaligned accesses are fast
> > [    0.265054] cpu44: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
> > [    0.265054] cpu46: Ratio of byte access time to unaligned word access is 2.95, unaligned accesses are fast
> > [    0.265052] cpu25: Ratio of byte access time to unaligned word access is 3.38, unaligned accesses are fast
> > [    0.265055] cpu2: Ratio of byte access time to unaligned word access is 2.88, unaligned accesses are fast
> > [    0.265055] cpu3: Ratio of byte access time to unaligned word access is 2.82, unaligned accesses are fast
> > [    0.265054] cpu35: Ratio of byte access time to unaligned word access is 3.19, unaligned accesses are fast
> > [    0.265051] cpu10: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
> > [    0.265054] cpu32: Ratio of byte access time to unaligned word access is 3.26, unaligned accesses are fast
> > [    0.265056] cpu29: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
> > [    0.265053] cpu56: Ratio of byte access time to unaligned word access is 3.07, unaligned accesses are fast
> > [    0.265053] cpu58: Ratio of byte access time to unaligned word access is 2.98, unaligned accesses are fast
> > [    0.265055] cpu37: Ratio of byte access time to unaligned word access is 4.56, unaligned accesses are fast
> > [    0.265055] cpu4: Ratio of byte access time to unaligned word access is 2.82, unaligned accesses are fast
> > [    0.265052] cpu48: Ratio of byte access time to unaligned word access is 3.11, unaligned accesses are fast
> > [    0.265055] cpu1: Ratio of byte access time to unaligned word access is 2.80, unaligned accesses are fast
> > [    0.265056] cpu7: Ratio of byte access time to unaligned word access is 3.91, unaligned accesses are fast
> > [    0.265056] cpu6: Ratio of byte access time to unaligned word access is 4.02, unaligned accesses are fast
> > [    0.265055] cpu21: Ratio of byte access time to unaligned word access is 3.07, unaligned accesses are fast
> > [    0.265054] cpu13: Ratio of byte access time to unaligned word access is 3.75, unaligned accesses are fast
> > [    0.265053] cpu53: Ratio of byte access time to unaligned word access is 2.91, unaligned accesses are fast
> > [    0.265056] cpu30: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> > [    0.265052] cpu17: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
> > [    0.265053] cpu40: Ratio of byte access time to unaligned word access is 3.14, unaligned accesses are fast
> > [    0.265054] cpu43: Ratio of byte access time to unaligned word access is 3.26, unaligned accesses are fast
> > [    0.265053] cpu42: Ratio of byte access time to unaligned word access is 3.23, unaligned accesses are fast
> > [    0.265053] cpu41: Ratio of byte access time to unaligned word access is 3.22, unaligned accesses are fast
> > [    0.265054] cpu14: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
> > [    0.265051] cpu9: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
> > [    0.265052] cpu27: Ratio of byte access time to unaligned word access is 3.42, unaligned accesses are fast
> > [    0.265054] cpu34: Ratio of byte access time to unaligned word access is 3.38, unaligned accesses are fast
> > [    0.265054] cpu33: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
> > [    0.265053] cpu54: Ratio of byte access time to unaligned word access is 2.94, unaligned accesses are fast
> > [    0.265051] cpu8: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
> > [    0.265056] cpu31: Ratio of byte access time to unaligned word access is 3.04, unaligned accesses are fast
> > [    0.265055] cpu39: Ratio of byte access time to unaligned word access is 3.22, unaligned accesses are fast
> > [    0.265055] cpu38: Ratio of byte access time to unaligned word access is 3.60, unaligned accesses are fast
> > [    0.265055] cpu22: Ratio of byte access time to unaligned word access is 3.13, unaligned accesses are fast
> > [    0.265054] cpu15: Ratio of byte access time to unaligned word access is 2.88, unaligned accesses are fast
> > [    0.265052] cpu49: Ratio of byte access time to unaligned word access is 2.83, unaligned accesses are fast
> > [    0.265055] cpu20: Ratio of byte access time to unaligned word access is 3.18, unaligned accesses are fast
> > [    0.265053] cpu52: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> > [    0.265053] cpu55: Ratio of byte access time to unaligned word access is 2.92, unaligned accesses are fast
> > [    0.265052] cpu16: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> > [    0.265052] cpu26: Ratio of byte access time to unaligned word access is 3.18, unaligned accesses are fast
> > [    0.265052] cpu51: Ratio of byte access time to unaligned word access is 2.89, unaligned accesses are fast
> > [    0.265055] cpu23: Ratio of byte access time to unaligned word access is 3.07, unaligned accesses are fast
> > [    0.265054] cpu12: Ratio of byte access time to unaligned word access is 3.32, unaligned accesses are fast
> > [    0.265054] cpu19: Ratio of byte access time to unaligned word access is 2.98, unaligned accesses are fast
> > [    0.265052] cpu50: Ratio of byte access time to unaligned word access is 2.80, unaligned accesses are fast
> > [    0.265053] cpu59: Ratio of byte access time to unaligned word access is 2.97, unaligned accesses are fast
> > [    0.265053] cpu57: Ratio of byte access time to unaligned word access is 3.06, unaligned accesses are fast
> > [    0.265056] cpu28: Ratio of byte access time to unaligned word access is 3.02, unaligned accesses are fast
> > [    0.265054] cpu18: Ratio of byte access time to unaligned word access is 3.00, unaligned accesses are fast
> > [    0.289100] cpu0: Ratio of byte access time to unaligned word access is 5.97, unaligned accesses are fast
> > [    0.290415] Serial: LRW UART driver
> > [    0.290665] sse: Missing SBI SSE extension
> > [    0.311076] sophgo,top-intc 70300102e0.top_intc: is a msi parent
> > [    0.327406] HugeTLB: registered 1.00 GiB page size, pre-allocated 0 pages
> > [    0.327430] HugeTLB: 0 KiB vmemmap can be freed for a 1.00 GiB page
> > [    0.327444] HugeTLB: registered 2.00 MiB page size, pre-allocated 0 pages
> > [    0.327455] HugeTLB: 0 KiB vmemmap can be freed for a 2.00 MiB page
> > [    0.332494] ACPI: Interpreter disabled.
> > [    0.333142] iommu: Default domain type: Translated
> > [    0.333161] iommu: DMA domain TLB invalidation policy: strict mode
> > [    0.333759] pps_core: LinuxPPS API ver. 1 registered
> > [    0.333779] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
> > [    0.333804] PTP clock support registered
> > [    0.334314] efivars: Registered efivars operations
> > [    0.335699] NetLabel: Initializing
> > [    0.335723] NetLabel:  domain hash size = 128
> > [    0.335734] NetLabel:  protocols = UNLABELED CIPSOv4 CALIPSO
> > [    0.335804] NetLabel:  unlabeled traffic allowed by default
> > [    0.336150] vgaarb: loaded
> > [    0.337190] clocksource: Switched to clocksource riscv_clocksource
> > [    0.343385] VFS: Disk quotas dquot_6.6.0
> > [    0.343633] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
> > [    0.346650] AppArmor: AppArmor Filesystem Enabled
> > [    0.346810] pnp: PnP ACPI: disabled
> > [    0.358401] NET: Registered PF_INET protocol family
> > [    0.359469] IP idents hash table entries: 262144 (order: 9, 2097152 bytes, vmalloc)
> > [    0.373312] tcp_listen_portaddr_hash hash table entries: 65536 (order: 8, 1048576 bytes, vmalloc)
> > [    0.373987] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, vmalloc)
> > [    0.375584] TCP established hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)
> > [    0.377485] TCP bind hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
> > [    0.378590] TCP: Hash tables configured (established 524288 bind 65536)
> > [    0.380288] MPTCP token hash table entries: 65536 (order: 9, 1572864 bytes, vmalloc)
> > [    0.382060] UDP hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
> > [    0.383229] UDP-Lite hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
> > [    0.384259] NET: Registered PF_UNIX/PF_LOCAL protocol family
> > [    0.384308] NET: Registered PF_XDP protocol family
> > [    0.384333] PCI: CLS 0 bytes, default 64
> > [    0.385763] Trying to unpack rootfs image as initramfs...
> > [    0.389153] Initialise system trusted keyrings
> > [    0.389318] Key type blacklist registered
> > [    0.390041] workingset: timestamp_bits=43 max_order=25 bucket_order=0
> > [    0.390114] zbud: loaded
> > [    0.396835] fuse: init (API version 7.39)
> > [    0.399678] integrity: Platform Keyring initialized
> > [    0.399734] integrity: Machine keyring initialized
> > [    0.399766] Key type asymmetric registered
> > [    0.399779] Asymmetric key parser 'x509' registered
> > [    3.296324] Freeing initrd memory: 117684K
> > [    3.378869] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 246)
> > [    3.379281] io scheduler mq-deadline registered
> > [    3.391286] pwm_sophgo_probe
> > [    3.391850] cdns-pcie-host 7060000000.pcie: host bridge /pcie@7060000000 ranges:
> > [    3.391899] cdns-pcie-host 7060000000.pcie:       IO 0x40c0000000..0x40c03fffff -> 0x00c0000000
> > [    3.391933] cdns-pcie-host 7060000000.pcie:      MEM 0x40d0000000..0x40dfffffff -> 0x00d0000000
> > [    3.391960] cdns-pcie-host 7060000000.pcie:      MEM 0x40e0000000..0x40ffffffff -> 0x00e0000000
> > [    3.391982] cdns-pcie-host 7060000000.pcie:      MEM 0x4200000000..0x43ffffffff -> 0x4200000000
> > [    3.392002] cdns-pcie-host 7060000000.pcie:      MEM 0x4100000000..0x41ffffffff -> 0x4100000000
> > [    3.392031] cdns-pcie-host 7060000000.pcie: Memory resource size exceeds max for 32 bits
> > [    3.392084] cdns-pcie-host 7060000000.pcie: no phy-names.  PHY will not be initialized
> > [    3.392458] cdns-pcie-host 7060000000.pcie: PCI host bridge to bus 0000:00
> > [    3.392480] pci_bus 0000:00: Unknown NUMA node; performance will be reduced
> > [    3.392495] pci_bus 0000:00: root bus resource [bus 00-3f]
> > [    3.392513] pci_bus 0000:00: root bus resource [io  0x0000-0x3fffff] (bus address [0xc0000000-0xc03fffff])
> > [    3.392531] pci_bus 0000:00: root bus resource [mem 0x40d0000000-0x40dfffffff pref] (bus address [0xd0000000-0xdfffffff])
> > [    3.392548] pci_bus 0000:00: root bus resource [mem 0x40e0000000-0x40ffffffff] (bus address [0xe0000000-0xffffffff])
> > [    3.392562] pci_bus 0000:00: root bus resource [mem 0x4200000000-0x43ffffffff pref]
> > [    3.392576] pci_bus 0000:00: root bus resource [mem 0x4100000000-0x41ffffffff]
> > [    3.392619] pci 0000:00:00.0: [1e30:2042] type 01 class 0x060400
> > [    3.392728] pci 0000:00:00.0: supports D1
> > [    3.392744] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
> > [    3.395695] pci 0000:01:00.0: [1002:6611] type 00 class 0x030000
> > [    3.395758] pci 0000:01:00.0: reg 0x10: [mem 0xc0000000-0xcfffffff 64bit pref]
> > [    3.395797] pci 0000:01:00.0: reg 0x18: [mem 0x40d0000000-0x40d003ffff 64bit]
> > [    3.395824] pci 0000:01:00.0: reg 0x20: initial BAR value 0x00000000 invalid
> > [    3.395837] pci 0000:01:00.0: reg 0x20: [io  size 0x0100]
> > [    3.395876] pci 0000:01:00.0: reg 0x30: [mem 0x40fffe0000-0x40ffffffff pref]
> > [    3.395899] pci 0000:01:00.0: enabling Extended Tags
> > [    3.396031] pci 0000:01:00.0: supports D1 D2
> > [    3.396044] pci 0000:01:00.0: PME# supported from D1 D2 D3hot
> > [    3.396430] pci 0000:01:00.0: vgaarb: setting as boot VGA device
> > [    3.396446] pci 0000:01:00.0: vgaarb: bridge control possible
> > [    3.396458] pci 0000:01:00.0: vgaarb: VGA device added: decodes=io+mem,owns=none,locks=none
> > [    3.396525] pci 0000:01:00.1: [1002:aab0] type 00 class 0x040300
> > [    3.396568] pci 0000:01:00.1: reg 0x10: [mem 0x40d0040000-0x40d0043fff 64bit]
> > [    3.396637] pci 0000:01:00.1: enabling Extended Tags
> > [    3.396744] pci 0000:01:00.1: supports D1 D2
> > [    3.405287] pci_bus 0000:01: busn_res: [bus 01-3f] end is updated to 01
> > [    3.405334] pci 0000:00:00.0: BAR 15: assigned [mem 0x4200000000-0x420fffffff 64bit pref]
> > [    3.405354] pci 0000:00:00.0: BAR 14: assigned [mem 0x40e0000000-0x40e00fffff]
> > [    3.405369] pci 0000:00:00.0: BAR 13: assigned [io  0x1000-0x1fff]
> > [    3.405389] pci 0000:01:00.0: BAR 0: assigned [mem 0x4200000000-0x420fffffff 64bit pref]
> > [    3.405420] pci 0000:01:00.0: BAR 2: assigned [mem 0x40e0000000-0x40e003ffff 64bit]
> > [    3.405449] pci 0000:01:00.0: BAR 6: assigned [mem 0x40e0040000-0x40e005ffff pref]
> > [    3.405463] pci 0000:01:00.1: BAR 0: assigned [mem 0x40e0060000-0x40e0063fff 64bit]
> > [    3.405490] pci 0000:01:00.0: BAR 4: assigned [io  0x1000-0x10ff]
> > [    3.405509] pci 0000:00:00.0: PCI bridge to [bus 01]
> > [    3.405521] pci 0000:00:00.0:   bridge window [io  0x1000-0x1fff]
> > [    3.405535] pci 0000:00:00.0:   bridge window [mem 0x40e0000000-0x40e00fffff]
> > [    3.405549] pci 0000:00:00.0:   bridge window [mem 0x4200000000-0x420fffffff 64bit pref]
> > [    3.405980] pcieport 0000:00:00.0: PME: Signaling with IRQ 45
> > [    3.406441] pcieport 0000:00:00.0: AER: enabled with IRQ 45
> > [    3.406727] pci 0000:01:00.1: D0 power state depends on 0000:01:00.0
> > [    3.406972] cdns-pcie-host 7062000000.pcie: host bridge /pcie@7062000000 ranges:
> > [    3.407016] cdns-pcie-host 7062000000.pcie:       IO 0x48c0800000..0x48c0bfffff -> 0x00c0800000
> > [    3.407047] cdns-pcie-host 7062000000.pcie:      MEM 0x48d0000000..0x48dfffffff -> 0x00d0000000
> > [    3.407071] cdns-pcie-host 7062000000.pcie:      MEM 0x48e0000000..0x48ffffffff -> 0x00e0000000
> > [    3.407094] cdns-pcie-host 7062000000.pcie:      MEM 0x4900000000..0x49ffffffff -> 0x4900000000
> > [    3.407112] cdns-pcie-host 7062000000.pcie:      MEM 0x4a00000000..0x4bffffffff -> 0x4a00000000
> > [    3.407163] cdns-pcie-host 7062000000.pcie: Memory resource size exceeds max for 32 bits
> > [    3.407217] cdns-pcie-host 7062000000.pcie: no phy-names.  PHY will not be initialized
> > [    3.407292] cdns-pcie-host 7062000000.pcie: msi_data is 0xaf000000
> > [    3.407605] cdns-pcie-host 7062000000.pcie: PCI host bridge to bus 0001:80
> > [    3.407624] pci_bus 0001:80: Unknown NUMA node; performance will be reduced
> > [    3.407638] pci_bus 0001:80: root bus resource [bus 80-bf]
> > [    3.407653] pci_bus 0001:80: root bus resource [io  0x400000-0x7fffff] (bus address [0xc0800000-0xc0bfffff])
> > [    3.407670] pci_bus 0001:80: root bus resource [mem 0x48d0000000-0x48dfffffff pref] (bus address [0xd0000000-0xdfffffff])
> > [    3.407687] pci_bus 0001:80: root bus resource [mem 0x48e0000000-0x48ffffffff] (bus address [0xe0000000-0xffffffff])
> > [    3.407702] pci_bus 0001:80: root bus resource [mem 0x4900000000-0x49ffffffff]
> > [    3.407715] pci_bus 0001:80: root bus resource [mem 0x4a00000000-0x4bffffffff pref]
> > [    3.407751] pci 0001:80:00.0: [1e30:2042] type 01 class 0x060400
> > [    3.407849] pci 0001:80:00.0: supports D1
> > [    3.407863] pci 0001:80:00.0: PME# supported from D0 D1 D3hot
> > [    3.410185] pci_bus 0001:81: busn_res: [bus 81-bf] end is updated to 81
> > [    3.410219] pci 0001:80:00.0: PCI bridge to [bus 81]
> > [    3.410439] cdns-pcie-host 7062000000.pcie: msi#0 address_hi 0x0 address_lo 0xaf000000
> > [    3.410588] pcieport 0001:80:00.0: PME: Signaling with IRQ 47
> > [    3.411013] pcieport 0001:80:00.0: AER: enabled with IRQ 47
> > [    3.411311] cdns-pcie-host 4c00000000.pcie: host bridge /pcie@7062800000 ranges:
> > [    3.411355] cdns-pcie-host 4c00000000.pcie:       IO 0x4cc0c00000..0x4cc0ffffff -> 0x00c0c00000
> > [    3.411386] cdns-pcie-host 4c00000000.pcie:      MEM 0x4cf8000000..0x4cfbffffff -> 0x00f8000000
> > [    3.411411] cdns-pcie-host 4c00000000.pcie:      MEM 0x4cfc000000..0x4cffffffff -> 0x00fc000000
> > [    3.411451] cdns-pcie-host 4c00000000.pcie:      MEM 0x4e00000000..0x4fffffffff -> 0x4e00000000
> > [    3.411472] cdns-pcie-host 4c00000000.pcie:      MEM 0x4d00000000..0x4dffffffff -> 0x4d00000000
> > [    3.411502] cdns-pcie-host 4c00000000.pcie: Memory resource size exceeds max for 32 bits
> > [    3.411540] cdns-pcie-host 4c00000000.pcie: no phy-names.  PHY will not be initialized
> > [    3.411711] cdns-pcie-host 4c00000000.pcie: PCI host bridge to bus 0002:c0
> > [    3.411727] pci_bus 0002:c0: Unknown NUMA node; performance will be reduced
> > [    3.411742] pci_bus 0002:c0: root bus resource [bus c0-ff]
> > [    3.411756] pci_bus 0002:c0: root bus resource [io  0x800000-0xbfffff] (bus address [0xc0c00000-0xc0ffffff])
> > [    3.411772] pci_bus 0002:c0: root bus resource [mem 0x4cf8000000-0x4cfbffffff pref] (bus address [0xf8000000-0xfbffffff])
> > [    3.411788] pci_bus 0002:c0: root bus resource [mem 0x4cfc000000-0x4cffffffff] (bus address [0xfc000000-0xffffffff])
> > [    3.411803] pci_bus 0002:c0: root bus resource [mem 0x4e00000000-0x4fffffffff pref]
> > [    3.411816] pci_bus 0002:c0: root bus resource [mem 0x4d00000000-0x4dffffffff]
> > [    3.411850] pci 0002:c0:00.0: [1e30:2042] type 01 class 0x060400
> > [    3.411945] pci 0002:c0:00.0: supports D1
> > [    3.411958] pci 0002:c0:00.0: PME# supported from D0 D1 D3hot
> > [    3.414269] pci 0002:c1:00.0: [1b21:2824] type 01 class 0x060400
> > [    3.414382] pci 0002:c1:00.0: enabling Extended Tags
> > [    3.414540] pci 0002:c1:00.0: PME# supported from D0 D3hot D3cold
> > [    3.425436] pci 0002:c2:00.0: [1b21:2824] type 01 class 0x060400
> > [    3.425551] pci 0002:c2:00.0: enabling Extended Tags
> > [    3.425713] pci 0002:c2:00.0: PME# supported from D0 D3hot D3cold
> > [    3.426443] pci 0002:c2:04.0: [1b21:2824] type 01 class 0x060400
> > [    3.426557] pci 0002:c2:04.0: enabling Extended Tags
> > [    3.426717] pci 0002:c2:04.0: PME# supported from D0 D3hot D3cold
> > [    3.427216] pci 0002:c2:06.0: [1b21:2824] type 01 class 0x060400
> > [    3.427325] pci 0002:c2:06.0: enabling Extended Tags
> > [    3.427483] pci 0002:c2:06.0: PME# supported from D0 D3hot D3cold
> > [    3.427911] pci 0002:c2:07.0: [1b21:2824] type 01 class 0x060400
> > [    3.428019] pci 0002:c2:07.0: enabling Extended Tags
> > [    3.428176] pci 0002:c2:07.0: PME# supported from D0 D3hot D3cold
> > [    3.428579] pci 0002:c2:08.0: [1b21:2824] type 01 class 0x060400
> > [    3.428685] pci 0002:c2:08.0: enabling Extended Tags
> > [    3.428841] pci 0002:c2:08.0: PME# supported from D0 D3hot D3cold
> > [    3.429563] pci 0002:c2:0c.0: [1b21:2824] type 01 class 0x060400
> > [    3.429676] pci 0002:c2:0c.0: enabling Extended Tags
> > [    3.429837] pci 0002:c2:0c.0: PME# supported from D0 D3hot D3cold
> > [    3.430365] pci 0002:c2:0e.0: [1b21:2824] type 01 class 0x060400
> > [    3.430475] pci 0002:c2:0e.0: enabling Extended Tags
> > [    3.430634] pci 0002:c2:0e.0: PME# supported from D0 D3hot D3cold
> > [    3.431059] pci 0002:c2:0f.0: [1b21:2824] type 01 class 0x060400
> > [    3.431165] pci 0002:c2:0f.0: enabling Extended Tags
> > [    3.431322] pci 0002:c2:0f.0: PME# supported from D0 D3hot D3cold
> > [    3.432977] pci_bus 0002:c3: busn_res: [bus c3-ff] end is updated to c3
> > [    3.433313] pci 0002:c4:00.0: [1b21:2142] type 00 class 0x0c0330
> > [    3.433374] pci 0002:c4:00.0: reg 0x10: [mem 0xc0500000-0xc0507fff 64bit]
> > [    3.433470] pci 0002:c4:00.0: enabling Extended Tags
> > [    3.433648] pci 0002:c4:00.0: PME# supported from D0 D3hot D3cold
> > [    3.445242] pci_bus 0002:c4: busn_res: [bus c4-ff] end is updated to c4
> > [    3.445447] pci 0002:c5:00.0: [10ec:8125] type 00 class 0x020000
> > [    3.445493] pci 0002:c5:00.0: reg 0x10: [io  0xc02000-0xc020ff]
> > [    3.445544] pci 0002:c5:00.0: reg 0x18: [mem 0xc0400000-0xc040ffff 64bit]
> > [    3.445581] pci 0002:c5:00.0: reg 0x20: [mem 0xc0410000-0xc0413fff 64bit]
> > [    3.445820] pci 0002:c5:00.0: supports D1 D2
> > [    3.445833] pci 0002:c5:00.0: PME# supported from D0 D1 D2 D3hot D3cold
> > [    3.457248] pci_bus 0002:c5: busn_res: [bus c5-ff] end is updated to c5
> > [    3.457460] pci 0002:c6:00.0: [1106:3483] type 00 class 0x0c0330
> > [    3.457514] pci 0002:c6:00.0: reg 0x10: [mem 0xc0300000-0xc0300fff 64bit]
> > [    3.457697] pci 0002:c6:00.0: PME# supported from D0 D3hot D3cold
> > [    3.458042] pci_bus 0002:c6: busn_res: [bus c6-ff] end is updated to c6
> > [    3.458236] pci 0002:c7:00.0: [1bb1:5027] type 00 class 0x010802
> > [    3.458314] pci 0002:c7:00.0: reg 0x10: [mem 0xc0200000-0xc0203fff 64bit]
> > [    3.459034] pci 0002:c7:00.0: 31.504 Gb/s available PCIe bandwidth, limited by 8.0 GT/s PCIe x4 link at 0002:c2:08.0 (capable of 63.012 Gb/s with 16.0 GT/s PCIe x4 link)
> > [    3.469236] pci_bus 0002:c7: busn_res: [bus c7-ff] end is updated to c7
> > [    3.469427] pci 0002:c8:00.0: [197b:0585] type 00 class 0x010601
> > [    3.469477] pci 0002:c8:00.0: reg 0x10: [io  0xc01200-0xc0127f]
> > [    3.469508] pci 0002:c8:00.0: reg 0x14: [io  0xc01180-0xc011ff]
> > [    3.469538] pci 0002:c8:00.0: reg 0x18: [io  0xc01100-0xc0117f]
> > [    3.469568] pci 0002:c8:00.0: reg 0x1c: [io  0xc01080-0xc010ff]
> > [    3.469597] pci 0002:c8:00.0: reg 0x20: [io  0xc01000-0xc0107f]
> > [    3.469626] pci 0002:c8:00.0: reg 0x24: [mem 0xc0100000-0xc0101fff]
> > [    3.469656] pci 0002:c8:00.0: reg 0x30: [mem 0x4cffff0000-0x4cffffffff pref]
> > [    3.469837] pci 0002:c8:00.0: PME# supported from D3hot
> > [    3.470310] pci_bus 0002:c8: busn_res: [bus c8-ff] end is updated to c8
> > [    3.470513] pci 0002:c9:00.0: [10ec:8125] type 00 class 0x020000
> > [    3.470558] pci 0002:c9:00.0: reg 0x10: [io  0xc00000-0xc000ff]
> > [    3.470609] pci 0002:c9:00.0: reg 0x18: [mem 0xc0000000-0xc000ffff 64bit]
> > [    3.470646] pci 0002:c9:00.0: reg 0x20: [mem 0xc0010000-0xc0013fff 64bit]
> > [    3.470881] pci 0002:c9:00.0: supports D1 D2
> > [    3.470893] pci 0002:c9:00.0: PME# supported from D0 D1 D2 D3hot D3cold
> > [    3.481236] pci_bus 0002:c9: busn_res: [bus c9-ff] end is updated to c9
> > [    3.481585] pci_bus 0002:ca: busn_res: [bus ca-ff] end is updated to ca
> > [    3.481612] pci_bus 0002:c2: busn_res: [bus c2-ff] end is updated to ca
> > [    3.481631] pci_bus 0002:c1: busn_res: [bus c1-ff] end is updated to ca
> > [    3.481676] pci 0002:c0:00.0: BAR 14: assigned [mem 0x4cfc000000-0x4cfc5fffff]
> > [    3.481694] pci 0002:c0:00.0: BAR 13: assigned [io  0x800000-0x802fff]
> > [    3.481712] pci 0002:c1:00.0: BAR 14: assigned [mem 0x4cfc000000-0x4cfc5fffff]
> > [    3.481726] pci 0002:c1:00.0: BAR 13: assigned [io  0x800000-0x802fff]
> > [    3.481746] pci 0002:c2:04.0: BAR 14: assigned [mem 0x4cfc000000-0x4cfc0fffff]
> > [    3.481761] pci 0002:c2:06.0: BAR 14: assigned [mem 0x4cfc100000-0x4cfc1fffff]
> > [    3.481775] pci 0002:c2:07.0: BAR 14: assigned [mem 0x4cfc200000-0x4cfc2fffff]
> > [    3.481789] pci 0002:c2:08.0: BAR 14: assigned [mem 0x4cfc300000-0x4cfc3fffff]
> > [    3.481802] pci 0002:c2:0c.0: BAR 14: assigned [mem 0x4cfc400000-0x4cfc4fffff]
> > [    3.481816] pci 0002:c2:0e.0: BAR 14: assigned [mem 0x4cfc500000-0x4cfc5fffff]
> > [    3.481829] pci 0002:c2:06.0: BAR 13: assigned [io  0x800000-0x800fff]
> > [    3.481842] pci 0002:c2:0c.0: BAR 13: assigned [io  0x801000-0x801fff]
> > [    3.481854] pci 0002:c2:0e.0: BAR 13: assigned [io  0x802000-0x802fff]
> > [    3.481868] pci 0002:c2:00.0: PCI bridge to [bus c3]
> > [    3.481902] pci 0002:c4:00.0: BAR 0: assigned [mem 0x4cfc000000-0x4cfc007fff 64bit]
> > [    3.481937] pci 0002:c2:04.0: PCI bridge to [bus c4]
> > [    3.481954] pci 0002:c2:04.0:   bridge window [mem 0x4cfc000000-0x4cfc0fffff]
> > [    3.481982] pci 0002:c5:00.0: BAR 2: assigned [mem 0x4cfc100000-0x4cfc10ffff 64bit]
> > [    3.482017] pci 0002:c5:00.0: BAR 4: assigned [mem 0x4cfc110000-0x4cfc113fff 64bit]
> > [    3.482050] pci 0002:c5:00.0: BAR 0: assigned [io  0x800000-0x8000ff]
> > [    3.482069] pci 0002:c2:06.0: PCI bridge to [bus c5]
> > [    3.482082] pci 0002:c2:06.0:   bridge window [io  0x800000-0x800fff]
> > [    3.482099] pci 0002:c2:06.0:   bridge window [mem 0x4cfc100000-0x4cfc1fffff]
> > [    3.482125] pci 0002:c6:00.0: BAR 0: assigned [mem 0x4cfc200000-0x4cfc200fff 64bit]
> > [    3.482158] pci 0002:c2:07.0: PCI bridge to [bus c6]
> > [    3.482174] pci 0002:c2:07.0:   bridge window [mem 0x4cfc200000-0x4cfc2fffff]
> > [    3.482200] pci 0002:c7:00.0: BAR 0: assigned [mem 0x4cfc300000-0x4cfc303fff 64bit]
> > [    3.482240] pci 0002:c2:08.0: PCI bridge to [bus c7]
> > [    3.482257] pci 0002:c2:08.0:   bridge window [mem 0x4cfc300000-0x4cfc3fffff]
> > [    3.482284] pci 0002:c8:00.0: BAR 6: assigned [mem 0x4cfc400000-0x4cfc40ffff pref]
> > [    3.482299] pci 0002:c8:00.0: BAR 5: assigned [mem 0x4cfc410000-0x4cfc411fff]
> > [    3.482317] pci 0002:c8:00.0: BAR 0: assigned [io  0x801000-0x80107f]
> > [    3.482334] pci 0002:c8:00.0: BAR 1: assigned [io  0x801080-0x8010ff]
> > [    3.482351] pci 0002:c8:00.0: BAR 2: assigned [io  0x801100-0x80117f]
> > [    3.482368] pci 0002:c8:00.0: BAR 3: assigned [io  0x801180-0x8011ff]
> > [    3.482385] pci 0002:c8:00.0: BAR 4: assigned [io  0x801200-0x80127f]
> > [    3.482403] pci 0002:c2:0c.0: PCI bridge to [bus c8]
> > [    3.482416] pci 0002:c2:0c.0:   bridge window [io  0x801000-0x801fff]
> > [    3.482433] pci 0002:c2:0c.0:   bridge window [mem 0x4cfc400000-0x4cfc4fffff]
> > [    3.482459] pci 0002:c9:00.0: BAR 2: assigned [mem 0x4cfc500000-0x4cfc50ffff 64bit]
> > [    3.482492] pci 0002:c9:00.0: BAR 4: assigned [mem 0x4cfc510000-0x4cfc513fff 64bit]
> > [    3.482525] pci 0002:c9:00.0: BAR 0: assigned [io  0x802000-0x8020ff]
> > [    3.482543] pci 0002:c2:0e.0: PCI bridge to [bus c9]
> > [    3.482556] pci 0002:c2:0e.0:   bridge window [io  0x802000-0x802fff]
> > [    3.482573] pci 0002:c2:0e.0:   bridge window [mem 0x4cfc500000-0x4cfc5fffff]
> > [    3.482597] pci 0002:c2:0f.0: PCI bridge to [bus ca]
> > [    3.482626] pci 0002:c1:00.0: PCI bridge to [bus c2-ca]
> > [    3.482638] pci 0002:c1:00.0:   bridge window [io  0x800000-0x802fff]
> > [    3.482656] pci 0002:c1:00.0:   bridge window [mem 0x4cfc000000-0x4cfc5fffff]
> > [    3.482680] pci 0002:c0:00.0: PCI bridge to [bus c1-ca]
> > [    3.482691] pci 0002:c0:00.0:   bridge window [io  0x800000-0x802fff]
> > [    3.482704] pci 0002:c0:00.0:   bridge window [mem 0x4cfc000000-0x4cfc5fffff]
> > [    3.483107] pcieport 0002:c0:00.0: PME: Signaling with IRQ 48
> > [    3.483596] pcieport 0002:c0:00.0: AER: enabled with IRQ 48
> > [    3.487131] pci 0002:c4:00.0: PME# does not work under D0, disabling it
> > [    3.487164] pci 0002:c4:00.0: enabling device (0000 -> 0002)
> > [    3.487259] pci 0002:c6:00.0: enabling device (0000 -> 0002)
> > [    3.488568] EINJ: ACPI disabled.
> > [    3.488589] ERST DBG: ERST support is disabled.
> > [    3.492343] no vdmabuf_reserved_memory node
> > [    3.492365] virtio-vdmabuf: carveout buf not setup -22
> > [    3.493828] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
> > [    3.496550] printk: console [ttyS0] disabled
> > [    3.496941] 7040000000.serial: ttyS0 at MMIO 0x7040000000 (irq = 57, base_baud = 31250000) is a 16550A
> > [    3.497008] printk: console [ttyS0] enabled
> > [    6.653616] 7040001000.serial: ttyS1 at MMIO 0x7040001000 (irq = 58, base_baud = 31250000) is a 16550A
> > [    6.664291] 7040002000.serial: ttyS2 at MMIO 0x7040002000 (irq = 59, base_baud = 31250000) is a 16550A
> > [    6.674993] 7040003000.serial: ttyS3 at MMIO 0x7040003000 (irq = 60, base_baud = 31250000) is a 16550A
> > [    6.691432] nvme nvme0: pci function 0002:c7:00.0
> > [    6.693487] mousedev: PS/2 mouse device common for all mice
> > [    6.703782] sdhci: Secure Digital Host Controller Interface driver
> > [    6.710021] sdhci: Copyright(c) Pierre Ossman
> > [    6.711847] hwmon hwmon0: temp1_input not attached to any thermal zone
> > [    6.714740] sdhci-pltfm: SDHCI platform and OF driver helper
> > [    6.721065] hwmon hwmon0: temp2_input not attached to any thermal zone
> > [    6.737204] ledtrig-cpu: registered to indicate activity on CPUs
> > [    6.743578] pstore: Using crash dump compression: deflate
> > [    6.749064] pstore: Registered efi_pstore as persistent store backend
> > [    6.756324] riscv-pmu-sbi: SBI PMU extension is available
> > [    6.761974] riscv-pmu-sbi: 16 firmware and 31 hardware counters
> > [    6.774971] NET: Registered PF_INET6 protocol family
> > [    6.775258] nvme nvme0: allocated 64 MiB host memory buffer.
> > [    6.792744] nvme nvme0: 1/0/0 default/read/poll queues
> > [    6.798818] Segment Routing with IPv6
> > [    6.802615] In-situ OAM (IOAM) with IPv6
> > [    6.806651] mip6: Mobile IPv6
> > [    6.809657] NET: Registered PF_PACKET protocol family
> > [    6.814951] mpls_gso: MPLS GSO support
> > [    6.826385] registered taskstats version 1
> > [    6.828554]  nvme0n1: p1 p2 p3
> > [    6.832483] Loading compiled-in X.509 certificates
> > [    6.881423] Loaded X.509 cert 'Build time autogenerated kernel key: a949a38ba7402beaa827889ff304b05fc9df7c05'
> > [    6.910444] Key type .fscrypt registered
> > [    6.914452] Key type fscrypt-provisioning registered
> > [    6.931636] Key type encrypted registered
> > [    6.935707] AppArmor: AppArmor sha1 policy hashing enabled
> > [    6.941498] ima: No TPM chip found, activating TPM-bypass!
> > [    6.947038] ima: Allocated hash algorithm: sha256
> > [    6.951806] ima: No architecture policies found
> > [    6.956459] evm: Initialising EVM extended attributes:
> > [    6.961618] evm: security.selinux
> > [    6.964937] evm: security.SMACK64 (disabled)
> > [    6.969217] evm: security.SMACK64EXEC (disabled)
> > [    6.973848] evm: security.SMACK64TRANSMUTE (disabled)
> > [    6.978909] evm: security.SMACK64MMAP (disabled)
> > [    6.983536] evm: security.apparmor
> > [    6.986948] evm: security.ima
> > [    6.989927] evm: security.capability
> > [    6.993513] evm: HMAC attrs: 0x1
> > [    7.247426] clk: Disabling unused clocks
> > [    7.256860] Freeing unused kernel image (initmem) memory: 2712K
> > [   10.882016] r8169 0002:c9:00.0 eth1: RTL8125B, 00:e0:4c:68:02:e6, XID 641, IRQ 68
> > 1;-1f[   10.882032] r8169 0002:c9:00.0 eth1: jumbo features [frames: 9194 bytes, tx checksumming: ko]
> > [   10.889827] xhci_hcd 0002:c4:00.0: xHCI Host Controller
> > [   10.891369] r8169 0002:c5:00.0 enP2p197s0: renamed from eth0
> > [   10.896488] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   10.904233] xhci_hcd 0002:c4:00.0: new USB bus registered, assigned bus number 2
> > [   10.904253] xhci_hcd 0002:c4:00.0: Host supports USB 3.1 Enhanced SuperSpeed
> > [   10.905580] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   10.913690] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.06
> > [   10.962246] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> > [   10.962253] usb usb1: Product: xHCI Host Controller
> > [   10.962257] usb usb1: Manufacturer: Linux 6.6.127+ xhci-hcd
> > [   10.962261] usb usb1: SerialNumber: 0002:c4:00.0
> > [   10.962987] hub 1-0:1.0: USB hub found
> > [   10.988466] hub 1-0:1.0: 2 ports detected
> > [   10.989373] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   10.991053] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
> > [   10.991187] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.06
> > [   10.991197] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> > [   10.991204] usb usb2: Product: xHCI Host Controller
> > [   10.991208] usb usb2: Manufacturer: Linux 6.6.127+ xhci-hcd
> > [   10.991212] usb usb2: SerialNumber: 0002:c4:00.0
> > [   10.991915] hub 2-0:1.0: USB hub found
> > [   10.991958] hub 2-0:1.0: 2 ports detected
> > [   10.992696] xhci_hcd 0002:c6:00.0: xHCI Host Controller
> > [   11.001456] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   11.008198] xhci_hcd 0002:c6:00.0: new USB bus registered, assigned bus number 3
> > [   11.016938] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [  OK  ] Finished dracut initqueue hook.
> > [  OK  ] Found device Seagate ZP2048CM30003 oERV.
> > [  OK  ] Reached target Initrd Root Device.
> > [  OK  ] Reached target Preparation for Remote File Systems.
> > [  OK  ] Reached target Remote File Systems.
> >          Starting dracut pre-mount hook...
> > [  OK  ] Started Show Plymouth Boot Screen.
> > [  OK  ] Started Forward Password Requests to Plymouth Directory Watch.
> > [  OK  ] Reached target Path Units.
> > [  OK  ] Reached target Basic System.
> > [  OK  ] Stopped Virtual Console Setup.
> >          Stopping Virtual Console Setup...
> >          Starting Virtual Console Setup...
> > [  OK  ] Finished dracut pre-mount hook.
> >          Starting File System Check on /dev/nvme0n1p3...
> > [   11.245223] usb 1-1: new high-speed USB device number 2 using xhci_hcd
> > [  OK  ] Finished File System Check on /dev/nvme0n1p3.
> >          Mounting /sysroot...
> > [   11.385246] EXT4-fs (nvme0n1p3): mounted filesystem 07617bd8-13da-4749-97a3-2b548687b739 ro with ordered data mode. Quota mode: none.
> > [   11.400683] usb 1-1: New USB device found, idVendor=2109, idProduct=2822, bcdDevice= 7.94
> > [   11.408909] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> > [   11.408916] usb 1-1: Product: USB2.0 Hub             
> > [  OK  ] Mounted    11.408921] usb 1-1: Manufacturer: VIA Labs, Inc.         
> > 1;39m/sysroot.
> > [   11.408925] usb 1-1: SerialNumber: 000000001
> > [   11.414710] hub 1-1:1.0: USB hub found
> > [   11.439385] hub 1-1:1.0: 4 ports detected
> > [  OK  ] Reached target Initrd Root File System.
> >          Starting Mountpoints Configured in the Real Root...
> > [  OK  ] Finished Mountpoints Configured in the Real Root.
> > [  OK  ] Reached target    11.542161] usb 2-1: new SuperSpeed USB device number 2 using xhci_hcd
> > mInitrd File Systems.
> > [  OK  ] Reached target Initrd Default Target.
> >          Starting dracut pre-pivot and cleanup hook...
> > [   11.573510] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   11.581589] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   11.674720] scsi host0: ahci
> > [   11.678766] xhci_hcd 0002:c6:00.0: hcc params 0x002841eb hci version 0x100 quirks 0x0000200000000890
> > [   11.679164] scsi host1: ahci
> > [   11.689257] xhci_hcd 0002:c6:00.0: xHCI Host Controller
> > [   11.692134] scsi host2: ahci
> > [   11.696523] xhci_hcd 0002:c6:00.0: new USB bus registered, assigned bus number 4
> > [   11.701654] scsi host3: ahci
> > [   11.702289] r8169 0002:c9:00.0 enP2p201s0: renamed from eth1
> > [   11.705361] [drm] radeon kernel modesetting enabled.
> > [   11.705529] radeon 0000:01:00.0: vgaarb: deactivate vga console
> > [   11.706618] xhci_hcd 0002:c6:00.0: Host supports USB 3.0 SuperSpeed
> > [   11.710666] scsi host4: ahci
> > [   11.715888] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.06
> > [   11.721238] ata1: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410100 irq 66
> > [   11.726370] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> > [   11.726394] ata2: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410180 irq 66
> > [   11.726410] usb usb3: Product: xHCI Host Controller
> > [   11.726426] ata3: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410200 irq 66
> > [   11.726437] usb usb3: Manufacturer: Linux 6.6.127+ xhci-hcd
> > [   11.726451] ata4: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410280 irq 66
> > [   11.726460] usb usb3: SerialNumber: 0002:c6:00.0
> > [   11.726472] ata5: SATA max UDMA/133 abar m8192@0x4cfc410000 port 0x4cfc410300 irq 66
> > [   11.727467] hub 3-0:1.0: USB hub found
> > [   11.735813] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   11.744126] hub 3-0:1.0: 1 port detected
> > [   11.752345] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   11.760122] usb usb4: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.06
> > [   11.768558] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   11.771859] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> > [   11.771870] usb usb4: Product: xHCI Host Controller
> > [   11.771876] usb usb4: Manufacturer: Linux 6.6.127+ xhci-hcd
> > [   11.772432] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   11.779686] usb usb4: SerialNumber: 0002:c6:00.0
> > [   11.874317] radeon 0000:01:00.0: enabling device (0006 -> 0007)
> > [   11.874856] hub 4-0:1.0: USB hub found
> > [   11.880999] [drm] initializing kernel modesetting (OLAND 0x1002:0x6611 0x1642:0x1601 0x87).
> > [   11.884201] hub 4-0:1.0: 4 ports detected
> > [   11.898907] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   11.906904] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   11.920679] usb 2-1: New USB device found, idVendor=2109, idProduct=0822, bcdDevice= 7.94
> > [   11.928938] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> > [   11.936115] usb 2-1: Product: USB3.1 Hub             
> > [   11.941209] usb 2-1: Manufacturer: VIA Labs, Inc.         
> > [   11.946728] usb 2-1: SerialNumber: 000000001
> > [   11.957650] hub 2-1:1.0: USB hub found
> > [   11.961924] hub 2-1:1.0: 4 ports detected
> > [   12.041196] usb 1-2: new high-speed USB device number 3 using xhci_hcd
> > [   12.047693] ata1: SATA link down (SStatus 0 SControl 300)
> > [  OK  ] Finished Virtual Console Setup.
> > [   12.072425] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   12.080726] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   12.196393] usb 1-2: New USB device found, idVendor=2109, idProduct=2822, bcdDevice= 7.94
> > [   12.204612] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> > [   12.211783] usb 1-2: Product: USB2.0 Hub             
> > [   12.211882] ATOM BIOS: C57701
> > [   12.216863] usb 1-2: Manufacturer: VIA Labs, Inc.         
> > [   12.216871] usb 1-2: SerialNumber: 000000001
> > [   12.223839] hub 1-2:1.0: USB hub found
> > [   12.225548] radeon 0000:01:00.0: VRAM: 2048M 0x0000000000000000 - 0x000000007FFFFFFF (2048M used)
> > [   12.229807] hub 1-2:1.0: 4 ports detected
> > [   12.233471] radeon 0000:01:00.0: GTT: 2048M 0x0000000080000000 - 0x00000000FFFFFFFF
> > [   12.233479] [drm] Detected VRAM RAM=2048M, BAR=256M
> > [   12.233484] [drm] RAM width 64bits DDR
> > [   12.233996] [drm] radeon: 2048M of VRAM memory ready
> > [   12.267754] [drm] radeon: 2048M of GTT memory ready.
> > [   12.272791] [drm] Loading oland Microcode
> > [   12.279651] [drm] Internal thermal controller with fan control
> > [   12.296355] [drm] radeon: dpm initialized
> > [   12.304205] [drm] GART: num cpu pages 524288, num gpu pages 524288
> > [   12.329186] usb 1-1.4: new full-speed USB device number 4 using xhci_hcd
> > [   12.345770] [drm] PCIE GART of 2048M enabled (table at 0x0000000000165000).
> > [   12.352936] radeon 0000:01:00.0: WB enabled
> > [   12.357188] radeon 0000:01:00.0: fence driver on ring 0 use gpu addr 0x0000000080000c00
> > [   12.357196] usb 3-1: new high-speed USB device number 2 using xhci_hcd
> > [   12.365218] radeon 0000:01:00.0: fence driver on ring 1 use gpu addr 0x0000000080000c04
> > [   12.365225] radeon 0000:01:00.0: fence driver on ring 2 use gpu addr 0x0000000080000c08
> > [   12.365230] radeon 0000:01:00.0: fence driver on ring 3 use gpu addr 0x0000000080000c0c
> > [   12.365234] radeon 0000:01:00.0: fence driver on ring 4 use gpu addr 0x0000000080000c10
> > [   12.366896] radeon 0000:01:00.0: fence driver on ring 5 use gpu addr 0x0000000000075a18
> > [   12.367665] ata2: SATA link down (SStatus 0 SControl 300)
> > [   12.373928] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   12.380499] radeon 0000:01:00.0: radeon: using MSI.
> > [   12.388370] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   12.396048] [drm] radeon: irq initialized.
> > [   12.522840] usb 3-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.20
> > [   12.531066] usb 3-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
> > [   12.538240] usb 3-1: Product: USB2.0 Hub
> > [   12.577094] usb 1-1.4: New USB device found, idVendor=09da, idProduct=fa10, bcdDevice= 0.77
> > [   12.585483] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
> > [   12.592826] usb 1-1.4: Product: USB Device 
> > [   12.596623] [drm] ring test on 0 succeeded in 1 usecs
> > [   12.597042] usb 1-1.4: Manufacturer: COMPANY 
> > [   12.602114] [drm] ring test on 1 succeeded in 1 usecs
> > [   12.607827] hub 3-1:1.0: USB hub found
> > [   12.611593] [drm] ring test on 2 succeeded in 1 usecs
> > [   12.611606] [drm] ring test on 3 succeeded in 3 usecs
> > [   12.611781] hub 3-1:1.0: 4 ports detected
> > [   12.615402] [drm] ring test on 4 succeeded in 3 usecs
> > [   12.625523] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   12.642608] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   12.651342] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   12.683753] ata3: SATA link down (SStatus 0 SControl 300)
> > [   12.701892] usb 2-2: new SuperSpeed USB device number 3 using xhci_hcd
> > [   12.762424] usb 2-2: New USB device found, idVendor=2109, idProduct=0822, bcdDevice= 7.94
> > [   12.770630] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> > [   12.777807] usb 2-2: Product: USB3.1 Hub             
> > [   12.782919] usb 2-2: Manufacturer: VIA Labs, Inc.         
> > [   12.788437] usb 2-2: SerialNumber: 000000001
> > [   12.792537] [drm] ring test on 5 succeeded in 2 usecs
> > [   12.797806] [drm] UVD initialized successfully.
> > [   12.800383] hub 2-2:1.0: USB hub found
> > [   12.802695] [drm] ib test on ring 0 succeeded in 0 usecs
> > [   12.806694] hub 2-2:1.0: 4 ports detected
> > [   12.811543] [drm] ib test on ring 1 succeeded in 0 usecs
> > [   12.811580] [drm] ib test on ring 2 succeeded in 0 usecs
> > [   12.826254] [drm] ib test on ring 3 succeeded in 0 usecs
> > [   12.831620] [drm] ib test on ring 4 succeeded in 0 usecs
> > [   12.921074] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   12.930025] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   13.003736] ata4: SATA link down (SStatus 0 SControl 300)
> > [   13.323673] ata5: SATA link down (SStatus 0 SControl 300)
> > [   13.416500] hid: raw HID events driver (C) Jiri Kosina
> > [   13.434630] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   13.443852] usbcore: registered new interface driver usbhid
> > [   13.449517] usbhid: USB HID core driver
> > [   13.451652] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   13.461802] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   13.470927] input: COMPANY  USB Device  as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.0/0003:09DA:FA10.0001/input/input32
> > [   13.497319] [drm] ib test on ring 5 succeeded
> > [   13.503488] [drm] Radeon Display Connectors
> > [   13.507749] [drm] Connector 0:
> > [   13.510849] [drm]   HDMI-A-1
> > [   13.513757] [drm]   HPD2
> > [   13.516294] [drm]   DDC: 0x6530 0x6530 0x6534 0x6534 0x6538 0x6538 0x653c 0x653c
> > [   13.523720] [drm]   Encoders:
> > [   13.526712] [drm]     DFP1: INTERNAL_UNIPHY
> > [   13.530918] [drm] Connector 1:
> > [   13.533995] [drm]   VGA-1
> > [   13.536618] [drm]   DDC: 0x65c0 0x65c0 0x65c4 0x65c4 0x65c8 0x65c8 0x65cc 0x65cc
> > [   13.544033] [drm]   Encoders:
> > [   13.547022] [drm]     CRT1: INTERNAL_KLDSCP_DAC1
> > [   13.552882] [drm] Initialized radeon 2.50.0 20080528 for 0000:01:00.0 on minor 0
> > [   13.649535] [drm] fb mappable at 0x4200571000
> > [   13.653933] [drm] vram apper at 0x4200000000
> > [   13.658245] [drm] size 8294400
> > [   13.661326] [drm] fb depth is 24
> > [   13.664557] [drm]    pitch is 7680
> > [   13.821511] hid-generic 0003:09DA:FA10.0001: input,hidraw0: USB HID v1.11 Keyboard [COMPANY  USB Device ] on usb-0002:c4:00.0-1.4/input0
> > [   13.822032] input: COMPANY  USB Device  as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.1/0003:09DA:FA10.0002/input/input33
> > [   13.823145] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   13.823500] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   13.824169] hid-generic 0003:09DA:FA10.0002: input,hidraw1: USB HID v1.11 Mouse [COMPANY  USB Device ] on usb-0002:c4:00.0-1.4/input1
> > [   13.824963] input: COMPANY  USB Device  Keyboard as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.2/0003:09DA:FA10.0003/input/input36
> > [   13.826076] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   13.826385] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   13.828024] Console: switching to colour frame buffer device 240x67
> > [   13.885382] input: COMPANY  USB Device  as /devices/platform/4c00000000.pcie/pci0002:c0/0002:c0:00.0/0002:c1:00.0/0002:c2:04.0/0002:c4:00.0/usb1/1-1/1-1.4/1-1.4:1.2/0003:09DA:FA10.0003/input/input37
> > [   13.885475] radeon 0000:01:00.0: [drm] fb0: radeondrmfb frame buffer device
> > [   13.886262] hid-generic 0003:09DA:FA10.0003: input,hiddev0,hidraw2: USB HID v1.11 Keyboard [COMPANY  USB Device ] on usb-0002:c4:00.0-1.4/input2
> > [   13.976925] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [  OK  ] Stopped    13.986432] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > 1;39mVirtual Console Setup.
> >          Stopping Vir[   13.999301] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > tual Console Setup...
> > [   14.009787] gpio-keys soc:gpio-restart: there is not valid maps for state default
> >          Starting Virtual Console Setup...
> > [  OK  ] Finished Virtual Console Setup.
> > [   32.115772] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   32.124451] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   32.162575] platform soc:gpio-poweroff: deferred probe pending
> > [   32.168564] platform soc:gpio-restart: deferred probe pending
> > [   32.174460] platform 704002a000.bm-emmc: deferred probe pending
> > [   32.180526] platform 704002b000.bm-sd: deferred probe pending
> > [   32.186415] platform 7030005000.i2c: deferred probe pending
> > [   32.192119] platform 7030006000.i2c: deferred probe pending
> > [   32.197825] platform 7030007000.i2c: deferred probe pending
> > [   32.203524] platform 7030008000.i2c: deferred probe pending
> > [   32.210850] [drm] amdgpu kernel modesetting enabled.
> > [  OK  ] Finished dracut pre-pivot and cleanup hook.
> >          Starting Cleaning Up and Shutting Down Daemons...
> > [  OK  ] Stopped target Timer Units.
> > [  OK  ] Stopped dracut pre-pivot and cleanup hook.
> > [  OK  ] Stopped target Initrd Default Target.
> > [  OK  ] Stopped target Basic System.
> > [  OK  ] Stopped target Initrd Root Device.
> > [  OK  ] Stopped target Initrd /usr File System.
> > [  OK  ] Stopped target Path Units.
> > [  OK  ] Stopped target Remote File Systems.
> > [  OK  ] Stopped target Preparation for Remote File Systems.
> > [  OK  ] Stopped target Slice Units.
> > [  OK  ] Stopped target Socket Units.
> > [  OK  ] Stopped target System Initialization.
> > [  OK  ] Stopped target Swaps.
> > [  OK  ] Stopped dracut pre-mount hook.
> > [  OK  ] Stopped dracut initqueue hook.
> > [  OK  ] Stopped Create List of Static Device Nodes.
> >          Starting Plymouth switch root service...
> > [  OK  ] Stopped Apply Kernel Variables.
> > [  OK  ] Stopped Create Volatile Files and Directories.
> > [  OK  ] Stopped target Local File Systems.
> > [  OK  ] Stopped target Preparation for Local File Systems.
> > [  OK  ] Stopped Coldplug All udev Devices.
> > [  OK  ] Stopped dracut pre-trigger hook.
> >          Stopping Rule-based Manager for Device Events and Files...
> > [  OK  ] Finished Cleaning Up and Shutting Down Daemons.
> > [  OK  ] Finished Plymouth switch root service.
> > [  OK  ] Stopped Rule-based Manager for Device Events and Files.
> > [  OK  ] Closed udev Control Socket.
> > [  OK  ] Closed udev Kernel Socket.
> > [  OK  ] Stopped dracut pre-udev hook.
> > [  OK  ] Stopped dracut cmdline hook.
> >          Starting Cleanup udev Database...
> > [  OK  ] Stopped Create Static Device Nodes in /dev.
> > [  OK  ] Finished Cleanup udev Database.
> > [  OK  ] Reached target Switch Root.
> >          Starting Switch Root...
> > [   33.209267] systemd-journald[606]: Received SIGTERM from PID 1 (systemd).
> > [   33.620485] systemd[1]: systemd v255-34.oe2403sp1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA -SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDIS)
> > [   33.664117] systemd[1]: Detected architecture riscv64.
> > 
> > Welcome to openEuler 24.03 (LTS-SP1)!
> > 
> > [   33.680609] systemd[1]: Hostname set to <openeuler-riscv64>.
> > [   34.006662] systemd[1]: /usr/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file acc.
> > [   34.460534] systemd[1]: initrd-switch-root.service: Deactivated successfully.
> > [   34.474062] systemd[1]: Stopped Switch Root.
> > [   34.487965] systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 1.
> > [  OK  ] Stopped Switch Root.
> > [   34.505914] systemd[1]: Created slice Slice /system/getty.
> > [  OK  ] Created slice Slice /system/getty.
> > [   34.518916] systemd[1]: Created slice Slice /system/modprobe.
> > [  OK  ] Created slice Slice /system/modprobe.
> > [   34.532925] systemd[1]: Created slice Slice /system/serial-getty.
> > [  OK  ] Created slice Slice /system/serial-getty.
> > [   34.547392] systemd[1]: Created slice Slice /system/sshd-keygen.
> > [  OK  ] Created slice Slice /system/sshd-keygen.
> > [   34.561592] systemd[1]: Created slice User and Session Slice.
> > [  OK  ] Created slice User and Session Slice.
> > [   34.573784] systemd[1]: Dispatch Password Requests to Console Directory Watch was skipped because of an unmet condition check (ConditionPathExists=!/run/plymouth/pid).
> > [   34.574193] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
> > [  OK  ] Started Forward Password Requests to Wall Directory Watch.
> > [   34.610316] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
> > [  OK  ] Set up automount Arbitrary Executable File Formats File System Automount Point.
> > [   34.628480] systemd[1]: Stopped target Switch Root.
> > [  OK  ] Stopped target Switch Root.
> > [   34.643364] systemd[1]: Stopped target Initrd File Systems.
> > [  OK  ] Stopped target Initrd File Systems.
> > [   34.658685] systemd[1]: Stopped target Initrd Root File System.
> > [   34.674425] systemd[1]: Reached target Path Units.
> > [  OK  ] Stopped target Initrd Root File System.
> > [   34.684328] systemd[1]: Reached target rpc_pipefs.target.
> > [  OK  ] Reached target Path Units.
> > [   34.699508] systemd[1]: Reached target Slice Units.
> > [  OK  ] Reached target rpc_pipefs.target.
> > [   34.714393] systemd[1]: Reached target Swaps.
> > [  OK  ] Reached target Slice Units.
> > [  OK  ] Reached target Swaps.
> > [   34.729511] systemd[1]: Listening on Device-mapper event daemon FIFOs.
> > [   34.749456] systemd[1]: Listening on LVM2 poll daemon socket.
> > [  OK  ] Listening on Device-mapper event daemon FIFOs.
> > [   34.763014] systemd[1]: Listening on RPCbind Server Activation Socket.
> > [  OK  ] Listening on LVM2 poll daemon socket.
> > [   34.779158] systemd[1]: Reached target RPC Port Mapper.
> > [  OK  ] Listening on RPCbind Server Activation Socket.
> > [  OK  ] Reached target RPC Port Mapper.
> > [   34.800509] systemd[1]: Listening on Process Core Dump Socket.
> > [  OK  ] Listening on Process Core Dump Socket.
> > [   34.817575] systemd[1]: Listening on initctl Compatibility Named Pipe.
> > [  OK  ] Listening on initctl Compatibility Named Pipe.
> > [   34.835866] systemd[1]: Listening on udev Control Socket.
> > [  OK  ] Listening on udev Control Socket.
> > [   34.851731] systemd[1]: Listening on udev Kernel Socket.
> > [  OK  ] Listening on udev Kernel Socket.
> > [   34.901469] systemd[1]: Mounting Huge Pages File System...
> >          Mounting Huge Pages File System...
> > [   34.921586] systemd[1]: Mounting POSIX Message Queue File System...
> >          Mounting POSIX Message Queue File System...
> > [   34.946587] systemd[1]: Mounting Kernel Debug File System...
> >          Mounting Kernel Debug File System...
> > [   34.969333] systemd[1]: Mounting Kernel Trace File System...
> >          Mounting Kernel Trace File System...
> > [   34.991219] systemd[1]: Mounting Temporary Directory /tmp...
> >          Mounting Temporary Directory /tmp...
> > [   35.002823] systemd[1]: Kernel Module supporting RPCSEC_GSS was skipped because of an unmet condition check (ConditionPathExists=/etc/krb5.keytab).
> > [   35.008768] systemd[1]: Starting Create List of Static Device Nodes...
> >          Starting Create List of Static Device Nodes...
> > [   35.045982] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
> >          Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
> > [   35.065358] systemd[1]: Starting Load Kernel Module configfs...
> >          Starting Load Kernel Module configfs...
> > [   35.087331] systemd[1]: Starting Load Kernel Module drm...
> >          Starting Load Kernel Module drm...
> > [   35.107834] systemd[1]: Starting Load Kernel Module fuse...
> >          Starting Load Kernel Module fuse...
> > [   35.122507] systemd[1]: plymouth-switch-root.service: Deactivated successfully.
> > [   35.123189] systemd[1]: Stopped Plymouth switch root service.
> > [  OK  ] Stopped Plymouth switch root service.
> > [   35.152572] systemd[1]: systemd-fsck-root.service: Deactivated successfully.
> > [   35.153217] systemd[1]: Stopped File System Check on Root Device.
> > [  OK  ] Stopped File System Check on Root Device.
> > [   35.188134] systemd[1]: Starting Journal Service...
> >          Starting Journal Service...
> > [   35.198581] systemd[1]: Load Kernel Modules was skipped because no trigger condition checks were met.
> > [   35.203780] systemd[1]: Starting Generate network units from Kernel command line...
> >          Starting Generate network units from Kernel command line...
> > [   35.233827] systemd[1]: Starting Remount Root and Kernel File Systems...
> >          Starting Remount Root and Kernel File Systems...
> > [   35.250723] systemd[1]: Starting Apply Kernel Variables...
> >          Starting Apply Kernel Variables...
> > [   35.267004] systemd[1]: Starting Coldplug All udev Devices...
> >          Starting Coldplug All udev Devices...
> > [   35.281708] systemd-journald[1201]: Collecting audit messages is disabled.
> > [   35.282511] systemd[1]: Mounted Huge Pages File System.
> > [  OK  ] Mounted Huge Pages File System.
> > [   35.305714] systemd[1]: Mounted POSIX Message Queue File System.
> > [   35.315684] EXT4-fs (nvme0n1p3): re-mounted 07617bd8-13da-4749-97a3-2b548687b739 r/w.
> > [  OK  ] Mounted POSIX Message Queue File System.
> > [   35.335786] systemd[1]: Started Journal Service.
> > [  OK  ] Started Journal Service.
> > [  OK  ] Mounted Kernel Debug File System.
> > [  OK  ] Mounted Kernel Trace File System.
> > [  OK  ] Mounted Temporary Directory /tmp.
> > [  OK  ] Finished Create List of Static Device Nodes.
> > [  OK  ] Finished Load Kernel Module configfs.
> > [  OK  ] Finished Load Kernel Module drm.
> > [  OK  ] Finished Load Kernel Module fuse.
> > [  OK  ] Finished Generate network units from Kernel command line.
> > [  OK  ] Finished Remount Root and Kernel File Systems.
> >          Mounting FUSE Control File System...
> >          Mounting Kernel Configuration File System...
> >          Starting Flush Journal to Persistent Storage...
> >          Starting Load/Save OS Random Seed...
> >          Starting Create Static Device Nodes in /dev gracefully...
> > [  OK  ] Mounted FUSE Control File System.
> > [  OK  ] Mounted Kernel Configuration File System.
> > [  OK  ] Finished Apply Kernel Variables.
> > [   35.526662] systemd-journald[1201]: Received client request to flush runtime journal.
> > [   35.550024] systemd-journald[1201]: /var/log/journal/552c396b6af0485990643f5de1788949/system.journal: Realtime clock jumped backwards relative to last journal entry, rotating.
> > [  OK  ] Finished    35.568502] systemd-journald[1201]: Rotating system journal.
> > ;1;39mCreate Static Device Nodes in /dev gracefully.
> >          Starting Create Static Device Nodes in /dev...
> > [  OK  ] Finished Create Static Device Nodes in /dev.
> >          Starting Rule-based Manager for Device Events and Files...
> > [  OK  ] Finished Flush Journal to Persistent Storage.
> > [  OK  ] Started Rule-based Manager for Device Events and Files.
> >          Starting Load Kernel Module fuse...
> > [  OK  ] Finished Coldplug All udev Devices.
> > [  OK  ] Finished Load Kernel Module fuse.
> > [   36.191287] sophgo-spifmc 7000180000.flash-controller: gd25lb512me (65536 Kbytes)
> > [  OK  ] Stopped Virtual Console Setup.
> >          Stopping Virtual Console Setup...
> > [   36.221724] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   36.225775] sophgo-spifmc 7002180000.flash-controller: gd25lb512me (65536 Kbytes)
> > [   36.232401] gpio-keys soc:gpio-restart: there is not valid maps for state default
> >          Starting Virtual Console Setup...
> > [   36.256299] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   36.256647] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   36.273598] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
> > [   36.290837] snd_hda_intel 0000:01:00.1: Force to snoop mode by module option
> > [   36.306357] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   36.316354] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [  OK  ] Finished Virtual Console Setup.
> > [   36.617211] random: crng init done
> > [  OK  ] Finished Load/Save OS Random Seed.
> > [  OK  ] Finished Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
> > [  OK  ] Reached target Preparation for Local File Systems.
> >          Mounting /boot...
> > [   36.760150] FAT-fs (nvme0n1p2): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> > [  OK  ] Mounted /boot.
> >          Mounting /boot/efi...
> > [   36.833966] FAT-fs (nvme0n1p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> > [  OK  ] Mounted /boot/efi.
> > [  OK  ] Reached target Local File Systems.
> >          Starting Tell Plymouth To Write Out Runtime Data...
> >          Starting Create Volatile Files and Directories...
> > [  OK  ] Finished Tell Plymouth To Write Out Runtime Data.
> > [  OK  ] Finished Create Volatile Files and Directories.
> >          Starting Security Auditing Service...
> >          Starting RPC Bind...
> > [  OK  ] Started RPC Bind.
> > [  OK  ] Started Security Auditing Service.
> >          Starting Record System Boot/Shutdown in UTMP...
> > [  OK  ] Finished Record System Boot/Shutdown in UTMP.
> > [  OK  ] Reached target System Initialization.
> > [  OK  ] Started dnf makecache --timer.
> > [  OK  ] Started Daily Cleanup of Temporary Dire[   37.309183] snd_hda_intel 0000:01:00.1: azx_get_response timeout, switching to polling mode: last cmd=0x000f0000
> > ctories.
> > [  OK  ] Reached target Timer Units.
> > [  OK  [   37.323629] snd_hda_intel 0000:01:00.1: bound 0000:01:00.0 (ops radeon_audio_component_bind_ops [radeon])
> > ] Listening on D-Bus System Message Bus Socket.
> > [  OK  ] Listening on PC/SC Smart Card Daemon[   37.341862] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> >  Activation Socket.
> > [   37.342172] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > 2m  OK  ] Reached target    37.345625] input: HDA ATI HDMI HDMI/DP,pcm=3 as /devices/platform/7060000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.1/sound/card0/input52
> > ;1;39mSocket Units.
> > [  OK  ] Reached target Basic System.
> >          Starting NTP client/server...
> >          Starting D-Bus System Message Bus...
> >          Starting Restore /run/initramfs on shutdown...
> >          Starting Update RTC With System Clock...
> >          Starting irqbalance daemon...
> > [  OK  ] Started libstoragemgmt plug-in server daemon.
> > [  OK  ] Started resize rootfs.
> > [  OK  ] Started Hardware RNG Entropy Gatherer Daemon.
> >          Starting Self Monitoring and Reporting Technology (SMART) Daemon...
> > [  OK  ] Reached target sshd-keygen.target.
> >          Starting User Login Management...
> >          Starting Run a configured list of systemtap scripts at system startup....
> > [  OK  ] Started D-Bus System Message Bus.
> > [  OK  ] Finished Restore /run/initramfs on shutdown.
> > [  OK  ] Finished Update RTC With System Clock.
> > [  OK  ] Started irqbalance daemon.
> > [  OK  ] Reached target Sound Card.
> >          Starting firewalld - dynamic firewall daemon...
> > [  OK  ] Started Self Monitoring and Reporting Technology (SMART) Daemon.
> > [  OK  ] Started NTP client/server.
> > [  OK  ] Finished Run a configured list of systemtap scripts at system startup..
> > [  OK  ] Started User Login Management.
> > [  OK  ] Started firewalld - dynamic firewall daemon.
> > [  OK  ] Reached target Preparation for Network.
> >          Starting Network Manager...
> >          Starting Hostname Service...
> > [  OK  ] Started Hostname Service.
> >          Starting Network Manager Script Dispatcher Service...
> > [   39.253277] RTL8226B_RTL8221B 2.5Gbps PHY r8169-2-c500:00: attached PHY driver (mii_bus:phy_addr=r8169-2-c500:00, irq=MAC)
> > [  OK  ] Started Network Manager Script Dispatcher Service.
> > [   39.469916] r8169 0002:c5:00.0 enP2p197s0: Link is Down
> > [   39.517430] RTL8226B_RTL8221B 2.5Gbps PHY r8169-2-c900:00: attached PHY driver (mii_bus:phy_addr=r8169-2-c900:00, irq=MAC)
> > [   39.752713] r8169 0002:c9:00.0 enP2p201s0: Link is Down
> > [  OK  ] Started Network Manager.
> > [  OK  ] Reached target Network.
> >          Starting Network Manager Wait Online...
> >          Starting GSSAPI Proxy Daemon...
> >          Starting /etc/rc.d/rc.local Compatibility...
> >          Starting OpenSSH server daemon...
> >          Starting Dynamic System Tuning Daemon...
> >          Starting Authorization Manager...
> > [  OK  ] Started /etc/rc.d/rc.local Compatibility.
> > [  OK  ] Started OpenSSH server daemon.
> > [  OK  ] Started GSSAPI Proxy Daemon.
> > [  OK  ] Reached target NFS client services.
> > [  OK  ] Reached target Preparation for Remote File Systems.
> > [  OK  ] Reached target Remote File Systems.
> >          Starting Permit User Sessions...
> > [  OK  ] Finished Permit User Sessions.
> > [  OK  ] Started Deferred execution scheduler.
> > [  OK  ] Started Command Scheduler.
> >          Starting Hold until boot process finishes up...
> >          Starting Terminate Plymouth Boot Screen...
> > [   41.894739] r8169 0002:c5:00.0 enP2p197s0: Link is Up - 1Gbps/Full - flow control rx/tx
> > 
> > 
> > Authorized users only. All activities may be monitored and reported.
> > openeuler-riscv64 login: root
> > Password: 
> > Last login: Mon Mar 30 22:23:28 on tty1
> > 
> > Authorized users only. All activities may be monitored and reported.
> > 
> > 
> > Welcome to 6.6.127+
> > 
> > System information as of time:  Mon Mar 30 22:38:22 CST 2026
> > 
> > System load:    0.16
> > Memory used:    .5%
> > Swap used:      0.0%
> > Usage On:       3%
> > IP address:     192.168.1.9
> > Users online:   1
> > 
> > 
> > [root@openeuler-riscv64 ~]# poweroff
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > poweroff
> > ```
> > [  OK  ] Reached target Switch Root.
> >          Starting Switch Root...
> > [   33.209267] systemd-journald[606]: Received SIGTERM from PID 1 (systemd).
> > [   33.620485] systemd[1]: systemd v255-34.oe2403sp1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA -SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDIS)
> > [   33.664117] systemd[1]: Detected architecture riscv64.
> > 
> > Welcome to openEuler 24.03 (LTS-SP1)!
> > 
> > [   33.680609] systemd[1]: Hostname set to <openeuler-riscv64>.
> > [   34.006662] systemd[1]: /usr/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file acc.
> > [   34.460534] systemd[1]: initrd-switch-root.service: Deactivated successfully.
> > [   34.474062] systemd[1]: Stopped Switch Root.
> > [   34.487965] systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 1.
> > [  OK  ] Stopped Switch Root.
> > [   34.505914] systemd[1]: Created slice Slice /system/getty.
> > [  OK  ] Created slice Slice /system/getty.
> > [   34.518916] systemd[1]: Created slice Slice /system/modprobe.
> > [  OK  ] Created slice Slice /system/modprobe.
> > [   34.532925] systemd[1]: Created slice Slice /system/serial-getty.
> > [  OK  ] Created slice Slice /system/serial-getty.
> > [   34.547392] systemd[1]: Created slice Slice /system/sshd-keygen.
> > [  OK  ] Created slice Slice /system/sshd-keygen.
> > [   34.561592] systemd[1]: Created slice User and Session Slice.
> > [  OK  ] Created slice User and Session Slice.
> > [   34.573784] systemd[1]: Dispatch Password Requests to Console Directory Watch was skipped because of an unmet condition check (ConditionPathExists=!/run/plymouth/pid).
> > [   34.574193] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
> > [  OK  ] Started Forward Password Requests to Wall Directory Watch.
> > [   34.610316] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
> > [  OK  ] Set up automount Arbitrary Executable File Formats File System Automount Point.
> > [   34.628480] systemd[1]: Stopped target Switch Root.
> > [  OK  ] Stopped target Switch Root.
> > [   34.643364] systemd[1]: Stopped target Initrd File Systems.
> > [  OK  ] Stopped target Initrd File Systems.
> > [   34.658685] systemd[1]: Stopped target Initrd Root File System.
> > [   34.674425] systemd[1]: Reached target Path Units.
> > [  OK  ] Stopped target Initrd Root File System.
> > [   34.684328] systemd[1]: Reached target rpc_pipefs.target.
> > [  OK  ] Reached target Path Units.
> > [   34.699508] systemd[1]: Reached target Slice Units.
> > [  OK  ] Reached target rpc_pipefs.target.
> > [   34.714393] systemd[1]: Reached target Swaps.
> > [  OK  ] Reached target Slice Units.
> > [  OK  ] Reached target Swaps.
> > [   34.729511] systemd[1]: Listening on Device-mapper event daemon FIFOs.
> > [   34.749456] systemd[1]: Listening on LVM2 poll daemon socket.
> > [  OK  ] Listening on Device-mapper event daemon FIFOs.
> > [   34.763014] systemd[1]: Listening on RPCbind Server Activation Socket.
> > [  OK  ] Listening on LVM2 poll daemon socket.
> > [   34.779158] systemd[1]: Reached target RPC Port Mapper.
> > [  OK  ] Listening on RPCbind Server Activation Socket.
> > [  OK  ] Reached target RPC Port Mapper.
> > [   34.800509] systemd[1]: Listening on Process Core Dump Socket.
> > [  OK  ] Listening on Process Core Dump Socket.
> > [   34.817575] systemd[1]: Listening on initctl Compatibility Named Pipe.
> > [  OK  ] Listening on initctl Compatibility Named Pipe.
> > [   34.835866] systemd[1]: Listening on udev Control Socket.
> > [  OK  ] Listening on udev Control Socket.
> > [   34.851731] systemd[1]: Listening on udev Kernel Socket.
> > [  OK  ] Listening on udev Kernel Socket.
> > [   34.901469] systemd[1]: Mounting Huge Pages File System...
> >          Mounting Huge Pages File System...
> > [   34.921586] systemd[1]: Mounting POSIX Message Queue File System...
> >          Mounting POSIX Message Queue File System...
> > [   34.946587] systemd[1]: Mounting Kernel Debug File System...
> >          Mounting Kernel Debug File System...
> > [   34.969333] systemd[1]: Mounting Kernel Trace File System...
> >          Mounting Kernel Trace File System...
> > [   34.991219] systemd[1]: Mounting Temporary Directory /tmp...
> >          Mounting Temporary Directory /tmp...
> > [   35.002823] systemd[1]: Kernel Module supporting RPCSEC_GSS was skipped because of an unmet condition check (ConditionPathExists=/etc/krb5.keytab).
> > [   35.008768] systemd[1]: Starting Create List of Static Device Nodes...
> >          Starting Create List of Static Device Nodes...
> > [   35.045982] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
> >          Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
> > [   35.065358] systemd[1]: Starting Load Kernel Module configfs...
> >          Starting Load Kernel Module configfs...
> > [   35.087331] systemd[1]: Starting Load Kernel Module drm...
> >          Starting Load Kernel Module drm...
> > [   35.107834] systemd[1]: Starting Load Kernel Module fuse...
> >          Starting Load Kernel Module fuse...
> > [   35.122507] systemd[1]: plymouth-switch-root.service: Deactivated successfully.
> > [   35.123189] systemd[1]: Stopped Plymouth switch root service.
> > [  OK  ] Stopped Plymouth switch root service.
> > [   35.152572] systemd[1]: systemd-fsck-root.service: Deactivated successfully.
> > [   35.153217] systemd[1]: Stopped File System Check on Root Device.
> > [  OK  ] Stopped File System Check on Root Device.
> > [   35.188134] systemd[1]: Starting Journal Service...
> >          Starting Journal Service...
> > [   35.198581] systemd[1]: Load Kernel Modules was skipped because no trigger condition checks were met.
> > [   35.203780] systemd[1]: Starting Generate network units from Kernel command line...
> >          Starting Generate network units from Kernel command line...
> > [   35.233827] systemd[1]: Starting Remount Root and Kernel File Systems...
> >          Starting Remount Root and Kernel File Systems...
> > [   35.250723] systemd[1]: Starting Apply Kernel Variables...
> >          Starting Apply Kernel Variables...
> > [   35.267004] systemd[1]: Starting Coldplug All udev Devices...
> >          Starting Coldplug All udev Devices...
> > [   35.281708] systemd-journald[1201]: Collecting audit messages is disabled.
> > [   35.282511] systemd[1]: Mounted Huge Pages File System.
> > [  OK  ] Mounted Huge Pages File System.
> > [   35.305714] systemd[1]: Mounted POSIX Message Queue File System.
> > [   35.315684] EXT4-fs (nvme0n1p3): re-mounted 07617bd8-13da-4749-97a3-2b548687b739 r/w.
> > [  OK  ] Mounted POSIX Message Queue File System.
> > [   35.335786] systemd[1]: Started Journal Service.
> > [  OK  ] Started Journal Service.
> > [  OK  ] Mounted Kernel Debug File System.
> > [  OK  ] Mounted Kernel Trace File System.
> > [  OK  ] Mounted Temporary Directory /tmp.
> > [  OK  ] Finished Create List of Static Device Nodes.
> > [  OK  ] Finished Load Kernel Module configfs.
> > [  OK  ] Finished Load Kernel Module drm.
> > [  OK  ] Finished Load Kernel Module fuse.
> > [  OK  ] Finished Generate network units from Kernel command line.
> > [  OK  ] Finished Remount Root and Kernel File Systems.
> >          Mounting FUSE Control File System...
> >          Mounting Kernel Configuration File System...
> >          Starting Flush Journal to Persistent Storage...
> >          Starting Load/Save OS Random Seed...
> >          Starting Create Static Device Nodes in /dev gracefully...
> > [  OK  ] Mounted FUSE Control File System.
> > [  OK  ] Mounted Kernel Configuration File System.
> > [  OK  ] Finished Apply Kernel Variables.
> > [   35.526662] systemd-journald[1201]: Received client request to flush runtime journal.
> > [   35.550024] systemd-journald[1201]: /var/log/journal/552c396b6af0485990643f5de1788949/system.journal: Realtime clock jumped backwards relative to last journal entry, rotating.
> > [  OK  ] Finished    35.568502] systemd-journald[1201]: Rotating system journal.
> > ;1;39mCreate Static Device Nodes in /dev gracefully.
> >          Starting Create Static Device Nodes in /dev...
> > [  OK  ] Finished Create Static Device Nodes in /dev.
> >          Starting Rule-based Manager for Device Events and Files...
> > [  OK  ] Finished Flush Journal to Persistent Storage.
> > [  OK  ] Started Rule-based Manager for Device Events and Files.
> >          Starting Load Kernel Module fuse...
> > [  OK  ] Finished Coldplug All udev Devices.
> > [  OK  ] Finished Load Kernel Module fuse.
> > [   36.191287] sophgo-spifmc 7000180000.flash-controller: gd25lb512me (65536 Kbytes)
> > [  OK  ] Stopped Virtual Console Setup.
> >          Stopping Virtual Console Setup...
> > [   36.221724] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   36.225775] sophgo-spifmc 7002180000.flash-controller: gd25lb512me (65536 Kbytes)
> > [   36.232401] gpio-keys soc:gpio-restart: there is not valid maps for state default
> >          Starting Virtual Console Setup...
> > [   36.256299] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   36.256647] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [   36.273598] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
> > [   36.290837] snd_hda_intel 0000:01:00.1: Force to snoop mode by module option
> > [   36.306357] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> > [   36.316354] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > [  OK  ] Finished Virtual Console Setup.
> > [   36.617211] random: crng init done
> > [  OK  ] Finished Load/Save OS Random Seed.
> > [  OK  ] Finished Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
> > [  OK  ] Reached target Preparation for Local File Systems.
> >          Mounting /boot...
> > [   36.760150] FAT-fs (nvme0n1p2): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> > [  OK  ] Mounted /boot.
> >          Mounting /boot/efi...
> > [   36.833966] FAT-fs (nvme0n1p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> > [  OK  ] Mounted /boot/efi.
> > [  OK  ] Reached target Local File Systems.
> >          Starting Tell Plymouth To Write Out Runtime Data...
> >          Starting Create Volatile Files and Directories...
> > [  OK  ] Finished Tell Plymouth To Write Out Runtime Data.
> > [  OK  ] Finished Create Volatile Files and Directories.
> >          Starting Security Auditing Service...
> >          Starting RPC Bind...
> > [  OK  ] Started RPC Bind.
> > [  OK  ] Started Security Auditing Service.
> >          Starting Record System Boot/Shutdown in UTMP...
> > [  OK  ] Finished Record System Boot/Shutdown in UTMP.
> > [  OK  ] Reached target System Initialization.
> > [  OK  ] Started dnf makecache --timer.
> > [  OK  ] Started Daily Cleanup of Temporary Dire[   37.309183] snd_hda_intel 0000:01:00.1: azx_get_response timeout, switching to polling mode: last cmd=0x000f0000
> > ctories.
> > [  OK  ] Reached target Timer Units.
> > [  OK  [   37.323629] snd_hda_intel 0000:01:00.1: bound 0000:01:00.0 (ops radeon_audio_component_bind_ops [radeon])
> > ] Listening on D-Bus System Message Bus Socket.
> > [  OK  ] Listening on PC/SC Smart Card Daemon[   37.341862] gpio-keys soc:gpio-poweroff: there is not valid maps for state default
> >  Activation Socket.
> > [   37.342172] gpio-keys soc:gpio-restart: there is not valid maps for state default
> > 2m  OK  ] Reached target    37.345625] input: HDA ATI HDMI HDMI/DP,pcm=3 as /devices/platform/7060000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.1/sound/card0/input52
> > ;1;39mSocket Units.
> > [  OK  ] Reached target Basic System.
> >          Starting NTP client/server...
> >          Starting D-Bus System Message Bus...
> >          Starting Restore /run/initramfs on shutdown...
> >          Starting Update RTC With System Clock...
> >          Starting irqbalance daemon...
> > [  OK  ] Started libstoragemgmt plug-in server daemon.
> > [  OK  ] Started resize rootfs.
> > [  OK  ] Started Hardware RNG Entropy Gatherer Daemon.
> >          Starting Self Monitoring and Reporting Technology (SMART) Daemon...
> > [  OK  ] Reached target sshd-keygen.target.
> >          Starting User Login Management...
> >          Starting Run a configured list of systemtap scripts at system startup....
> > [  OK  ] Started D-Bus System Message Bus.
> > [  OK  ] Finished Restore /run/initramfs on shutdown.
> > 1;-1f[  OK  ] Stopped Permit User Sessions.
> > [  OK  ] Stopped target Remote File Systems.
> > [  OK  ] Stopped target Preparation for Remote File Systems.
> > [  OK  ] Stopped target NFS client services.
> >          Stopping GSSAPI Proxy Daemon...
> > [  OK  ] Stopped Dynamic System Tuning Daemon.
> > [  OK  ] Stopped GSSAPI Proxy Daemon.
> > [  OK  ] Started Show Plymouth Power Off Screen.
> > [  OK  ] Stopped target Network.
> >          Stopping Network Manager...
> > [  OK  ] Stopped Network Manager.
> > [  OK  ] Stopped target Preparation for Network.
> >          Stopping firewalld - dynamic firewall daemon...
> > [  OK  ] Stopped Generate network units from Kernel command line.
> > [  OK  ] Stopped firewalld - dynamic firewall daemon.
> >          Stopping D-Bus System Message Bus...
> >          Stopping Authorization Manager...
> > [  OK  ] Stopped D-Bus System Message Bus.
> > [  OK  ] Stopped Authorization Manager.
> > [  OK  ] Stopped target Basic System.
> > [  OK  ] Stopped Forward Password Requests to Plymouth Directory Watch.
> > [  OK  ] Stopped target Path Units.
> > [  OK  ] Stopped Forward Password Requests to Wall Directory Watch.
> > [  OK  ] Stopped target Slice Units.
> > [  OK  ] Removed slice User and Session Slice.
> > [  OK  ] Stopped target Socket Units.
> > [  OK  ] Closed D-Bus System Message Bus Socket.
> > [  OK  ] Closed PC/SC Smart Card Daemon Activation Socket.
> > [  OK  ] Stopped target System Initialization.
> > [  OK  ] Unset automount Arbitrary Executable File Formats File System Automount Point.
> > [  OK  ] Stopped Apply Kernel Variables.
> > [  OK  ] Closed Process Core Dump Socket.
> >          Stopping Record System Boot/Shutdown in UTMP...
> > [  OK  ] Stopped Record System Boot/Shutdown in UTMP.
> >          Stopping Security Auditing Servi[  636.281948] audit: type=1305 audit(1774881583.167:96): op=set audit_pid=0 old=1422 auid=4294967295 ses=4294967295 subj=unconfined res=1
> > ce...
> > [  636.299707] audit: type=1131 audit(1774881583.183:97): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=auditd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
> > [  OK  ] Stopped   636.319649] audit: type=1131 audit(1774881583.203:98): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termi'
> > 1;39mSecurity Auditing Service.
> > [  OK  ] Stopped Create Volatile Files and Directories.
> > [  OK  ] Stopped target Local File Systems.
> >          Unmounting /boot/efi...
> >          Unmounting Temporary Directory /tmp...
> > [  OK  ] Unmounted Temporary Directory /tmp.
> > [  OK  ] Stopped target Swaps.
> > [  OK  ] Unmounted /boot/efi.
> >          Unmounting /boot...
> > [  OK  ] Unmounted /boot.
> > [  OK  ] Stopped target Preparation for Local File Syste[  636.485345] audit: type=1131 audit(1774881583.367:99): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-remount-fs comm="systemd" exe="/usr/lib/syst'
> > ms.
> > [  OK  ] Re[  636.509090] audit: type=1131 audit(1774881583.391:100): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup-dev comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? termi'
> > ached target Unmount Al[  636.533088] audit: type=1131 audit(1774881583.415:101): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup-dev-early comm="systemd" exe="/usr/lib/systemd/systemd" hostn'
> > l Filesystems.
> >          St[  636.559414] audit: type=1131 audit(1774881583.443:102): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=lvm2-monitor comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=succ'
> > opping Monitoring of LV[  636.581659] audit: type=1130 audit(1774881583.463:103): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-poweroff comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? ter'
> > M2 mirrors, snapshots etc. using[  636.603011] audit: type=1131 audit(1774881583.463:104): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-poweroff comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? a'
> >  dmeventd or progress polling...
> > [  OK  ] Stopped Remount Root and Kernel File Systems.
> > [  OK  ] Stopped Create Static Device Nodes in /dev.
> > [  OK  ] Stopped Create Static Device Nodes in /dev gracefully.
> > [  OK  ] Stopped Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
> > [  OK  ] Reached target System Shutdown.
> > [  OK  ] Reached target Late Shutdown Services.
> > [  OK  ] Finished System Power Off.
> > [  OK  ] Reached target System Power Off.
> > [  636.797550] systemd-shutdown[1]: Syncing filesystems and block devices.
> > [  636.812866] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
> > [  636.922730] systemd-journald[1201]: Received SIGTERM from PID 1 (systemd-shutdow).
> > [  636.984247] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
> > [  637.177412] systemd-shutdown[1]: Unmounting file systems.
> > [  637.186000] (sd-remount)[2172]: Remounting '/' read-only with options ''.
> > [  637.244917] EXT4-fs (nvme0n1p3): re-mounted 07617bd8-13da-4749-97a3-2b548687b739 ro.
> > [  637.307447] systemd-shutdown[1]: All filesystems unmounted.
> > [  637.313192] systemd-shutdown[1]: Deactivating swaps.
> > [  637.318493] systemd-shutdown[1]: All swaps deactivated.
> > [  637.323865] systemd-shutdown[1]: Detaching loop devices.
> > [  637.334092] systemd-shutdown[1]: All loop devices detached.
> > [  637.339772] systemd-shutdown[1]: Stopping MD devices.
> > [  637.345168] systemd-shutdown[1]: All MD devices stopped.
> > [  637.350568] systemd-shutdown[1]: Detaching DM devices.
> > [  637.355991] systemd-shutdown[1]: All DM devices detached.
> > [  637.361474] systemd-shutdown[1]: All filesystems, swaps, loop devices, MD devices and DM devices detached.
> > [  637.410897] systemd-shutdown[1]: Syncing filesystems and block devices.
> > [  637.417769] systemd-shutdown[1]: Powering off.
> > [  637.522257] r8169 0002:c5:00.0 enP2p197s0: Link is Down
> > [  637.553174] reboot: Power down
> > mango_system_reset: chip is not mango
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 此时风扇狂转
> 
> [ 0.000000] Machine model: Sophgo Mango [ 0.000000] SBI specification v1.0 detected [ 0.000000] SBI implementation ID=0x1 Version=0x10002 [ 0.000000] SBI TIME extension detected [ 0.000000] SBI IPI extension detected [ 0.000000] SBI RFENCE extension detected [ 0.000000] SBI SRST extension detected 如上日志可以看出sbi并没有开启FWFT特性（如果打开会有SBI FWFT extension detected输出），因此这个系列的补丁其实并没有生效。
> 
> 而最后打印 [ 637.553174] reboot: Power down mango_system_reset: chip is not mango 代表内核层面的关机流程已经完成，但硬件/固件复位阶段失败，芯片无法正确进入断电状态导致风扇狂转；这是一个底层固件/硬件兼容性问题，不是内核通用代码的问题。如果有其它型号的设备，是否可以更换一个再测试一下呢

我又测试了一遍，关机正常了，复盘了之前的集成测试分支，发现意外集成了237号pr，该pr会导致关机不下电
